{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.11"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.0.1-dev.jar",
          "url": "honoka-kotlin-utils-1.0.1-dev.jar",
          "size": 6502,
          "sha512": "3246caa2cdb8918fbbf1807a58a8a30316ebf16ca0507e3e3e63ac6d9df30acab8d246dc3d45f20acec659ecc6958ef6617a0152168e86d213237a2d8e309007",
          "sha256": "a58cc986639c98088881ef3886245568111889b5d1e66ae6d63d7dacdad94ff3",
          "sha1": "7b9c25960c9209c9a1cebea8de7dd6f7ae299ab4",
          "md5": "8951ed0e723a995c411751d871bf3d9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.11"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.0.1-dev.jar",
          "url": "honoka-kotlin-utils-1.0.1-dev.jar",
          "size": 6502,
          "sha512": "3246caa2cdb8918fbbf1807a58a8a30316ebf16ca0507e3e3e63ac6d9df30acab8d246dc3d45f20acec659ecc6958ef6617a0152168e86d213237a2d8e309007",
          "sha256": "a58cc986639c98088881ef3886245568111889b5d1e66ae6d63d7dacdad94ff3",
          "sha1": "7b9c25960c9209c9a1cebea8de7dd6f7ae299ab4",
          "md5": "8951ed0e723a995c411751d871bf3d9c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.0.1-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.0.1-dev-sources.jar",
          "size": 3081,
          "sha512": "e647b013385e509d2cf2f472c2e41bc972e060d29b7a11c89b0b18337b45274c7c9b05d116b1082bb7c96eddafd421dd9c3877380e76f9eecac1faa719365f87",
          "sha256": "41819944aaf56aaeff0c242cd8438790454bde1a670bf85371cf90b4ea30c646",
          "sha1": "0e0ecc44d70a0189bd379f8f26a1e1db6ef802ae",
          "md5": "cf0ef88542c6e93c325c2e7a8ef07ac8"
        }
      ]
    }
  ]
}
