{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.11"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.0.1-dev.jar",
          "url": "honoka-kotlin-utils-1.0.1-dev.jar",
          "size": 6502,
          "sha512": "ac0f4ad7cead7b5bc8b9aff6fe8265c017980765d51cd06f5ae06397e38c302f77b2483cd6952a212e88427d60deef0e70f0d66ecc68f154a1c1635d2eaa798e",
          "sha256": "1bda6fb9dd4d29350ae6f4b51a8b980142a01e7c65689f8d7fc5d767dad0d03b",
          "sha1": "8ab597015d5faeafc1550de6e37574c2ef000e27",
          "md5": "eda4d5450574bcc2d51e5ab4a3740c92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.11"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.0.1-dev.jar",
          "url": "honoka-kotlin-utils-1.0.1-dev.jar",
          "size": 6502,
          "sha512": "ac0f4ad7cead7b5bc8b9aff6fe8265c017980765d51cd06f5ae06397e38c302f77b2483cd6952a212e88427d60deef0e70f0d66ecc68f154a1c1635d2eaa798e",
          "sha256": "1bda6fb9dd4d29350ae6f4b51a8b980142a01e7c65689f8d7fc5d767dad0d03b",
          "sha1": "8ab597015d5faeafc1550de6e37574c2ef000e27",
          "md5": "eda4d5450574bcc2d51e5ab4a3740c92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.0.1-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.0.1-dev-sources.jar",
          "size": 3081,
          "sha512": "83248a83539cf0929419ca13a965aaa05fdefb6f599b0cf968e221068e2e8a0a0298bd086fce70d28c1e3c349fe8c534f108d1972e30a7200b2ba72ab1901605",
          "sha256": "c523aaee1bf4ab745c4df199c6a981ef490e2c12dd02858d24eba1eae398bb92",
          "sha1": "49353d96fb532c5963fa9d63218d42053e868ab3",
          "md5": "50e97bef1587226f9b057345d98bd9ea"
        }
      ]
    }
  ]
}
