{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "2.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-2.0.0-dev.jar",
          "url": "honoka-utils-2.0.0-dev.jar",
          "size": 72035,
          "sha512": "9868ff708d7d0f1dc5ef2a636b1156fce40688cb18e138b0c1512066de7b213ee48f3b2bf1211353471e21dafe3680101574e61119a30bea8ca0d76f644aa7fb",
          "sha256": "cbce691da08f8b83448189d04d2154cfca1ef75b4d3a9807883eebbaf8c38b01",
          "sha1": "457ded777daec6959701abccb1a438da014e6177",
          "md5": "b3a1402a0a1cc475392e51f4aeb7986a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-2.0.0-dev.jar",
          "url": "honoka-utils-2.0.0-dev.jar",
          "size": 72035,
          "sha512": "9868ff708d7d0f1dc5ef2a636b1156fce40688cb18e138b0c1512066de7b213ee48f3b2bf1211353471e21dafe3680101574e61119a30bea8ca0d76f644aa7fb",
          "sha256": "cbce691da08f8b83448189d04d2154cfca1ef75b4d3a9807883eebbaf8c38b01",
          "sha1": "457ded777daec6959701abccb1a438da014e6177",
          "md5": "b3a1402a0a1cc475392e51f4aeb7986a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-2.0.0-dev-sources.jar",
          "url": "honoka-utils-2.0.0-dev-sources.jar",
          "size": 38277,
          "sha512": "52db7bd41db3582eb6096a66a00652440623c8f0e407a46a89ad16b79b0a6114641ae7dff6f38a100f3a2a6043fcde7d63fcc6ae4ef8cc14187dfe1e8409f66e",
          "sha256": "173c86815643e53135baa5d7086e62a29246f8a03c5844d7994f76205f9b2b22",
          "sha1": "17df12fb98b4d08b0c6084ddee77da4529e4b713",
          "md5": "720511bfeb35d001f8884f9bee05dd2d"
        }
      ]
    }
  ]
}
