{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "2.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-2.0.0-dev.jar",
          "url": "honoka-utils-2.0.0-dev.jar",
          "size": 72035,
          "sha512": "4fc1bb261e68156e5de3fc54ce8b2afbeb31fb535dc01848f5c63d76cc6e90b0e41be4202b7be12de3a60371f095a1d5b86a709ee3bccf94c523a608ad8bfb37",
          "sha256": "896edcb580954c3960671c4091d0fbebdcabc2f7438edb87b45357033db6691b",
          "sha1": "fb0ab4377b51fd5129b3f273390faaa5a14c5280",
          "md5": "d82d670640aa1a8b171124d847a809f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-2.0.0-dev.jar",
          "url": "honoka-utils-2.0.0-dev.jar",
          "size": 72035,
          "sha512": "4fc1bb261e68156e5de3fc54ce8b2afbeb31fb535dc01848f5c63d76cc6e90b0e41be4202b7be12de3a60371f095a1d5b86a709ee3bccf94c523a608ad8bfb37",
          "sha256": "896edcb580954c3960671c4091d0fbebdcabc2f7438edb87b45357033db6691b",
          "sha1": "fb0ab4377b51fd5129b3f273390faaa5a14c5280",
          "md5": "d82d670640aa1a8b171124d847a809f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-2.0.0-dev-sources.jar",
          "url": "honoka-utils-2.0.0-dev-sources.jar",
          "size": 38277,
          "sha512": "42b5ad7f8ab1b7beb110f69bd171dccb0a9bdf870647803e167cfe3cb035cbd56f7d67ac7460327937a923c47e6e2897dadd49481f52d09dce2c29be44317b46",
          "sha256": "70d6729852c264a771927929e3edfdc129e01d3c7a3072a7c4eb7ea4c32e27d2",
          "sha1": "18909779db4e10f04acb4b55bee50f67e0ecc27e",
          "md5": "eb0a92955ebf646df9c1f8dbf8bb1cd7"
        }
      ]
    }
  ]
}
