{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.0.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.0.2-dev.jar",
          "url": "honoka-kotlin-utils-1.0.2-dev.jar",
          "size": 61520,
          "sha512": "1d66bff6bb2a5c6fc35ea4dc9ce0e80e01ff5c744f4129670b7d7e827cb0ed34657e095616744df019d03c528cafd322e976c333b470a8bafa56de07d144af34",
          "sha256": "7eeb8351fc566eb2d1e350fbddb8003bc380c2eac28e70fce68d4b097a38f79a",
          "sha1": "a90eec40f03cde395e02da59a4e0aa31372475a0",
          "md5": "a0263ae409428d61d6a936cfab79bc7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.0.2-dev.jar",
          "url": "honoka-kotlin-utils-1.0.2-dev.jar",
          "size": 61520,
          "sha512": "1d66bff6bb2a5c6fc35ea4dc9ce0e80e01ff5c744f4129670b7d7e827cb0ed34657e095616744df019d03c528cafd322e976c333b470a8bafa56de07d144af34",
          "sha256": "7eeb8351fc566eb2d1e350fbddb8003bc380c2eac28e70fce68d4b097a38f79a",
          "sha1": "a90eec40f03cde395e02da59a4e0aa31372475a0",
          "md5": "a0263ae409428d61d6a936cfab79bc7f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.0.2-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.0.2-dev-sources.jar",
          "size": 15712,
          "sha512": "42c0b9cfbf027b25029a6ad707c9dda6c7a8a6dcb867cacb4d3bcf68770ac6a823b5d0b104742f5df42fd97257691d6102a08aebf5699776d55ed29725c2c34e",
          "sha256": "994f0bc450e8a0abc44d32581c79eb7839e6e3d0ce8d20246ae3d94a60864b56",
          "sha1": "0463889c2bfca297baefa86055af9d7cc4bdeb26",
          "md5": "f1fcdc41c12d2f1d432f3ab51f5d1f87"
        }
      ]
    }
  ]
}
