{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.0.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.0.2-dev.jar",
          "url": "honoka-kotlin-utils-1.0.2-dev.jar",
          "size": 84973,
          "sha512": "2bffa97aa47967fa52c3138cae28d49242df3e2fc5e1c050ffcefaaeb354ea69437690a38bc86ef6db2df07ad23846688b545738eec451a3a230224581b0a8e0",
          "sha256": "3d2e1b1fcac01f10e994217f9f8734cf406ca9b2356823cd28cc2e11f7f3258e",
          "sha1": "ce6d15080b0e7333325b25a47df71c6a26cbb46b",
          "md5": "07ec3197ce1fe1a2403feaaa83fd8ffc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.0.2-dev.jar",
          "url": "honoka-kotlin-utils-1.0.2-dev.jar",
          "size": 84973,
          "sha512": "2bffa97aa47967fa52c3138cae28d49242df3e2fc5e1c050ffcefaaeb354ea69437690a38bc86ef6db2df07ad23846688b545738eec451a3a230224581b0a8e0",
          "sha256": "3d2e1b1fcac01f10e994217f9f8734cf406ca9b2356823cd28cc2e11f7f3258e",
          "sha1": "ce6d15080b0e7333325b25a47df71c6a26cbb46b",
          "md5": "07ec3197ce1fe1a2403feaaa83fd8ffc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.0.2-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.0.2-dev-sources.jar",
          "size": 18958,
          "sha512": "dccedf2b9d1202fb3d180bc4b3a2115764f6784c220a6d89098ccca548d655f7b880ab1f9bbc4bb919df18a6ea7e569f5339b537457c02fbe62af1a39d53f1d4",
          "sha256": "b3c543fa013b0af5a64dd098371e986d3a11ccc94466b047199ff57470ea2ca2",
          "sha1": "27cc3a95524fbc3e722db2699d39427d7d9e90ca",
          "md5": "fa7b482500689a76778b91360a19b9a5"
        }
      ]
    }
  ]
}
