{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.0.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.0.2-dev.jar",
          "url": "honoka-kotlin-utils-1.0.2-dev.jar",
          "size": 18650,
          "sha512": "6cc26eaea6b821d75a930c24b7d57d22d81ee2f1eaeca1f5979e227abecc2355de3e574a99107deada33ff1cfb94aeda9dcdafd6d114a0f40c3834e3289d6075",
          "sha256": "31b41a8786b92c9b045f018088785bb669391fd4636a606d5baca5bf06fce3fc",
          "sha1": "1fc6734ce7a8ef43b4f461fc6a4eb251dcd01613",
          "md5": "ea8f2b2493a83e24da91483cdaa5734a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.0.2-dev.jar",
          "url": "honoka-kotlin-utils-1.0.2-dev.jar",
          "size": 18650,
          "sha512": "6cc26eaea6b821d75a930c24b7d57d22d81ee2f1eaeca1f5979e227abecc2355de3e574a99107deada33ff1cfb94aeda9dcdafd6d114a0f40c3834e3289d6075",
          "sha256": "31b41a8786b92c9b045f018088785bb669391fd4636a606d5baca5bf06fce3fc",
          "sha1": "1fc6734ce7a8ef43b4f461fc6a4eb251dcd01613",
          "md5": "ea8f2b2493a83e24da91483cdaa5734a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.0.2-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.0.2-dev-sources.jar",
          "size": 6800,
          "sha512": "714ac830ba8f629f7df4bcb37a7151d6c22979dd81ff30d1a04fc6bce85809f8faa9d3db05bbda0bbd6a2d8c30887fbd59c80147956726949f826c40e4c33d38",
          "sha256": "52bbe70af3b08421cd52774a30fe6422b1dd5d4bbe5d167bddfe6170a8527677",
          "sha1": "fe7aa3268f539699217ee9dd05aa8df60e3231c0",
          "md5": "6ad45445ef4e2918e68bf37c7a5baafe"
        }
      ]
    }
  ]
}
