{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-framework-utils",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.4.jar",
          "url": "honoka-framework-utils-1.0.4.jar",
          "size": 16868,
          "sha512": "f843965cddf172b9acd6d973a7c354f1f7bcb636bcfaf623dfc79ffebd578264fc016727f987f32385087f54fbbdb80d40c3cdb59ea94798cb0c96277c3e84a3",
          "sha256": "60fb596f1d3392a67d4531e5d4c9ba5e4feb4003befac0fcb49557d1882e2200",
          "sha1": "fb71901aabe50ca900ef97b368365862cb393e29",
          "md5": "6d37b8d45256bae5d70fab64e72dbb67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.4.jar",
          "url": "honoka-framework-utils-1.0.4.jar",
          "size": 16868,
          "sha512": "f843965cddf172b9acd6d973a7c354f1f7bcb636bcfaf623dfc79ffebd578264fc016727f987f32385087f54fbbdb80d40c3cdb59ea94798cb0c96277c3e84a3",
          "sha256": "60fb596f1d3392a67d4531e5d4c9ba5e4feb4003befac0fcb49557d1882e2200",
          "sha1": "fb71901aabe50ca900ef97b368365862cb393e29",
          "md5": "6d37b8d45256bae5d70fab64e72dbb67"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.4-sources.jar",
          "url": "honoka-framework-utils-1.0.4-sources.jar",
          "size": 10546,
          "sha512": "8dfa16f762d344e96a59ed8b4bdb7578b768f975d5335902117c55e29b6eb77dddc42df812bad976d3ad56fa96d2f91ebb0097c1b3e038de32ec7d085f570a2d",
          "sha256": "e45db79cf62e5ea61a8a28a4a874324dfb4ddf31d72a8e66f99d791faf5d9103",
          "sha1": "596afbb112faf9566ac58e8f01eac1e9b95efb0f",
          "md5": "413d014bfcbb505fb00e116aa3b0696f"
        }
      ]
    }
  ]
}
