{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.2.jar",
          "url": "honoka-utils-1.0.2.jar",
          "size": 67452,
          "sha512": "a9e51e6d0f0cab7e409335d20a33f0e4cf114e42db57112418cac705993d75b9b8da1aa199489cd7da32e6a680c30f7f5d17f8f9106157962dcebd498aea95fe",
          "sha256": "cb15fa706ab146f9a05dcbe1f10027a791c8c7fc1260689da5b4005e99b111bc",
          "sha1": "c91cd35782c9d350dfaa818043b2ec3b9d7141d1",
          "md5": "bdfdefaab3239ee0e160fa3019e52090"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.2.jar",
          "url": "honoka-utils-1.0.2.jar",
          "size": 67452,
          "sha512": "a9e51e6d0f0cab7e409335d20a33f0e4cf114e42db57112418cac705993d75b9b8da1aa199489cd7da32e6a680c30f7f5d17f8f9106157962dcebd498aea95fe",
          "sha256": "cb15fa706ab146f9a05dcbe1f10027a791c8c7fc1260689da5b4005e99b111bc",
          "sha1": "c91cd35782c9d350dfaa818043b2ec3b9d7141d1",
          "md5": "bdfdefaab3239ee0e160fa3019e52090"
        }
      ]
    }
  ]
}
