{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender",
    "module": "lavender-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lavender-api-1.0.0.jar",
          "url": "lavender-api-1.0.0.jar",
          "size": 23329,
          "sha512": "416d76bce41dd85194a5def4481c4064dcd1e7298974865ac26df16f3ade338d3bc5e5107f34a68c6bb64b7646016cb8dbdaa1f80e9b3297db649ba7df7e8223",
          "sha256": "f7abde349f534ffd1d4f496434317812daa63fa192612a371908a1f22c9f3e9c",
          "sha1": "f49ae51e87f58fd28cfeb7707aca9dad77859e63",
          "md5": "8db8933ce6effc93fa6c059a0db26731"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lavender-api-1.0.0.jar",
          "url": "lavender-api-1.0.0.jar",
          "size": 23329,
          "sha512": "416d76bce41dd85194a5def4481c4064dcd1e7298974865ac26df16f3ade338d3bc5e5107f34a68c6bb64b7646016cb8dbdaa1f80e9b3297db649ba7df7e8223",
          "sha256": "f7abde349f534ffd1d4f496434317812daa63fa192612a371908a1f22c9f3e9c",
          "sha1": "f49ae51e87f58fd28cfeb7707aca9dad77859e63",
          "md5": "8db8933ce6effc93fa6c059a0db26731"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavender-api-1.0.0-sources.jar",
          "url": "lavender-api-1.0.0-sources.jar",
          "size": 2929,
          "sha512": "8fafba7aea680959f3e2b7225c113d4fe80bc0086a45add504e85cf3b988dac459b3abf73a4534f50a53c81881fa9591208f621af10b5c33f06f3757c368ea9d",
          "sha256": "5f2e23ccc763696979508a0e9c485f3e7b52fb7bc96a75a384f6dc01185bd35c",
          "sha1": "4d57c71e93a2e4d39dab400a02e73868fe2d1ff0",
          "md5": "6e16a61fbbcabd714ca28ae50f093a08"
        }
      ]
    }
  ]
}
