{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender",
    "module": "lavender-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lavender-api-1.0.0.jar",
          "url": "lavender-api-1.0.0.jar",
          "size": 23329,
          "sha512": "6d8bc7bdc55fb15f12446b2dbd0e3da658dc2f526701ea0ac04a8a06c525b23fd9dbc74f248d2151f99f1e544ac943543880301a689f08e9cc189b68bb6173a0",
          "sha256": "c5f2d27c9a38d0073dc411500a76e946154e8b750825a2f0e36cb9dcaf619cbe",
          "sha1": "ba995efbb9a70c5965697ca40cfa316b755b8f5c",
          "md5": "be346fc400d60ddb580f0aec5c3447ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lavender-api-1.0.0.jar",
          "url": "lavender-api-1.0.0.jar",
          "size": 23329,
          "sha512": "6d8bc7bdc55fb15f12446b2dbd0e3da658dc2f526701ea0ac04a8a06c525b23fd9dbc74f248d2151f99f1e544ac943543880301a689f08e9cc189b68bb6173a0",
          "sha256": "c5f2d27c9a38d0073dc411500a76e946154e8b750825a2f0e36cb9dcaf619cbe",
          "sha1": "ba995efbb9a70c5965697ca40cfa316b755b8f5c",
          "md5": "be346fc400d60ddb580f0aec5c3447ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavender-api-1.0.0-sources.jar",
          "url": "lavender-api-1.0.0-sources.jar",
          "size": 2929,
          "sha512": "caf1e8c64c5163cfa1feda0659f870d66904d54d2cd3781841b26c4f973241eaf869c6010fbfbc3b7f8602a4ef37c5fd4847e537c167776ac5c660e17e82791f",
          "sha256": "75e5401b101095d46ee252a7b8a1e68808279b4bcae398589046f913c39c9837",
          "sha1": "3fc148a1c2ff03795e7ba7e19f0d94989b35b658",
          "md5": "faedceb9e952c8c9a42ce4097fe4f707"
        }
      ]
    }
  ]
}
