{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender",
    "module": "lavender-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lavender-api-1.0.0.jar",
          "url": "lavender-api-1.0.0.jar",
          "size": 23329,
          "sha512": "905cdf9ae43f8892c798196aeb68060944e27415dffe0656073d94309a5a31ae86754aabe833ed31c1f888e06cb16dfa035383087af758a6557902e3044fea4a",
          "sha256": "3149b424ba946fd9a3a3d3959dd7cd36bf41ebb9395e2a7cf6e9a5212786f5a0",
          "sha1": "a5caa761b995aed7f207d31a0bf29ee03d87696b",
          "md5": "e42435d75b117ab1a27ac1115ed5cceb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lavender-api-1.0.0.jar",
          "url": "lavender-api-1.0.0.jar",
          "size": 23329,
          "sha512": "905cdf9ae43f8892c798196aeb68060944e27415dffe0656073d94309a5a31ae86754aabe833ed31c1f888e06cb16dfa035383087af758a6557902e3044fea4a",
          "sha256": "3149b424ba946fd9a3a3d3959dd7cd36bf41ebb9395e2a7cf6e9a5212786f5a0",
          "sha1": "a5caa761b995aed7f207d31a0bf29ee03d87696b",
          "md5": "e42435d75b117ab1a27ac1115ed5cceb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavender-api-1.0.0-sources.jar",
          "url": "lavender-api-1.0.0-sources.jar",
          "size": 2929,
          "sha512": "617c887a72ad067d3eb0663363ce4e37930df3e2b1bbafdaaf9987d34e665314fc389608407e8c79fe259cdc08fd09b0c961002c37c21c4ba7657df3eacbcb1c",
          "sha256": "327d99691434351e0ca1a9426471716dbe3d1cc11669eb64bdd6ea9d3c64553d",
          "sha1": "b7b0820ae28663f60953c9617e8679a1296dfba2",
          "md5": "f43e349ee7ad172aba15fa02346ef9aa"
        }
      ]
    }
  ]
}
