{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "2.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.1-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.1-dev.jar",
          "size": 50125,
          "sha512": "66e424ba04e5d24b07de543e3635924feaaddb30c84ad65c909065fe4c0fc60b65a2cc821b8b4db733a8adb6ccd1b02c8f4d89848adabb965e17d458697cd196",
          "sha256": "ec1f81a578c1842e669271515715cb9676586c96e9c60ef1682d353cf8832a49",
          "sha1": "baa1e90f255eff364e40599e0c80e48e7df218ce",
          "md5": "8273dc951186a5f07e752087699cb6e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.1-dev"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "2.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.1-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.1-dev.jar",
          "size": 50125,
          "sha512": "66e424ba04e5d24b07de543e3635924feaaddb30c84ad65c909065fe4c0fc60b65a2cc821b8b4db733a8adb6ccd1b02c8f4d89848adabb965e17d458697cd196",
          "sha256": "ec1f81a578c1842e669271515715cb9676586c96e9c60ef1682d353cf8832a49",
          "sha1": "baa1e90f255eff364e40599e0c80e48e7df218ce",
          "md5": "8273dc951186a5f07e752087699cb6e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.1-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.1-dev-sources.jar",
          "size": 17685,
          "sha512": "e4b69eac1825e14deaa4f3be9a32b5d20fcbef58cc6528d5208c6469b2809a5dd8451c2a865221911e036b97dffec614cb44f4d889279988b50f9d7f11a90401",
          "sha256": "d688e8411a8ce22464fd8e3bbd9cb91aefed8795386035ecab53d69a89bd86d4",
          "sha1": "ca623a492f2383d83c82e9b5825b07b806b3f79c",
          "md5": "ab218e1bdababfa684a4e1e2f583e917"
        }
      ]
    }
  ]
}
