{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.1-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.1-dev.jar",
          "size": 56797,
          "sha512": "9770d837eb852d763eec3046f720e184f37e4ab3eb7202970cbfad3d601ce5e9083c6f6c7edface7936fa68a2e6acf5ad58b0ba54d2608ae68fc2eefbe04c1cf",
          "sha256": "df534572107d5f6ff9a657ce75face0e3fa4a3c8d30d973ef3dfb95f83d17289",
          "sha1": "85d4a5e8320dc317feb6d3d733abc3d9a10f3aca",
          "md5": "87ab4bb5ceac2d68bf45b95932f27efc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.1-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.1-dev.jar",
          "size": 56797,
          "sha512": "9770d837eb852d763eec3046f720e184f37e4ab3eb7202970cbfad3d601ce5e9083c6f6c7edface7936fa68a2e6acf5ad58b0ba54d2608ae68fc2eefbe04c1cf",
          "sha256": "df534572107d5f6ff9a657ce75face0e3fa4a3c8d30d973ef3dfb95f83d17289",
          "sha1": "85d4a5e8320dc317feb6d3d733abc3d9a10f3aca",
          "md5": "87ab4bb5ceac2d68bf45b95932f27efc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.1-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.1-dev-sources.jar",
          "size": 19064,
          "sha512": "c7231213bf03b44a22a852dad0c95f37af9b45aca84c37f4a9004c772270d7f9bf0c65c83ee026f70a0986adc2ce0086a36bb740926cede71b75ca5111c4db72",
          "sha256": "e69382c6bf958de51e20a247f2abb53ab30fe98cfde47db839222cc358639499",
          "sha1": "114aab4868b427bb69d57f3852748b71fb8f9acf",
          "md5": "73897e5cd47ae6d4b7c246217ebaf837"
        }
      ]
    }
  ]
}
