{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.1-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.1-dev.jar",
          "size": 50125,
          "sha512": "e80a18c922edabb64bc2d7ed3a08e70d286d049b5d511527a1ed9789c99be0b48cefc5f61f640814dc074fe4475ac0426da33922a1f3495209f0d9ce833f74c8",
          "sha256": "12f4b8e8ba0028fc06e4a98f1d8338d71299dd09fa10b9813a20a160b824c60a",
          "sha1": "7258a831be5b92cd207157f4ef6707f4790e8133",
          "md5": "a4a6ec0ab2f4326bd21835a6d87fbed1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.1-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.1-dev.jar",
          "size": 50125,
          "sha512": "e80a18c922edabb64bc2d7ed3a08e70d286d049b5d511527a1ed9789c99be0b48cefc5f61f640814dc074fe4475ac0426da33922a1f3495209f0d9ce833f74c8",
          "sha256": "12f4b8e8ba0028fc06e4a98f1d8338d71299dd09fa10b9813a20a160b824c60a",
          "sha1": "7258a831be5b92cd207157f4ef6707f4790e8133",
          "md5": "a4a6ec0ab2f4326bd21835a6d87fbed1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.1-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.1-dev-sources.jar",
          "size": 17685,
          "sha512": "91a5f23fb387e4008509c940f4a33f1dc8db23bd27b992dddd1572d1ccec054156c22fc65962bf56a113824da511937a800cb2011b3b9f132d43e0b759308f8e",
          "sha256": "69e678be15cf5ffe128abbeb9d40f9bf42871461a7d3364baebf9ec9ecf9260b",
          "sha1": "038f6641486795ab324742f5fab2d998228b30c4",
          "md5": "308da76cd130e59ae8e072162abf4caa"
        }
      ]
    }
  ]
}
