{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.0.jar",
          "url": "honoka-utils-1.0.0.jar",
          "size": 65163,
          "sha512": "8abd608416f3d76032c6ecbca193fd7c5e1083ddaa90175848dab973e2ead22f7c0194f6966a276d1c4cdabb4a83376ea851866cf64cffc03dc0688a33cbea26",
          "sha256": "3e698b5c08a18227c17141fb8a945be1e53473378404b5d50234060dc7468b2e",
          "sha1": "015a7b8d630d67533352e808b7c3fd684163ab5a",
          "md5": "cbae554e99aa92c6ac2b7b025fe221b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.0.jar",
          "url": "honoka-utils-1.0.0.jar",
          "size": 65163,
          "sha512": "8abd608416f3d76032c6ecbca193fd7c5e1083ddaa90175848dab973e2ead22f7c0194f6966a276d1c4cdabb4a83376ea851866cf64cffc03dc0688a33cbea26",
          "sha256": "3e698b5c08a18227c17141fb8a945be1e53473378404b5d50234060dc7468b2e",
          "sha1": "015a7b8d630d67533352e808b7c3fd684163ab5a",
          "md5": "cbae554e99aa92c6ac2b7b025fe221b5"
        }
      ]
    }
  ]
}
