{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.1.3-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.3-dev.jar",
          "url": "honoka-kotlin-utils-1.1.3-dev.jar",
          "size": 65459,
          "sha512": "e3aa9448566fb916ba432c69464b140e0d9d73f32f6ffd34b08dcbee957891e973f04a7111729174c832faed62d8ff7d15040df5a3fd16b84389a17b88d30e2a",
          "sha256": "3c635187764720e6b8d403da8a7a97a66534778b0035acc31d1b8d7ffa23e1fe",
          "sha1": "a1ac64d425d1a3527a36c220092b043208d91b45",
          "md5": "871c08839f086d2db8bda12f194ea204"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.3-dev.jar",
          "url": "honoka-kotlin-utils-1.1.3-dev.jar",
          "size": 65459,
          "sha512": "e3aa9448566fb916ba432c69464b140e0d9d73f32f6ffd34b08dcbee957891e973f04a7111729174c832faed62d8ff7d15040df5a3fd16b84389a17b88d30e2a",
          "sha256": "3c635187764720e6b8d403da8a7a97a66534778b0035acc31d1b8d7ffa23e1fe",
          "sha1": "a1ac64d425d1a3527a36c220092b043208d91b45",
          "md5": "871c08839f086d2db8bda12f194ea204"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.3-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.3-dev-sources.jar",
          "size": 17411,
          "sha512": "7c2f383b59e3c65cada5e0609448d0af5708e4510ad50e2cf4a7c4f5ffc69de24c0cd13c340b3346e2d68a97514c5c660e4f63e3c761d99b4d16ca1e6e693ee5",
          "sha256": "6da9b5203419414dd6b00ce38f8d6eb69abba0fd4b932cbab1fadbe332d17341",
          "sha1": "8143e6535d2da572fffe16d9d6bf66f6ee13801a",
          "md5": "0f842aca1008efa3e0a4d793b95643fe"
        },
        {
          "name": "honoka-kotlin-utils-1.1.3-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.3-dev-sources.jar",
          "size": 17411,
          "sha512": "7c2f383b59e3c65cada5e0609448d0af5708e4510ad50e2cf4a7c4f5ffc69de24c0cd13c340b3346e2d68a97514c5c660e4f63e3c761d99b4d16ca1e6e693ee5",
          "sha256": "6da9b5203419414dd6b00ce38f8d6eb69abba0fd4b932cbab1fadbe332d17341",
          "sha1": "8143e6535d2da572fffe16d9d6bf66f6ee13801a",
          "md5": "0f842aca1008efa3e0a4d793b95643fe"
        }
      ]
    }
  ]
}
