{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.1.3-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.3-dev.jar",
          "url": "honoka-kotlin-utils-1.1.3-dev.jar",
          "size": 61353,
          "sha512": "609770ea7f9d045096b81edfe7cb437dba1f3c803bd4b83a8c9d28941735b0ee71a9928b9088e7e524a18ca1951ca0f2332bdc2a6779bb358416b626f48d2b0e",
          "sha256": "52e5105298cbea0bb6ef3f8209fac610947ca3deb357c840d53c04694770a74e",
          "sha1": "0708e71ad1958c40a48e47972aa931b444af435c",
          "md5": "903dcdf6e259b7b3c60c6a01442ef07c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.3-dev.jar",
          "url": "honoka-kotlin-utils-1.1.3-dev.jar",
          "size": 61353,
          "sha512": "609770ea7f9d045096b81edfe7cb437dba1f3c803bd4b83a8c9d28941735b0ee71a9928b9088e7e524a18ca1951ca0f2332bdc2a6779bb358416b626f48d2b0e",
          "sha256": "52e5105298cbea0bb6ef3f8209fac610947ca3deb357c840d53c04694770a74e",
          "sha1": "0708e71ad1958c40a48e47972aa931b444af435c",
          "md5": "903dcdf6e259b7b3c60c6a01442ef07c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.3-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.3-dev-sources.jar",
          "size": 17202,
          "sha512": "0db79be9e5e552d77ffbe471897c20a1affb871389a1086a80e6be7e2d9fbfff2a8132bde460bd5e6f2ba60a90dd7db5f2313f73bbcb0ee18a1c537443b3f321",
          "sha256": "80782b44010a497d2c9422d3e0b52e7ff1060e105ce6f3cfad467d8f37799a19",
          "sha1": "b72d2b84df6eb6fb7747e3e1ca375d004abeedbf",
          "md5": "01708fd5784b0ae02a706565d80147fc"
        },
        {
          "name": "honoka-kotlin-utils-1.1.3-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.3-dev-sources.jar",
          "size": 17202,
          "sha512": "0db79be9e5e552d77ffbe471897c20a1affb871389a1086a80e6be7e2d9fbfff2a8132bde460bd5e6f2ba60a90dd7db5f2313f73bbcb0ee18a1c537443b3f321",
          "sha256": "80782b44010a497d2c9422d3e0b52e7ff1060e105ce6f3cfad467d8f37799a19",
          "sha1": "b72d2b84df6eb6fb7747e3e1ca375d004abeedbf",
          "md5": "01708fd5784b0ae02a706565d80147fc"
        }
      ]
    }
  ]
}
