{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.1.3-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.3-dev.jar",
          "url": "honoka-kotlin-utils-1.1.3-dev.jar",
          "size": 65741,
          "sha512": "90ae3dbd8d22db313d71f040a4139f0654b110e8a5ca9fe293bf307fbccf7060741e2a471d125798913b022d6dc94999fed054cd9b22465dfa8098129875395a",
          "sha256": "bf7ada5fac5902bf9cbb4250f15b2ffffb4ce2bd24347b8fef6c6f81be54e16e",
          "sha1": "b13466c517e96d0b3948fb08df9f1859246d3902",
          "md5": "d597d708771ef17bacc2ee78db8c38fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.3-dev.jar",
          "url": "honoka-kotlin-utils-1.1.3-dev.jar",
          "size": 65741,
          "sha512": "90ae3dbd8d22db313d71f040a4139f0654b110e8a5ca9fe293bf307fbccf7060741e2a471d125798913b022d6dc94999fed054cd9b22465dfa8098129875395a",
          "sha256": "bf7ada5fac5902bf9cbb4250f15b2ffffb4ce2bd24347b8fef6c6f81be54e16e",
          "sha1": "b13466c517e96d0b3948fb08df9f1859246d3902",
          "md5": "d597d708771ef17bacc2ee78db8c38fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.3-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.3-dev-sources.jar",
          "size": 18400,
          "sha512": "0e0bb1ef46c30fdfd2faa352f43cb946c63d85e03fbb4b65c6709d7ca019175a360d3f785ad681b9e161b015b983e24b954e654494fdb49292974a6a4d6df0c9",
          "sha256": "5269641f552cb3ae1301741a1d904a5ba2f64e6123cca4da3662dfbfcedb6854",
          "sha1": "f24fa0671a645d787ba76120af2081663549cd7a",
          "md5": "14e1ac4b37b84fa0c2cdeafb40367c9e"
        },
        {
          "name": "honoka-kotlin-utils-1.1.3-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.3-dev-sources.jar",
          "size": 18400,
          "sha512": "0e0bb1ef46c30fdfd2faa352f43cb946c63d85e03fbb4b65c6709d7ca019175a360d3f785ad681b9e161b015b983e24b954e654494fdb49292974a6a4d6df0c9",
          "sha256": "5269641f552cb3ae1301741a1d904a5ba2f64e6123cca4da3662dfbfcedb6854",
          "sha1": "f24fa0671a645d787ba76120af2081663549cd7a",
          "md5": "14e1ac4b37b84fa0c2cdeafb40367c9e"
        }
      ]
    }
  ]
}
