{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.1.jar",
          "url": "qqrobot-spring-boot-starter-2.0.1.jar",
          "size": 148197,
          "sha512": "6c54cdf619629942305fb8e41c2e80932a692dc4eeab22d92659f68174577c52eaba056c25760016f429bc0f8ec956478174580bad6f90ff8af57892fc86771b",
          "sha256": "455c6905b9e29e548fe5370d09f9867194be8c71ab9ac6c9ecb4e38d15845904",
          "sha1": "2389bc65d6e59c6e3484efa8575409813b776df3",
          "md5": "572dfb154375cd64da1bb37b06f04804"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.1.jar",
          "url": "qqrobot-spring-boot-starter-2.0.1.jar",
          "size": 148197,
          "sha512": "6c54cdf619629942305fb8e41c2e80932a692dc4eeab22d92659f68174577c52eaba056c25760016f429bc0f8ec956478174580bad6f90ff8af57892fc86771b",
          "sha256": "455c6905b9e29e548fe5370d09f9867194be8c71ab9ac6c9ecb4e38d15845904",
          "sha1": "2389bc65d6e59c6e3484efa8575409813b776df3",
          "md5": "572dfb154375cd64da1bb37b06f04804"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.1-sources.jar",
          "url": "qqrobot-spring-boot-starter-2.0.1-sources.jar",
          "size": 53929,
          "sha512": "cb7ce0f316d54b3b7f1f20ed25a68adace3ee24c560f22e21ce5e100ad0dc22ae14a43c1471d5dee1a754160c60c569b00e2e6a2d20e771fd96657be5e24e31b",
          "sha256": "e42e49b6a662c40b68a9c38a5230fe062cd0b37bc6f3fd653f55e3dd39ee7fb1",
          "sha1": "a0bb0f2a84f5471df3df8e6530c67a1151899c5e",
          "md5": "e2f7b08d01e356f1c1526c4ece6c4b87"
        }
      ]
    }
  ]
}
