{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qqrobot-framework-1.0.1.jar",
          "url": "qqrobot-framework-1.0.1.jar",
          "size": 8174,
          "sha512": "fa681b79c7e8f4ac0580f0ecdaf596207ade0d24aeba281a0be37abfc155af5f5d6588fdb554fcd4a77e1ea991c7823655b989cd554deedefa6f05aa8e30db12",
          "sha256": "8e25b15bea558bf60e5e35ded51e0bbc8d18466ebf6fceb845a006eb6bf8187f",
          "sha1": "81ad7f31c31da6e4a80125c7acf341e2889297f7",
          "md5": "c2dd74e059cbf817572d9735bcba5d96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-1.0.1.jar",
          "url": "qqrobot-framework-1.0.1.jar",
          "size": 8174,
          "sha512": "fa681b79c7e8f4ac0580f0ecdaf596207ade0d24aeba281a0be37abfc155af5f5d6588fdb554fcd4a77e1ea991c7823655b989cd554deedefa6f05aa8e30db12",
          "sha256": "8e25b15bea558bf60e5e35ded51e0bbc8d18466ebf6fceb845a006eb6bf8187f",
          "sha1": "81ad7f31c31da6e4a80125c7acf341e2889297f7",
          "md5": "c2dd74e059cbf817572d9735bcba5d96"
        }
      ]
    }
  ]
}
