{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qqrobot-framework-1.0.1.jar",
          "url": "qqrobot-framework-1.0.1.jar",
          "size": 8174,
          "sha512": "a3b9ff06a32966d70a7948977317b25a75ff8b4929b480afe79037c741dc102d3ae2fcea3f64ec43593328f8dced640b206815e5a82f3c863d391abeb0510194",
          "sha256": "c3e847e88517a5772ae31418e8d0138c587199237c656557330f4561bafac0c2",
          "sha1": "1e72746a4a6b7f6bec2fd73bf57e5eacedc6d871",
          "md5": "1e6933ffd8b9164dd1ef9dc0907bca5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-1.0.1.jar",
          "url": "qqrobot-framework-1.0.1.jar",
          "size": 8174,
          "sha512": "a3b9ff06a32966d70a7948977317b25a75ff8b4929b480afe79037c741dc102d3ae2fcea3f64ec43593328f8dced640b206815e5a82f3c863d391abeb0510194",
          "sha256": "c3e847e88517a5772ae31418e8d0138c587199237c656557330f4561bafac0c2",
          "sha1": "1e72746a4a6b7f6bec2fd73bf57e5eacedc6d871",
          "md5": "1e6933ffd8b9164dd1ef9dc0907bca5e"
        }
      ]
    }
  ]
}
