{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.0.5-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.4-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.5-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.5-dev.jar",
          "size": 69430,
          "sha512": "f45c05b40f3753e2b921c6062662405548d352a1418743b4c42bcef1717a3e9aef818f9ec2fea52c7ed1fe2844ef7c930675b2263525fc99901ef1abb60eb176",
          "sha256": "028d0dd4f09f395c98ae708544dd731c9b736cff242d89d19c65fb352aac6fc5",
          "sha1": "05242f4a51c6a3d7dadf90a757fbb558d727f4c0",
          "md5": "d3a05579460c4d490150cdac4dddddfb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.2.5"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.4-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.5-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.5-dev.jar",
          "size": 69430,
          "sha512": "f45c05b40f3753e2b921c6062662405548d352a1418743b4c42bcef1717a3e9aef818f9ec2fea52c7ed1fe2844ef7c930675b2263525fc99901ef1abb60eb176",
          "sha256": "028d0dd4f09f395c98ae708544dd731c9b736cff242d89d19c65fb352aac6fc5",
          "sha1": "05242f4a51c6a3d7dadf90a757fbb558d727f4c0",
          "md5": "d3a05579460c4d490150cdac4dddddfb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.5-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.5-dev-sources.jar",
          "size": 19712,
          "sha512": "684e913d9438137a65097db167889a07707a6e1d010fb376d653b1e6c0b83ab1bfc00aeb24adc2e135009650e161589996e153372e8b8de5b17134d3b717d5dc",
          "sha256": "498d2ba6168a6d6bbc1f8aff6729e79adc57dcc88b50f3d01e00ad14829f1727",
          "sha1": "5d2d094f4cb8118e04b9cefe9f9ae8eba55a20d7",
          "md5": "2b5d005928a1ea4b575c4e55a63f40cf"
        },
        {
          "name": "honoka-spring-boot-starter-1.0.5-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.5-dev-sources.jar",
          "size": 19712,
          "sha512": "684e913d9438137a65097db167889a07707a6e1d010fb376d653b1e6c0b83ab1bfc00aeb24adc2e135009650e161589996e153372e8b8de5b17134d3b717d5dc",
          "sha256": "498d2ba6168a6d6bbc1f8aff6729e79adc57dcc88b50f3d01e00ad14829f1727",
          "sha1": "5d2d094f4cb8118e04b9cefe9f9ae8eba55a20d7",
          "md5": "2b5d005928a1ea4b575c4e55a63f40cf"
        }
      ]
    }
  ]
}
