{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.0.5-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.4-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.5-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.5-dev.jar",
          "size": 69498,
          "sha512": "8900fe5fc6ccf4c4338430bbfd9b9151d08151904cd9572eaf3968d9fb777556d29de4290d6594c4de1c4a7410c219cf928c408dda7623620fef8ee9d5c77143",
          "sha256": "031caf3d3674378ec62e1220c5b835b1e7e3c5a38e8c78ba00fbdbe35014a51f",
          "sha1": "9096d0aea1d7591a5ce2bd6372678abc3ae760ff",
          "md5": "401b0adbf0511ac21e49979c553cd552"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.4-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.5-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.5-dev.jar",
          "size": 69498,
          "sha512": "8900fe5fc6ccf4c4338430bbfd9b9151d08151904cd9572eaf3968d9fb777556d29de4290d6594c4de1c4a7410c219cf928c408dda7623620fef8ee9d5c77143",
          "sha256": "031caf3d3674378ec62e1220c5b835b1e7e3c5a38e8c78ba00fbdbe35014a51f",
          "sha1": "9096d0aea1d7591a5ce2bd6372678abc3ae760ff",
          "md5": "401b0adbf0511ac21e49979c553cd552"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.5-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.5-dev-sources.jar",
          "size": 19726,
          "sha512": "33a4a44b748e1f286018c5f69012c90e216388c7e9acb201de1d1488009e360675b6982493060e38c84d789677169a7e80effc0476303d706990d666de336dd9",
          "sha256": "2e45189c1cacc880d0b901bf39ad1982a2412fe67a35a38b66f1f4e07afd0787",
          "sha1": "0aa4c4cc008c95f13f74133bd941d9d14c218f29",
          "md5": "e6a3c35a46c871d50c43e8c0b0af8470"
        },
        {
          "name": "honoka-spring-boot-starter-1.0.5-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.5-dev-sources.jar",
          "size": 19726,
          "sha512": "33a4a44b748e1f286018c5f69012c90e216388c7e9acb201de1d1488009e360675b6982493060e38c84d789677169a7e80effc0476303d706990d666de336dd9",
          "sha256": "2e45189c1cacc880d0b901bf39ad1982a2412fe67a35a38b66f1f4e07afd0787",
          "sha1": "0aa4c4cc008c95f13f74133bd941d9d14c218f29",
          "md5": "e6a3c35a46c871d50c43e8c0b0af8470"
        }
      ]
    }
  ]
}
