{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.0.5-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.4-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.5-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.5-dev.jar",
          "size": 69498,
          "sha512": "224b6f22b35c646b8866afd8ae0a3a898a4c2243ba9e9ac9bcb7eaf9723aa2f25008fdc883a32d1286487833e00af7a48be0759f32342e1f30bb4a85f053b126",
          "sha256": "138622b75382b470077ac3185c59c9ed967278896fb5f6b1e9e95e254c8fde21",
          "sha1": "17528b29dcc37ec7bb5f38dd66b14f3bb97fbc0a",
          "md5": "a83500a416897aedf99d902951c9cddf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.4-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.5-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.5-dev.jar",
          "size": 69498,
          "sha512": "224b6f22b35c646b8866afd8ae0a3a898a4c2243ba9e9ac9bcb7eaf9723aa2f25008fdc883a32d1286487833e00af7a48be0759f32342e1f30bb4a85f053b126",
          "sha256": "138622b75382b470077ac3185c59c9ed967278896fb5f6b1e9e95e254c8fde21",
          "sha1": "17528b29dcc37ec7bb5f38dd66b14f3bb97fbc0a",
          "md5": "a83500a416897aedf99d902951c9cddf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.5-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.5-dev-sources.jar",
          "size": 19726,
          "sha512": "33a4a44b748e1f286018c5f69012c90e216388c7e9acb201de1d1488009e360675b6982493060e38c84d789677169a7e80effc0476303d706990d666de336dd9",
          "sha256": "2e45189c1cacc880d0b901bf39ad1982a2412fe67a35a38b66f1f4e07afd0787",
          "sha1": "0aa4c4cc008c95f13f74133bd941d9d14c218f29",
          "md5": "e6a3c35a46c871d50c43e8c0b0af8470"
        },
        {
          "name": "honoka-spring-boot-starter-1.0.5-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.5-dev-sources.jar",
          "size": 19726,
          "sha512": "33a4a44b748e1f286018c5f69012c90e216388c7e9acb201de1d1488009e360675b6982493060e38c84d789677169a7e80effc0476303d706990d666de336dd9",
          "sha256": "2e45189c1cacc880d0b901bf39ad1982a2412fe67a35a38b66f1f4e07afd0787",
          "sha1": "0aa4c4cc008c95f13f74133bd941d9d14c218f29",
          "md5": "e6a3c35a46c871d50c43e8c0b0af8470"
        }
      ]
    }
  ]
}
