{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "2.0.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.1.0-dev"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.2-dev.jar",
          "url": "qqrobot-spring-boot-starter-2.0.2-dev.jar",
          "size": 1232296,
          "sha512": "211b06e158d4a68045ef36e7497fcf8ac296d9a786652ba6dbc5fef33a23eb9642e3a74e3ce914be8ac2342898bdfbacdce75256e170d1d8caf21e0e6d74e87e",
          "sha256": "ad966db787a2240b9ee1c1bdfd9e6c8c3f3c6eca10c2aaee7c511c8b98c528c4",
          "sha1": "0c90a3c07fb470190402631e610c2a35f9a29be4",
          "md5": "76c562b9c146bffe76e91d8a9135dade"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.9"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "*"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.1.0-dev"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.2-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.2-dev.jar",
          "url": "qqrobot-spring-boot-starter-2.0.2-dev.jar",
          "size": 1232296,
          "sha512": "211b06e158d4a68045ef36e7497fcf8ac296d9a786652ba6dbc5fef33a23eb9642e3a74e3ce914be8ac2342898bdfbacdce75256e170d1d8caf21e0e6d74e87e",
          "sha256": "ad966db787a2240b9ee1c1bdfd9e6c8c3f3c6eca10c2aaee7c511c8b98c528c4",
          "sha1": "0c90a3c07fb470190402631e610c2a35f9a29be4",
          "md5": "76c562b9c146bffe76e91d8a9135dade"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.2-dev-sources.jar",
          "url": "qqrobot-spring-boot-starter-2.0.2-dev-sources.jar",
          "size": 1135443,
          "sha512": "2d3b226fef83371fb64271cd7dab0858534a249751f3adcceeea6bc1cb0906e36e3ad7bbe47b2cadfcb4b3db887fb2dbc718d2d61558e233a40e1da967482332",
          "sha256": "e07b5df35b85f5795ff43dbb42a0806a73a1ea14d91f00f4db4216db8afc10d4",
          "sha1": "8215184ad44ad7720c57ec37b58c1044f1d405f5",
          "md5": "db0932ee5058b06cb23777c9cfcdd004"
        }
      ]
    }
  ]
}
