{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "2.0.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.1.0-dev"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.2-dev.jar",
          "url": "qqrobot-spring-boot-starter-2.0.2-dev.jar",
          "size": 1232246,
          "sha512": "59b0e5714620f25601fd83749952b99bcef892711bfb029326c556abb0ec0822dc0127893662c891165386edd92947f1a90453a9d1f88d34aa3da0f8c4b4e28c",
          "sha256": "c2e971bb7f6d4af1e1dcbc0f29554bb8d1ef0da7b412b272ca2ada5ee9a9a22e",
          "sha1": "0174b326c72baf2d5bc70092b5fdafed6921d490",
          "md5": "a941a6e8507eec44d09bd4d4aef8df08"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.9"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "*"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.1.0-dev"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.2-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.2-dev.jar",
          "url": "qqrobot-spring-boot-starter-2.0.2-dev.jar",
          "size": 1232246,
          "sha512": "59b0e5714620f25601fd83749952b99bcef892711bfb029326c556abb0ec0822dc0127893662c891165386edd92947f1a90453a9d1f88d34aa3da0f8c4b4e28c",
          "sha256": "c2e971bb7f6d4af1e1dcbc0f29554bb8d1ef0da7b412b272ca2ada5ee9a9a22e",
          "sha1": "0174b326c72baf2d5bc70092b5fdafed6921d490",
          "md5": "a941a6e8507eec44d09bd4d4aef8df08"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.2-dev-sources.jar",
          "url": "qqrobot-spring-boot-starter-2.0.2-dev-sources.jar",
          "size": 1135434,
          "sha512": "66a9b026ba9c9c9d09fd6fc960916d97c0c9094df27477d59e605d531025107451154b5f5cb8d2d2d409d7ad5849ce80459bd47add56c07f2d8054e4bfdbe78b",
          "sha256": "56f96ee23b99b153c56086897955bb11369b4e3cc9508e3d9d393a2b54a11ceb",
          "sha1": "c773d366e20f13a3df49826fd17eea62e0b4d428",
          "md5": "841ee1af80463ee873b3a92c5fa212ab"
        }
      ]
    }
  ]
}
