{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "2.0.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.1.0-dev"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.2-dev.jar",
          "url": "qqrobot-spring-boot-starter-2.0.2-dev.jar",
          "size": 1232086,
          "sha512": "89b48288a2b7ee2bd258f9a1aee7900e2d456298a6627e03fd331e2140c78193c7c8570024251979b29cae7a87303177b7b3abecb5370dfd3e31b2443e40ac3d",
          "sha256": "7fefe52a7d994684809100ba834d60302bbb3928d74049dff92d2e165e1a74d2",
          "sha1": "a2839b0905ead0186325b51d297a3e3111e4c186",
          "md5": "5da5e1cf59d982bd135269a62fb686f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.9"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "*"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.1.0-dev"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.2-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.2-dev.jar",
          "url": "qqrobot-spring-boot-starter-2.0.2-dev.jar",
          "size": 1232086,
          "sha512": "89b48288a2b7ee2bd258f9a1aee7900e2d456298a6627e03fd331e2140c78193c7c8570024251979b29cae7a87303177b7b3abecb5370dfd3e31b2443e40ac3d",
          "sha256": "7fefe52a7d994684809100ba834d60302bbb3928d74049dff92d2e165e1a74d2",
          "sha1": "a2839b0905ead0186325b51d297a3e3111e4c186",
          "md5": "5da5e1cf59d982bd135269a62fb686f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.2-dev-sources.jar",
          "url": "qqrobot-spring-boot-starter-2.0.2-dev-sources.jar",
          "size": 1135119,
          "sha512": "dd514514e65c3b158f49836e86cb5a73d4096a10b265dc094d522afba82ac4188f77759c83f89eb4df9ffe4f07340e434edfbd767b48208a971229909c869136",
          "sha256": "93d36b6216d31a6b3c2f39fd81c6fa43894f2448f85be1d2ee84a3996a13288b",
          "sha1": "6727a47d4298a23187d1b928a7dd167e2c962d32",
          "md5": "6c0425f8f5a8d97a2a0c6c194ed9f0c8"
        }
      ]
    }
  ]
}
