{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "2.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.0-dev"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0-dev.jar",
          "url": "honoka-kotlin-utils-2.0.0-dev.jar",
          "size": 8519,
          "sha512": "43fad37c8f357097af0d2bd9b372d135b051eaff79bde2aa71c324a9171e137b559003e36f72cb401b6f9394e311b1595a7bffa75ebf2d093777b71936b2a542",
          "sha256": "c34f8d022b239a3c3b9548420518f69c0bd56266d410ec7a0bce7efa37bc479f",
          "sha1": "fc2132ab269247278a29d1a03a884cbe2c97a956",
          "md5": "cf5d4db81ff4a0327bd90ada3df7a00e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.0-dev"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0-dev.jar",
          "url": "honoka-kotlin-utils-2.0.0-dev.jar",
          "size": 8519,
          "sha512": "43fad37c8f357097af0d2bd9b372d135b051eaff79bde2aa71c324a9171e137b559003e36f72cb401b6f9394e311b1595a7bffa75ebf2d093777b71936b2a542",
          "sha256": "c34f8d022b239a3c3b9548420518f69c0bd56266d410ec7a0bce7efa37bc479f",
          "sha1": "fc2132ab269247278a29d1a03a884cbe2c97a956",
          "md5": "cf5d4db81ff4a0327bd90ada3df7a00e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0-dev-sources.jar",
          "url": "honoka-kotlin-utils-2.0.0-dev-sources.jar",
          "size": 3854,
          "sha512": "8a15d04e9115c3814e319227de73adc85aa0a655c471ffb6b6f057620ed0525ee33c780eacaa78ba2dad1806ba4df5cf9685ad09755a11c4a4cf6280997e30fb",
          "sha256": "f97de092067cc0662ba1305a5ae9f00de13fecbb46b365143b1fa8d71db6d74c",
          "sha1": "44feb8722bba6c01f991698270385211af425302",
          "md5": "a1063897728bd775212effee6d231654"
        }
      ]
    }
  ]
}
