{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "2.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.0-dev"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0-dev.jar",
          "url": "honoka-kotlin-utils-2.0.0-dev.jar",
          "size": 8519,
          "sha512": "fadc08734f3fb91634e23a8f12aa00083bba7a0784dd42c231c802d137cae6493124dafde89911c93ee65827df5ecff8c798bf26d1915ed532fa9e293b3ca0b0",
          "sha256": "15fc4f3b02b5ce084f70272d02b271365acd9c3b583383ecf174b6109fdcad31",
          "sha1": "58dc5400581006c2d658decfa51bd5c812315e40",
          "md5": "f2d2a83004dd63daac6b09e9bb1fc3d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.0-dev"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0-dev.jar",
          "url": "honoka-kotlin-utils-2.0.0-dev.jar",
          "size": 8519,
          "sha512": "fadc08734f3fb91634e23a8f12aa00083bba7a0784dd42c231c802d137cae6493124dafde89911c93ee65827df5ecff8c798bf26d1915ed532fa9e293b3ca0b0",
          "sha256": "15fc4f3b02b5ce084f70272d02b271365acd9c3b583383ecf174b6109fdcad31",
          "sha1": "58dc5400581006c2d658decfa51bd5c812315e40",
          "md5": "f2d2a83004dd63daac6b09e9bb1fc3d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0-dev-sources.jar",
          "url": "honoka-kotlin-utils-2.0.0-dev-sources.jar",
          "size": 3854,
          "sha512": "727f1dde237bdc3a307f01be5b72aeb894b0d69f24a7829e7d0fa57a48b0cd9fade75e44d767a0e08641c504b3c29f440c0fec92766e6f1ca51cefa531f86c77",
          "sha256": "b3b9a2d3b0471708b21842dd84b82ccfbcd47ee80b465344777e54aabbfd9859",
          "sha1": "ea773e2de1505fb8ec2b22982564833dbe2917ac",
          "md5": "6001d34a880482316035d56c2f65fd0b"
        }
      ]
    }
  ]
}
