{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "2.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.0-dev"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0-dev.jar",
          "url": "honoka-kotlin-utils-2.0.0-dev.jar",
          "size": 8519,
          "sha512": "3b0f8be85b396558519f0d6a8c3a2f417750b9606e58858beb86bf2291a4c5b8bda6f018a2943efdeaedb3cb18214f8b32869c7db6c8a22d64d87e2ae87e1406",
          "sha256": "6c1effd016a9ea6bf4e3789ac252fd5b1f99fbbf337ea5f4bffa362d68a72675",
          "sha1": "287e4e78c6dcbbff4db0f92479689b859a13f3a7",
          "md5": "ad7aea2c587274894d47c95d1ed03028"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.0-dev"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0-dev.jar",
          "url": "honoka-kotlin-utils-2.0.0-dev.jar",
          "size": 8519,
          "sha512": "3b0f8be85b396558519f0d6a8c3a2f417750b9606e58858beb86bf2291a4c5b8bda6f018a2943efdeaedb3cb18214f8b32869c7db6c8a22d64d87e2ae87e1406",
          "sha256": "6c1effd016a9ea6bf4e3789ac252fd5b1f99fbbf337ea5f4bffa362d68a72675",
          "sha1": "287e4e78c6dcbbff4db0f92479689b859a13f3a7",
          "md5": "ad7aea2c587274894d47c95d1ed03028"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0-dev-sources.jar",
          "url": "honoka-kotlin-utils-2.0.0-dev-sources.jar",
          "size": 3854,
          "sha512": "c0181e5f05f65c30ddc4a09d2a2f11d22908537bf924609ef6fc8393adf1429e5cd7c8f7975b3bf87d5a3cd0ee705ced2e701a5e8b518e4fd87a938f7c29ffc5",
          "sha256": "3002d221d0932e96238ce5ac34472784fc159515125395c3fba49d0674b1aa2e",
          "sha1": "1d8c92bb14536f77182257855c4b305ad7ef28aa",
          "md5": "c2cf8b36df296ea42c13ac4dff513b91"
        }
      ]
    }
  ]
}
