{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender",
    "module": "lavender-api",
    "version": "1.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lavender-api-1.0.0-dev.jar",
          "url": "lavender-api-1.0.0-dev.jar",
          "size": 60718,
          "sha512": "74574ae9d5140ea7ca2adbe644286ee19f5ee805f973b064f9c0c5580ffc5aa8e55e6871107578565870ad40130d7a97c8d1d417a3a4000bd9e2107f227ce18d",
          "sha256": "ae0097714094772fda9cf9c584319cfaf5096bbb5a00ebbf2d74fbf0637ecab1",
          "sha1": "9f08ab722849d7fc22516832b92d2687c6fcefac",
          "md5": "bf3a3f76943150b37d705d010d52bbb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lavender-api-1.0.0-dev.jar",
          "url": "lavender-api-1.0.0-dev.jar",
          "size": 60718,
          "sha512": "74574ae9d5140ea7ca2adbe644286ee19f5ee805f973b064f9c0c5580ffc5aa8e55e6871107578565870ad40130d7a97c8d1d417a3a4000bd9e2107f227ce18d",
          "sha256": "ae0097714094772fda9cf9c584319cfaf5096bbb5a00ebbf2d74fbf0637ecab1",
          "sha1": "9f08ab722849d7fc22516832b92d2687c6fcefac",
          "md5": "bf3a3f76943150b37d705d010d52bbb5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavender-api-1.0.0-dev-sources.jar",
          "url": "lavender-api-1.0.0-dev-sources.jar",
          "size": 7476,
          "sha512": "86c6d6d7930a9953729ebabdf5783908f2810f6a7ef629a94ac4f4b288ed222e382806097c0d0370730c9b4ee013128a741640bf518e0a41cc121550b6fd3af8",
          "sha256": "e0c8f3485129cbeb1deac5731069320225ee5c879e2be4c6b6ba166d7eeb3185",
          "sha1": "8a8b8ac8c3b90674b2bdec564d639ed098a1da2b",
          "md5": "123e8ae6c0ce138bb86e1a0620986f56"
        }
      ]
    }
  ]
}
