{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender",
    "module": "lavender-api",
    "version": "1.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lavender-api-1.0.0-dev.jar",
          "url": "lavender-api-1.0.0-dev.jar",
          "size": 43812,
          "sha512": "fcd956644eacc587f8ca310222444a0bf9ba34986f25610aec688872849705d20c6c51cb77b4b72edf802e17b7a1a551edf2a5e7bf271702f16e77d6eb329f9c",
          "sha256": "a277dc5d9a191d7ef9731a82308d3c23e8500668fd8429a9eb52923e1f0b6ae3",
          "sha1": "6ea21529c187c705326a918d69bacd6c93ea83af",
          "md5": "49f0560290d4ca86356e6c571216f694"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "lavender-api-1.0.0-dev.jar",
          "url": "lavender-api-1.0.0-dev.jar",
          "size": 43812,
          "sha512": "fcd956644eacc587f8ca310222444a0bf9ba34986f25610aec688872849705d20c6c51cb77b4b72edf802e17b7a1a551edf2a5e7bf271702f16e77d6eb329f9c",
          "sha256": "a277dc5d9a191d7ef9731a82308d3c23e8500668fd8429a9eb52923e1f0b6ae3",
          "sha1": "6ea21529c187c705326a918d69bacd6c93ea83af",
          "md5": "49f0560290d4ca86356e6c571216f694"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavender-api-1.0.0-dev-sources.jar",
          "url": "lavender-api-1.0.0-dev-sources.jar",
          "size": 6209,
          "sha512": "7e9f7b691442b299c081a6c94dc61fd973ab3f9f269b66b26927221caf61500982a6cee3f16c882f98bfd7ceac5fec1a4d399ac5089c9f0e81c2c470d27237b5",
          "sha256": "4380978cb8870f8a4c32d1c71d9493ee47e1e4086a243763d71f8d3b753abce0",
          "sha1": "6114ee1486f8710b2f9560f01852198875ba93e1",
          "md5": "9e09901bc04a8e123977c14218749843"
        }
      ]
    }
  ]
}
