{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender",
    "module": "lavender-api",
    "version": "1.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lavender-api-1.0.0-dev.jar",
          "url": "lavender-api-1.0.0-dev.jar",
          "size": 42304,
          "sha512": "04e464d71417bf5a52265d64c2e6c7a75248c533df08da227d72792030e623094cd34598bc5652786267ee77c291a44c073c8ba471d79a5c230f9acf86ab4ea1",
          "sha256": "278921b0b579298c344ce254f7911a691c291874b68ac69b7e91a4c269e31c8a",
          "sha1": "689c1c5494c20374847c90193dccbca2474f5ced",
          "md5": "89870e2dabe658a1b758f9d9c344eb1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lavender-api-1.0.0-dev.jar",
          "url": "lavender-api-1.0.0-dev.jar",
          "size": 42304,
          "sha512": "04e464d71417bf5a52265d64c2e6c7a75248c533df08da227d72792030e623094cd34598bc5652786267ee77c291a44c073c8ba471d79a5c230f9acf86ab4ea1",
          "sha256": "278921b0b579298c344ce254f7911a691c291874b68ac69b7e91a4c269e31c8a",
          "sha1": "689c1c5494c20374847c90193dccbca2474f5ced",
          "md5": "89870e2dabe658a1b758f9d9c344eb1e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavender-api-1.0.0-dev-sources.jar",
          "url": "lavender-api-1.0.0-dev-sources.jar",
          "size": 5984,
          "sha512": "e6bb5a16a99a87b3dd439bf9da6ea0df06096dc79653e70a06db352cb8d6a57ef41e51e1ad48c75f2ec082dacb3f892f0dedb0d477ff8a27fae9efa71432cbff",
          "sha256": "d1cfc74c1c81db745a8043bc0cd0022a570006b6e959c55ca1a47d5b7e8711ce",
          "sha1": "ad52ab7405bba267164d9e4f16371cd6a0d291e7",
          "md5": "3088f32a5444fdc38d62f0226a7ab60a"
        }
      ]
    }
  ]
}
