{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.10.jar",
          "url": "honoka-utils-1.0.10.jar",
          "size": 70540,
          "sha512": "60517d232f735d9dbd24bb93e10f0bf4ab350e452d04344157337e4e3f2c885ce22493d67b4109bf67b382336be3d1217ef961723a47fdd8bed6e8bb0566fbec",
          "sha256": "88ed2c8bd6de60672b0c3c76e5eb0f077cbe4eea24f4371971ea53a3bf7c784d",
          "sha1": "09cb82207b54e76d3f7eb780c833e9cd5560b9b7",
          "md5": "2a38189eb50b58631a98599f5c4068f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.10.jar",
          "url": "honoka-utils-1.0.10.jar",
          "size": 70540,
          "sha512": "60517d232f735d9dbd24bb93e10f0bf4ab350e452d04344157337e4e3f2c885ce22493d67b4109bf67b382336be3d1217ef961723a47fdd8bed6e8bb0566fbec",
          "sha256": "88ed2c8bd6de60672b0c3c76e5eb0f077cbe4eea24f4371971ea53a3bf7c784d",
          "sha1": "09cb82207b54e76d3f7eb780c833e9cd5560b9b7",
          "md5": "2a38189eb50b58631a98599f5c4068f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.0.10-sources.jar",
          "url": "honoka-utils-1.0.10-sources.jar",
          "size": 37750,
          "sha512": "f5027b9bae0eacbfa29b23d2ee0c1ec8ad5d4abf84cb35f6f95625bf2f0a44fa20654a507f921cc6fb8a35958bf0b35fd5f5397b7070749536fc368574dc8499",
          "sha256": "cd11ccb3f06592c71ea21f09109a4b1fc0f3e0c681e8dc082cd8527a09d7ea80",
          "sha1": "2c8be94d3b8cf805637d319624d73d4f9995be55",
          "md5": "01ad02ed0939a43d2b4f2ede39a5b7d3"
        }
      ]
    }
  ]
}
