{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.10.jar",
          "url": "honoka-utils-1.0.10.jar",
          "size": 70540,
          "sha512": "c3a67353c10f64afa2013b24684cc71d4f0d1e6fb9a01c6e308e4429a2702294f8b9b97b7ebe397dfc90d57111eb456bc5456511a4724f9b98077900555262b8",
          "sha256": "94b1cc1a0a1dd915a12ca1930727b116056e007162785a747eead9f5196454ec",
          "sha1": "1ac5265367c7f603785dd709ac1e7df9770f6044",
          "md5": "debf8877d3835b0e65cf9c00e02a33c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.10.jar",
          "url": "honoka-utils-1.0.10.jar",
          "size": 70540,
          "sha512": "c3a67353c10f64afa2013b24684cc71d4f0d1e6fb9a01c6e308e4429a2702294f8b9b97b7ebe397dfc90d57111eb456bc5456511a4724f9b98077900555262b8",
          "sha256": "94b1cc1a0a1dd915a12ca1930727b116056e007162785a747eead9f5196454ec",
          "sha1": "1ac5265367c7f603785dd709ac1e7df9770f6044",
          "md5": "debf8877d3835b0e65cf9c00e02a33c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.0.10-sources.jar",
          "url": "honoka-utils-1.0.10-sources.jar",
          "size": 37750,
          "sha512": "4a1fd04aa0344937381449cf917c1389154200ce6e76a9fe7d1991888a8b62ff8fd1139379698aef160ccfdc0a912b8403aa7e81f255010ca413f8e3dbaf8705",
          "sha256": "a0b02645b9cdd03dfcd7ce09ede3e51fcf6986faa23221be510170783cb152a8",
          "sha1": "3ae8e21d7345d47d895460e513afd24c4d6025d4",
          "md5": "1ecd9dfed84077860c1d56ec57a841ca"
        }
      ]
    }
  ]
}
