{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.10.jar",
          "url": "honoka-utils-1.0.10.jar",
          "size": 70540,
          "sha512": "6552a0fe272948c03b4baf366ca33444e0252aa69ccbc6166b413e7c5b7bf9f35079ffe2e70a16672ed4472254e3724dfb36c7f49fe792fb426656fb58f98eed",
          "sha256": "bce5dca0068503cd20aad7b259c14e1ef5ca4e05dae8f6bb931e44cef4e8f643",
          "sha1": "a6987a76d57418cd8b7e4c96859ee7606f4c815a",
          "md5": "b9e0685ed6ec75ca9ce614931b4de7ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.10.jar",
          "url": "honoka-utils-1.0.10.jar",
          "size": 70540,
          "sha512": "6552a0fe272948c03b4baf366ca33444e0252aa69ccbc6166b413e7c5b7bf9f35079ffe2e70a16672ed4472254e3724dfb36c7f49fe792fb426656fb58f98eed",
          "sha256": "bce5dca0068503cd20aad7b259c14e1ef5ca4e05dae8f6bb931e44cef4e8f643",
          "sha1": "a6987a76d57418cd8b7e4c96859ee7606f4c815a",
          "md5": "b9e0685ed6ec75ca9ce614931b4de7ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.0.10-sources.jar",
          "url": "honoka-utils-1.0.10-sources.jar",
          "size": 37750,
          "sha512": "3307f274be0197b8ed1609a48afc187c0d95f251f098515479fc1b391f34a9857731b9fc4402453353386d36fa715c54b39ca57221423e5b577f21a227aaa97d",
          "sha256": "ce3cb352905b65378dfa09d1f890d69a66bbca889834e94ab97e08db7b930575",
          "sha1": "e6784ea3449216ddd31ec8d15422f162bf0cae23",
          "md5": "5ddedc13ba179579c82a78e5ad2a8ae6"
        }
      ]
    }
  ]
}
