{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-basic-plugin",
    "version": "1.1.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.1.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.1.0-dev.jar",
          "url": "honoka-basic-plugin-1.1.0-dev.jar",
          "size": 37082,
          "sha512": "6d4504c8add6e5ba42c615ef192a6e4369a7ce492a3f6cded0fab72890bbfecb2575cf2cd6b8d0b1f88e8fbe48ac8f0c9f3ee40f3a7fc4eac83e9d7544ae01df",
          "sha256": "a5611c2523a120d41f0f4738a15b629b52944dbe77fe76550168fb87c48e0f2d",
          "sha1": "1a833c488f108c6ab96c70c06bc93833671de5bb",
          "md5": "9e72d8e35fbb87d0e5e6ba8449f16f28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-allopen",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.1.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.1.0-dev.jar",
          "url": "honoka-basic-plugin-1.1.0-dev.jar",
          "size": 37082,
          "sha512": "6d4504c8add6e5ba42c615ef192a6e4369a7ce492a3f6cded0fab72890bbfecb2575cf2cd6b8d0b1f88e8fbe48ac8f0c9f3ee40f3a7fc4eac83e9d7544ae01df",
          "sha256": "a5611c2523a120d41f0f4738a15b629b52944dbe77fe76550168fb87c48e0f2d",
          "sha1": "1a833c488f108c6ab96c70c06bc93833671de5bb",
          "md5": "9e72d8e35fbb87d0e5e6ba8449f16f28"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.1.0-dev-sources.jar",
          "url": "honoka-basic-plugin-1.1.0-dev-sources.jar",
          "size": 6704,
          "sha512": "28a89fdd54015a7c13b755106e42461e8315be21d7b299ce12422f85588176f88124158009cee058e5d5b54e6601677b98f7bbbc34d87e056227ab7eb67b4a41",
          "sha256": "703ba495f5d57bdac539c297c6d8a5801e6508b812d2bfef4652de39d5537086",
          "sha1": "500018da78756247d9ae48b585570c1163bf1d61",
          "md5": "4f1864fb6528ca34069c0683c371be9c"
        }
      ]
    }
  ]
}
