{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-basic-plugin",
    "version": "1.1.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.1.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.1.0-dev.jar",
          "url": "honoka-basic-plugin-1.1.0-dev.jar",
          "size": 35861,
          "sha512": "8dcf2e0cced22d4d60ef2ec7d1c3a8ea06c7389faa036dba1f5cca8a5660cfae9d2c0b2d91250f2b1807d849663684fa479b3836d02aefd11d61a6864b968edf",
          "sha256": "4a8f863cd44b4ca4fad6222de902bec2d51eb6b7699f49b53abe16f3326cad5d",
          "sha1": "4d5d8b3bb2d91715e94b51d5549c8948ea7d47a3",
          "md5": "423876365effcad8cdce970730f081c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.1.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.1.0-dev.jar",
          "url": "honoka-basic-plugin-1.1.0-dev.jar",
          "size": 35861,
          "sha512": "8dcf2e0cced22d4d60ef2ec7d1c3a8ea06c7389faa036dba1f5cca8a5660cfae9d2c0b2d91250f2b1807d849663684fa479b3836d02aefd11d61a6864b968edf",
          "sha256": "4a8f863cd44b4ca4fad6222de902bec2d51eb6b7699f49b53abe16f3326cad5d",
          "sha1": "4d5d8b3bb2d91715e94b51d5549c8948ea7d47a3",
          "md5": "423876365effcad8cdce970730f081c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.1.0-dev-sources.jar",
          "url": "honoka-basic-plugin-1.1.0-dev-sources.jar",
          "size": 6606,
          "sha512": "8666671760bfc7ec751f9535765d4f587f784747f6c1ed756fdc47f102ac05aa06edfa187d7ac1f3f601e7ceec7e52b9fc0371536bd4002d857f60ff404a5326",
          "sha256": "9930712355f2329d5ca3ec4b45dcfa785b18d6702740a798634a8b8d8e9d81eb",
          "sha1": "7b6b255d04a06cf4679f7c2696a25d01cf0f2070",
          "md5": "496d7be8a4416635b40150ba78bf9443"
        }
      ]
    }
  ]
}
