{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-basic-plugin",
    "version": "1.1.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.1.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.1.0-dev.jar",
          "url": "honoka-basic-plugin-1.1.0-dev.jar",
          "size": 34156,
          "sha512": "5263e48347f082d6f6afe0258b5f482e220a565bf07c37c6f162875d106069eaf6266b64ab1b9e688c12d3f7ed7d17f2616220597d9812e746515d45de82fe28",
          "sha256": "3dc3066309dc05c345c211bb7a71a7505c1f98e3693b8d680e5b98ebcf72f82c",
          "sha1": "b8ae33aed4ba44f19556c57c4c3d5252b8655a1e",
          "md5": "9c2e0e38a2742cd3218f445efe7a338b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.1.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.1.0-dev.jar",
          "url": "honoka-basic-plugin-1.1.0-dev.jar",
          "size": 34156,
          "sha512": "5263e48347f082d6f6afe0258b5f482e220a565bf07c37c6f162875d106069eaf6266b64ab1b9e688c12d3f7ed7d17f2616220597d9812e746515d45de82fe28",
          "sha256": "3dc3066309dc05c345c211bb7a71a7505c1f98e3693b8d680e5b98ebcf72f82c",
          "sha1": "b8ae33aed4ba44f19556c57c4c3d5252b8655a1e",
          "md5": "9c2e0e38a2742cd3218f445efe7a338b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.1.0-dev-sources.jar",
          "url": "honoka-basic-plugin-1.1.0-dev-sources.jar",
          "size": 6006,
          "sha512": "e10be8d680901b6510a49eefe7becbe5c9056009e51722d15bc162c88a9d0cc613709da5e3a04b88d7ad69056b9cc77caf31d3d5e4b1ea78772e09cb7b8b31aa",
          "sha256": "257c7d9ac2510e9b35eba4c47188bf36718369f889eeb3a32fbbfc03214d86dc",
          "sha1": "4e2ecac36bdfcb88aecd109d19d5e24c77d9e14d",
          "md5": "b56d801f641a2017a412471e83ec96d6"
        }
      ]
    }
  ]
}
