{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.0.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.2-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.2-dev.jar",
          "size": 64256,
          "sha512": "ae329a190dbe4799dc011c73543e8990e17d0ced3376f2fa3b7b1d35bcdb723e35649a8faa92a15c36d7b5a10d9d3b873e7563869cfffb439d00a747ca8a6cbf",
          "sha256": "4a109efe0f9e9384216b4479da7e9d38c6661773617f1ba43db32ba6d6a9f8e3",
          "sha1": "51f68dfcfd590e9396c3623ba1894f70383af244",
          "md5": "183e32c541618386f1439c7bac0e2edc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.2-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.2-dev.jar",
          "size": 64256,
          "sha512": "ae329a190dbe4799dc011c73543e8990e17d0ced3376f2fa3b7b1d35bcdb723e35649a8faa92a15c36d7b5a10d9d3b873e7563869cfffb439d00a747ca8a6cbf",
          "sha256": "4a109efe0f9e9384216b4479da7e9d38c6661773617f1ba43db32ba6d6a9f8e3",
          "sha1": "51f68dfcfd590e9396c3623ba1894f70383af244",
          "md5": "183e32c541618386f1439c7bac0e2edc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.2-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.2-dev-sources.jar",
          "size": 19381,
          "sha512": "10b1b712ed614edeb2ecb8e2a02920139242293adde0d75cd1a39229d96d6408da1e24b0b7e28682106daa7a6ae0a6136bafb67cf144222a04785641dac53db9",
          "sha256": "ed25815d4b9657a33a9d7d5fede056a761815806e9a4dfdee6d9e19ccc4cc7e2",
          "sha1": "ee6389a9217b033a13c09d3efea7f4d59b557ac6",
          "md5": "dfa490837516444c02540f74fb4988cd"
        }
      ]
    }
  ]
}
