{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.0.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.2-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.2-dev.jar",
          "size": 61020,
          "sha512": "8bf3891e45f1439a5af2129b3180ab0f1360aaa9dba585f8c061b2bc375fd723c4803c10d21a4325143e29e80dded9309b8b838793c57123248521bec7a172d5",
          "sha256": "28dc5c66729c0ea9e39d97f56daa88590ee90326c6583de7390ed99b88d1fc76",
          "sha1": "8e8f164a0f41d62c8837f39ba46f166d33afe39c",
          "md5": "fd1ff5ccdc0298050efa0ce311b3fb20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.2-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.2-dev.jar",
          "size": 61020,
          "sha512": "8bf3891e45f1439a5af2129b3180ab0f1360aaa9dba585f8c061b2bc375fd723c4803c10d21a4325143e29e80dded9309b8b838793c57123248521bec7a172d5",
          "sha256": "28dc5c66729c0ea9e39d97f56daa88590ee90326c6583de7390ed99b88d1fc76",
          "sha1": "8e8f164a0f41d62c8837f39ba46f166d33afe39c",
          "md5": "fd1ff5ccdc0298050efa0ce311b3fb20"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.2-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.2-dev-sources.jar",
          "size": 18222,
          "sha512": "f68b6539043f51b49cac79f0b78679b4bcd3911d8d4651529805435d588224657371e33a60c8450f58bea19832ce20eaaa66964a3553f3405e10827c00923348",
          "sha256": "66158d81c53d56103a880d52f007eeef9314db22746e46d56a8da24fcb454f2f",
          "sha1": "f2e19d63b3bbda0cc0ed96d58eaa525cdc4db7f7",
          "md5": "ed4b649bee3746202ed065c0b1eb2c16"
        }
      ]
    }
  ]
}
