{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.0.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.2-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.2-dev.jar",
          "size": 64256,
          "sha512": "e5fa1f53f6c9c77b0f1e57216ce2ef52b7673ad8c6085ede8177c2fcbef15eb018ce9ae8d6556c027494b75440269dbdbb843c0eac5b5c85c861012c4be1aa13",
          "sha256": "c5a75b4c93e2bd0e1ac95d083537ec4629af9ee34ba1c66fc76d672d778444db",
          "sha1": "854b3e0afdfbe51983915380f56bf01e6b565508",
          "md5": "b132640c12f9905996e3afbf1267d6c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.2-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.2-dev.jar",
          "size": 64256,
          "sha512": "e5fa1f53f6c9c77b0f1e57216ce2ef52b7673ad8c6085ede8177c2fcbef15eb018ce9ae8d6556c027494b75440269dbdbb843c0eac5b5c85c861012c4be1aa13",
          "sha256": "c5a75b4c93e2bd0e1ac95d083537ec4629af9ee34ba1c66fc76d672d778444db",
          "sha1": "854b3e0afdfbe51983915380f56bf01e6b565508",
          "md5": "b132640c12f9905996e3afbf1267d6c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.2-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.2-dev-sources.jar",
          "size": 19381,
          "sha512": "3cd8f0ccb33369662e8c3bc3402f40fbcfac78f519d0b4ac9d4c623ea6793d9baa3f3d62f15dd9299a42eddf1a2f3401e37b95b52de43bc260e260cd0a3b719a",
          "sha256": "645fd7037164ab532497c06f3ddfca551be26a7cbbf9ab0b07c4141d391a0ac1",
          "sha1": "8e10e370d153ec9e2f8aa188dadae7dead612b2a",
          "md5": "57f245f3d697df1ea344980ce8b1cf04"
        }
      ]
    }
  ]
}
