{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "2.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.0-dev.jar",
          "url": "qqrobot-framework-api-2.0.0-dev.jar",
          "size": 8883,
          "sha512": "28ca971add32eaabfa4ccaa6bf5303a68f1451094e54adf84b2da592bd613f7345cbd13b8696f3f2e87e0de2bafd4e84400a5ea159167ae6fc8b8460b7a23455",
          "sha256": "e27cedf1d6fb27e9d4857f2136efdfda15bc0fad51fdb9783ded02bb14b85821",
          "sha1": "7fa227ee20b4715de87eee3a6f2fb9206e7f52a1",
          "md5": "cb7bc3ffdc66cb71ed5aba49d104edb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.0-dev.jar",
          "url": "qqrobot-framework-api-2.0.0-dev.jar",
          "size": 8883,
          "sha512": "28ca971add32eaabfa4ccaa6bf5303a68f1451094e54adf84b2da592bd613f7345cbd13b8696f3f2e87e0de2bafd4e84400a5ea159167ae6fc8b8460b7a23455",
          "sha256": "e27cedf1d6fb27e9d4857f2136efdfda15bc0fad51fdb9783ded02bb14b85821",
          "sha1": "7fa227ee20b4715de87eee3a6f2fb9206e7f52a1",
          "md5": "cb7bc3ffdc66cb71ed5aba49d104edb6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.0-dev-sources.jar",
          "url": "qqrobot-framework-api-2.0.0-dev-sources.jar",
          "size": 4934,
          "sha512": "133437b41b6b278084ae4de4a2f7add1cb84256d657a4003306a72f9661bbe719cfc0b6307da9827e4a7326a8944b46e7422adff56cb8954882c63656bc6799f",
          "sha256": "27882effb8dcfb81d7e925b9c8417ef3447030486d40590a247860089b11de12",
          "sha1": "579a95248df1c7162b6b8430bea0b60ebe789dda",
          "md5": "6c4528ec4bb6389ab75dff6781417d21"
        }
      ]
    }
  ]
}
