{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "2.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.0-dev.jar",
          "url": "qqrobot-framework-api-2.0.0-dev.jar",
          "size": 8883,
          "sha512": "82971e91be2175fe7282cc9e6c2c8b6a24304b0c6d717846613e1b346b690aa6a96a641227bcc02476988a83245a8995104b25a83bf14d169d2ffbba20a3bf01",
          "sha256": "c351916593b3f63c2dbc5f4e58ce831244734280fc23444a31df837e6a2aa2fe",
          "sha1": "c30079e8d08b1ecdb528a34faa6d67e48ba1f141",
          "md5": "9f6c7d8f46d5b8a1e069828d0d7954ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.0-dev.jar",
          "url": "qqrobot-framework-api-2.0.0-dev.jar",
          "size": 8883,
          "sha512": "82971e91be2175fe7282cc9e6c2c8b6a24304b0c6d717846613e1b346b690aa6a96a641227bcc02476988a83245a8995104b25a83bf14d169d2ffbba20a3bf01",
          "sha256": "c351916593b3f63c2dbc5f4e58ce831244734280fc23444a31df837e6a2aa2fe",
          "sha1": "c30079e8d08b1ecdb528a34faa6d67e48ba1f141",
          "md5": "9f6c7d8f46d5b8a1e069828d0d7954ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.0-dev-sources.jar",
          "url": "qqrobot-framework-api-2.0.0-dev-sources.jar",
          "size": 4934,
          "sha512": "8cc67e5e6f0c00214168ab61c253a1f53cdc17cb99e7cde3c22843da15059d84e532993441f3c7b4b083f3405a29bc6afdbc83f41c12d425636e2082b68c30e8",
          "sha256": "a21f299b0555ccab2b7c1bb4ea86f166723d58fe77c6cf85d8a4eea919aa3584",
          "sha1": "ec5ba17ea641ca0038db1842235fb986c4e77a31",
          "md5": "f7b9c08b2efd2129e53b344ffd576d82"
        }
      ]
    }
  ]
}
