{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-basic-plugin",
    "version": "1.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.1-dev.jar",
          "url": "honoka-basic-plugin-1.0.1-dev.jar",
          "size": 31881,
          "sha512": "845a8d63b5c01e259a0d6e953e5328c82db686b9ddaec25a0b5b0bec92f011d7652d91453ef905c95e53f4ec800d79a33e4cfa12762c564a6c50c5095db0198a",
          "sha256": "0571052c77681f04bcd627d43bca738aa7f8a4ca328ca2577e20877c3af37beb",
          "sha1": "5235fdecd66c0567bf1e02d69dc68e097b6b3da7",
          "md5": "4d8710e6538e35ff2c373685865bbbb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.1-dev.jar",
          "url": "honoka-basic-plugin-1.0.1-dev.jar",
          "size": 31881,
          "sha512": "845a8d63b5c01e259a0d6e953e5328c82db686b9ddaec25a0b5b0bec92f011d7652d91453ef905c95e53f4ec800d79a33e4cfa12762c564a6c50c5095db0198a",
          "sha256": "0571052c77681f04bcd627d43bca738aa7f8a4ca328ca2577e20877c3af37beb",
          "sha1": "5235fdecd66c0567bf1e02d69dc68e097b6b3da7",
          "md5": "4d8710e6538e35ff2c373685865bbbb2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.1-dev-sources.jar",
          "url": "honoka-basic-plugin-1.0.1-dev-sources.jar",
          "size": 3493,
          "sha512": "1afd4bdac5968fefe8ec19c2d86dcca8b046632fe028cc0b78c8b268daf2118b6c3fd539ca6934739f673567958609a3fc613462b0bc4918371f1a5f1d36afc6",
          "sha256": "a7498d4af4acc34b8a10c7c64b921699a4391a86d017c776fc000e9fafe4fe2e",
          "sha1": "3f7fcbd7366681a30403b21a115fc9e7cd37bd0c",
          "md5": "b4d13f764e84a71453895e2c0853bf81"
        }
      ]
    }
  ]
}
