{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-basic-plugin",
    "version": "1.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.1-dev.jar",
          "url": "honoka-basic-plugin-1.0.1-dev.jar",
          "size": 31979,
          "sha512": "e4c81f6705f282c2c46d435ce5e4f6752442737f644f866eb517febf4e5b4bbfe1d4c6034cc434bed1ba0b086e3e9f1c3ccd4a472903b8c41fb51e78329c72c2",
          "sha256": "6620a42fb0c8f6ad378f8ab6a468631dd34fd89c5b798b7c4a39d9ca61da419b",
          "sha1": "db7fbfe7e2950775923dace5609c42e816e57fa4",
          "md5": "945a73bda0d2853140a7e865fecbc6a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.1-dev.jar",
          "url": "honoka-basic-plugin-1.0.1-dev.jar",
          "size": 31979,
          "sha512": "e4c81f6705f282c2c46d435ce5e4f6752442737f644f866eb517febf4e5b4bbfe1d4c6034cc434bed1ba0b086e3e9f1c3ccd4a472903b8c41fb51e78329c72c2",
          "sha256": "6620a42fb0c8f6ad378f8ab6a468631dd34fd89c5b798b7c4a39d9ca61da419b",
          "sha1": "db7fbfe7e2950775923dace5609c42e816e57fa4",
          "md5": "945a73bda0d2853140a7e865fecbc6a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.1-dev-sources.jar",
          "url": "honoka-basic-plugin-1.0.1-dev-sources.jar",
          "size": 3507,
          "sha512": "91899c09d4dfabaf8f6be83f0ff2a3bd219ecd7a333e406c381e36d34893f8297128363468d28e842b840a78b35f10522c21b766b2df50d5b1a037a94cd45cce",
          "sha256": "b6d2c6e2560338a5528a2b9603ea868607b4cf5e5caa266f4bf9e3066ed4cdf1",
          "sha1": "9c7604cd759f7daa301c327e6f5e33f3cb0ca596",
          "md5": "1048703aaa8e43bdf08eb1a587bdaef4"
        }
      ]
    }
  ]
}
