{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-basic-plugin",
    "version": "1.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.1-dev.jar",
          "url": "honoka-basic-plugin-1.0.1-dev.jar",
          "size": 25970,
          "sha512": "7a5f3913713180a829529d87abaed316846300cbdb22198edc6fcf2cea5cef5e82d742fac434e8f6695d9d53fc64a64c1af7eb7d1a4da59158431f712267279c",
          "sha256": "aa752142f5f369a9f1c9b7145c2295f23dd31f1dceb17d7ac1e856a07b1139f9",
          "sha1": "87c4123b7feabf763010be9f0f18c0fc96e3545e",
          "md5": "609704b9181fca90e2e7a683da1b206a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.1-dev.jar",
          "url": "honoka-basic-plugin-1.0.1-dev.jar",
          "size": 25970,
          "sha512": "7a5f3913713180a829529d87abaed316846300cbdb22198edc6fcf2cea5cef5e82d742fac434e8f6695d9d53fc64a64c1af7eb7d1a4da59158431f712267279c",
          "sha256": "aa752142f5f369a9f1c9b7145c2295f23dd31f1dceb17d7ac1e856a07b1139f9",
          "sha1": "87c4123b7feabf763010be9f0f18c0fc96e3545e",
          "md5": "609704b9181fca90e2e7a683da1b206a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.1-dev-sources.jar",
          "url": "honoka-basic-plugin-1.0.1-dev-sources.jar",
          "size": 4005,
          "sha512": "01ccc9fac4f6493be9236c02c4c0e05e450f3f61cccc4d10eebe4c320bb4ad265482ed4cfe3c4b743ba51f93229dce23802b2f5357e5575d0e193dde71c1abdb",
          "sha256": "fac6fa3639a9a93548d90b08fec902d5844c3317feaec6dded222bcdc7f75593",
          "sha1": "98c558d752d9148211858538f61bf09e4b626f9a",
          "md5": "4b37392735b0e5bc81ef9bbd012c7898"
        }
      ]
    }
  ]
}
