{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "2.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.0-dev.jar",
          "url": "qqrobot-spring-boot-starter-2.0.0-dev.jar",
          "size": 1186935,
          "sha512": "4eefe7e83bf487e3be81747c2af22ffad27cbc1c12d657bff73736739718284b35d435947edbc3bdc715b619fbc2b0f0c3bc837d28585aa22c3c2da343054168",
          "sha256": "fe28e9e150abf0f6b0772ce851988fb6af4e5b66ea53b99d510b5143e89c7cc9",
          "sha1": "7cf87922f45d443ba5def67e7914a6df1e8a3bab",
          "md5": "aa596c8fa79a9230370a9d8d67abdddb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "net.mamoe",
          "module": "mirai-core-jvm",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "net.mamoe",
          "module": "mirai-console-compiler-annotations-jvm",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.0-dev.jar",
          "url": "qqrobot-spring-boot-starter-2.0.0-dev.jar",
          "size": 1186935,
          "sha512": "4eefe7e83bf487e3be81747c2af22ffad27cbc1c12d657bff73736739718284b35d435947edbc3bdc715b619fbc2b0f0c3bc837d28585aa22c3c2da343054168",
          "sha256": "fe28e9e150abf0f6b0772ce851988fb6af4e5b66ea53b99d510b5143e89c7cc9",
          "sha1": "7cf87922f45d443ba5def67e7914a6df1e8a3bab",
          "md5": "aa596c8fa79a9230370a9d8d67abdddb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.0-dev-sources.jar",
          "url": "qqrobot-spring-boot-starter-2.0.0-dev-sources.jar",
          "size": 1111287,
          "sha512": "123927926d2452d13985208043f2846e4a070e644bdef1473804c16fd398d21229fcaf1de146d1280d07184df589ace114e5fc20454f4baae28ee8477b33e3f2",
          "sha256": "eb8c89eaf814b101c345de68a76db31c447028fc6c754dffd9ed6c0cc987b4d8",
          "sha1": "b6df5bb7f1bab34215890e465f382498072376b0",
          "md5": "c2b4b310bbc2d5830738e890ee77871a"
        }
      ]
    }
  ]
}
