{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "2.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.0-dev.jar",
          "url": "qqrobot-spring-boot-starter-2.0.0-dev.jar",
          "size": 1186947,
          "sha512": "98b2f7c196d05a2b08df897a25c99872211ec9848c85e7c768bd3ba1e526c8356a43bc4351ca5b86ee96e18d3dd16f242635551f4068fb643f055e79be77028d",
          "sha256": "bc3253416281122c7f7b841d78becf76600a115a4f7dcc59427804935a91787a",
          "sha1": "cf0006a7e9931566d736392aab10dcf3a67b5c93",
          "md5": "db05b6fd2d6b5f6bfd2c490872062190"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "net.mamoe",
          "module": "mirai-core-jvm",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "net.mamoe",
          "module": "mirai-console-compiler-annotations-jvm",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.0-dev.jar",
          "url": "qqrobot-spring-boot-starter-2.0.0-dev.jar",
          "size": 1186947,
          "sha512": "98b2f7c196d05a2b08df897a25c99872211ec9848c85e7c768bd3ba1e526c8356a43bc4351ca5b86ee96e18d3dd16f242635551f4068fb643f055e79be77028d",
          "sha256": "bc3253416281122c7f7b841d78becf76600a115a4f7dcc59427804935a91787a",
          "sha1": "cf0006a7e9931566d736392aab10dcf3a67b5c93",
          "md5": "db05b6fd2d6b5f6bfd2c490872062190"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.0-dev-sources.jar",
          "url": "qqrobot-spring-boot-starter-2.0.0-dev-sources.jar",
          "size": 1111295,
          "sha512": "116d21c9d55cb2385c503b23ce7a6a9cac1d6fbbc34f1a7e3cc4eb7b2d3abd202583386ce881f5bdd693f999315b1b507da14c579bb4df9eb67465bf6b6c6a9f",
          "sha256": "a46328628c26578ccbce6538f6f7a0518e56a34aaa4b8530082749ce374cd691",
          "sha1": "d58712848d037325fba35d4add15f8724a2e4ed0",
          "md5": "b2eecea62f42fe01fb1daae252b47bd5"
        }
      ]
    }
  ]
}
