{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.1.jar",
          "url": "qqrobot-framework-api-2.0.1.jar",
          "size": 11669,
          "sha512": "6c38eab5b046557d83f7ee47093ed757a0530497ff30d201a6f1915341ae597265e7736601375b52237ddfca377f013023d091cb29166401284e005730465b89",
          "sha256": "a52b636b3fe173e9d621f2a547686500a6d6e086f830f4fc603a86343a1a963a",
          "sha1": "09d934f5c018e6001288c57521acc1c1a8afc265",
          "md5": "0a6d415f867abb9efc796b50575c66de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.1.jar",
          "url": "qqrobot-framework-api-2.0.1.jar",
          "size": 11669,
          "sha512": "6c38eab5b046557d83f7ee47093ed757a0530497ff30d201a6f1915341ae597265e7736601375b52237ddfca377f013023d091cb29166401284e005730465b89",
          "sha256": "a52b636b3fe173e9d621f2a547686500a6d6e086f830f4fc603a86343a1a963a",
          "sha1": "09d934f5c018e6001288c57521acc1c1a8afc265",
          "md5": "0a6d415f867abb9efc796b50575c66de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.1-sources.jar",
          "url": "qqrobot-framework-api-2.0.1-sources.jar",
          "size": 4270,
          "sha512": "b0fef05855c8114ee9485f3c5da954946e7b84697d693fb1f6f028a123c38a1741ce269ee69c450b7b75c2f3460f014087aaaf6a84426961221ac9cb6551e0e2",
          "sha256": "3dd917497e1d251622ed4fa4396bb7d08be47c216af611b19b89e91de27a9520",
          "sha1": "e3ab11683b5b67389c6844176baa42840adda2ff",
          "md5": "8edd6591ec1939724559035e8855b7bf"
        }
      ]
    }
  ]
}
