{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.3.jar",
          "url": "qqrobot-framework-api-1.0.3.jar",
          "size": 8552,
          "sha512": "895c15dc23c58edd4e954f3408eae371aed29d5c4935169a6af2946c5f076220bd4fabdd35959cfde0d9c21526628fc7a0de753ef56100bc4c3ff6a0dff76c29",
          "sha256": "53cd79c06b8bb1cf79209f4265c51959d5a9cac1871df2f65b95a34966958867",
          "sha1": "3dd8efb92cda82b8fdb93c0af271b9b2c1656be7",
          "md5": "5106a53ad3672f00dc79a15ba0886705"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.3.jar",
          "url": "qqrobot-framework-api-1.0.3.jar",
          "size": 8552,
          "sha512": "895c15dc23c58edd4e954f3408eae371aed29d5c4935169a6af2946c5f076220bd4fabdd35959cfde0d9c21526628fc7a0de753ef56100bc4c3ff6a0dff76c29",
          "sha256": "53cd79c06b8bb1cf79209f4265c51959d5a9cac1871df2f65b95a34966958867",
          "sha1": "3dd8efb92cda82b8fdb93c0af271b9b2c1656be7",
          "md5": "5106a53ad3672f00dc79a15ba0886705"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.3-sources.jar",
          "url": "qqrobot-framework-api-1.0.3-sources.jar",
          "size": 4676,
          "sha512": "2375750b3cffb0bfa5324b99e237f9b7c3e25f35e1bed1af5d1dd08853cf0061eccebe6b7dd1744f13f85cc275db5b367d5194c441bdce0a47361124845a472d",
          "sha256": "043be6215e1bea900848a2c67fb00a0f0e4ebf66d86ec1c45fcebbf191b8e3ec",
          "sha1": "c8099f968928390277bcc6b87888f6b076e54e07",
          "md5": "0b70f0cf23949d5e6931b6f1b298d416"
        }
      ]
    }
  ]
}
