{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.3.jar",
          "url": "qqrobot-framework-api-1.0.3.jar",
          "size": 8552,
          "sha512": "0158290b7f052114c31fef029ecd098bc7dc96c3b6a2aa1c79d23970657e5d8611504b1f9330ee59bc562586a7781cd6a747477f4c375ce4200d0d622db49a5c",
          "sha256": "233d16ebcb774593fd5f8fc2c2d0c7432b289be1f5a3bbcbe48ace397d876aee",
          "sha1": "cdfd40e7050f154c8e3daac78a18851d6b9904a5",
          "md5": "f59221d3d854840ae0c5c083efad0514"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.3.jar",
          "url": "qqrobot-framework-api-1.0.3.jar",
          "size": 8552,
          "sha512": "0158290b7f052114c31fef029ecd098bc7dc96c3b6a2aa1c79d23970657e5d8611504b1f9330ee59bc562586a7781cd6a747477f4c375ce4200d0d622db49a5c",
          "sha256": "233d16ebcb774593fd5f8fc2c2d0c7432b289be1f5a3bbcbe48ace397d876aee",
          "sha1": "cdfd40e7050f154c8e3daac78a18851d6b9904a5",
          "md5": "f59221d3d854840ae0c5c083efad0514"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.3-sources.jar",
          "url": "qqrobot-framework-api-1.0.3-sources.jar",
          "size": 4676,
          "sha512": "c30628c8e1a8690808b81b2d2599c179ab2ed38e33d3cf21f1b4281418cf53e0d9f333638a4a04cc2a3daf93196d6dbb0fbeaed561a794432365426af6039d55",
          "sha256": "031883bc00aa5f3602ee7fb77f48c590038d19d81773d92c097fd1cc41f23323",
          "sha1": "c37896381168a8bf5137b9d6c3f251c06b719609",
          "md5": "2cdd37632070b87f2453b4064a2f0716"
        }
      ]
    }
  ]
}
