{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.3.jar",
          "url": "qqrobot-framework-api-1.0.3.jar",
          "size": 8552,
          "sha512": "bf6a01b541d9d7afd876268b0104fb5f350d75f85811482c2b4936cb24bbeaaa1e84fcfdbd7b072977356d10ff420751d656ca08db44c1ee1fa927a75ab541e5",
          "sha256": "cbddabc5e0de4624285b39821b0682fc0e8a0a670021f694ceee56433b492c4f",
          "sha1": "4dff8f881fd0466931fd20301f906eea70b01ef8",
          "md5": "9fda90652c19fedd6aa1e77aa62aeb64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.3.jar",
          "url": "qqrobot-framework-api-1.0.3.jar",
          "size": 8552,
          "sha512": "bf6a01b541d9d7afd876268b0104fb5f350d75f85811482c2b4936cb24bbeaaa1e84fcfdbd7b072977356d10ff420751d656ca08db44c1ee1fa927a75ab541e5",
          "sha256": "cbddabc5e0de4624285b39821b0682fc0e8a0a670021f694ceee56433b492c4f",
          "sha1": "4dff8f881fd0466931fd20301f906eea70b01ef8",
          "md5": "9fda90652c19fedd6aa1e77aa62aeb64"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.3-sources.jar",
          "url": "qqrobot-framework-api-1.0.3-sources.jar",
          "size": 4676,
          "sha512": "9c99042105835fdc9384b18fd079e8934a7546d950d4c3e9537bcf6b42b25b7cffed6c91edc0bb298f87d367b47a1c5842421873d3f236888dc60b9afb428360",
          "sha256": "1de8c3a55b57ab6af6d9d2e6dc560caa7e7320ca06a2e40d9262e2d00c0ee631",
          "sha1": "1cc7a34afc17fd9ab549d937ea2071cff0905e8e",
          "md5": "78e096a618a66e733339c3dc2843e337"
        }
      ]
    }
  ]
}
