{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle",
    "module": "honoka-gradle-utils",
    "version": "1.0.3-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.3-dev.jar",
          "url": "honoka-gradle-utils-1.0.3-dev.jar",
          "size": 25865,
          "sha512": "ca80564de0d9ce21837bc68408c77ac6485f3d547535748ddc74883a500428964f379adaaf163282821ecf33701286627e0bbb7675b149e53dd7b1c184ab1c00",
          "sha256": "70a288514266f6e2febbd29e3c37cd6538ee708356a2c90361da1a6ba1b41903",
          "sha1": "fabc4403f2d3d42e5a3365a1c7ff4d075e3f340e",
          "md5": "50bd93a68b453a0871aa8023866dd598"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.3-dev.jar",
          "url": "honoka-gradle-utils-1.0.3-dev.jar",
          "size": 25865,
          "sha512": "ca80564de0d9ce21837bc68408c77ac6485f3d547535748ddc74883a500428964f379adaaf163282821ecf33701286627e0bbb7675b149e53dd7b1c184ab1c00",
          "sha256": "70a288514266f6e2febbd29e3c37cd6538ee708356a2c90361da1a6ba1b41903",
          "sha1": "fabc4403f2d3d42e5a3365a1c7ff4d075e3f340e",
          "md5": "50bd93a68b453a0871aa8023866dd598"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.3-dev-sources.jar",
          "url": "honoka-gradle-utils-1.0.3-dev-sources.jar",
          "size": 5432,
          "sha512": "d0bd5d3b8ae85ed55c54f6670586cff652da2bc939ed7b0927bef80732962ebec05ee402e0b67292b3f7495b0c0d00aebc56edb06d59261c81823acc5a2898f8",
          "sha256": "16d5dd359601593e4d5f7d58e9329d71ed0f50848acfbd7fdaf67547d1499126",
          "sha1": "43c66dbb1a9a65d4acc22eaf1b9f61e27920ed7c",
          "md5": "c53464152ae4bca022c3076445297e61"
        }
      ]
    }
  ]
}
