{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.1.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.1-dev.jar",
          "url": "honoka-utils-1.1.1-dev.jar",
          "size": 75968,
          "sha512": "74ee504fbd5b1a6c8c8a23b9ffbab8861e4c14566fe493e4dc035f6b71d2f11845a5964cedeb0abeeaec45ac6f3dc7a0754d9a6a05b534ce3d9a532a29d95f02",
          "sha256": "81147988693c94166ef90c623e8d7f123e09f1a051dd6121eee2ecf84657babe",
          "sha1": "57388552774bc5cea03b3da33a071b3b1265b4f3",
          "md5": "f51326e8d6fe508ac26507a4f115518c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.1-dev.jar",
          "url": "honoka-utils-1.1.1-dev.jar",
          "size": 75968,
          "sha512": "74ee504fbd5b1a6c8c8a23b9ffbab8861e4c14566fe493e4dc035f6b71d2f11845a5964cedeb0abeeaec45ac6f3dc7a0754d9a6a05b534ce3d9a532a29d95f02",
          "sha256": "81147988693c94166ef90c623e8d7f123e09f1a051dd6121eee2ecf84657babe",
          "sha1": "57388552774bc5cea03b3da33a071b3b1265b4f3",
          "md5": "f51326e8d6fe508ac26507a4f115518c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.1.1-dev-sources.jar",
          "url": "honoka-utils-1.1.1-dev-sources.jar",
          "size": 40246,
          "sha512": "3e25d8f1842d6a35928a0ff4a03fc6f7c614378af9d82ac07a8a94c6b02d5826ef9f5f1b6e6de7db9386e4d5d12b8dd5310e72887d386b6d7bfe1823878b9a5a",
          "sha256": "68e8f4d0ec41e1b132eada53710de6319fd16d5e96c861bd9a00b5cd1b2446ef",
          "sha1": "0bbc06c1520d8552b13b01459297d6fac9bbe155",
          "md5": "857e4240b88553c3377f423e5b0bdc52"
        }
      ]
    }
  ]
}
