{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.1.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.1-dev.jar",
          "url": "honoka-utils-1.1.1-dev.jar",
          "size": 74893,
          "sha512": "1e6ead1cfe8c7b1d67dc2fa649bf6c25bee2eda0485e05106f8d9805ec3ce46c6232cc43269d8c1cd71e14f1177f0bb5ba9a35ffa21448dd995b9895468b2732",
          "sha256": "c3b6ec174c74e5357503e384a8056ce59902c4ce15027cd2a9b088b474bd2415",
          "sha1": "2c31dccad4d908612930a7fcfb237ac304f1c4dc",
          "md5": "b128f257473ffd303b009c395c55bec5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.1-dev.jar",
          "url": "honoka-utils-1.1.1-dev.jar",
          "size": 74893,
          "sha512": "1e6ead1cfe8c7b1d67dc2fa649bf6c25bee2eda0485e05106f8d9805ec3ce46c6232cc43269d8c1cd71e14f1177f0bb5ba9a35ffa21448dd995b9895468b2732",
          "sha256": "c3b6ec174c74e5357503e384a8056ce59902c4ce15027cd2a9b088b474bd2415",
          "sha1": "2c31dccad4d908612930a7fcfb237ac304f1c4dc",
          "md5": "b128f257473ffd303b009c395c55bec5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.1.1-dev-sources.jar",
          "url": "honoka-utils-1.1.1-dev-sources.jar",
          "size": 38786,
          "sha512": "db3e363c47cfbd38d9dd8cda7bde14e091326b6981643ae2f53b91709f5fd75df74015029c18b4dd91fc6082a992c576a8100f00413e8c57b03e8600f1b037b7",
          "sha256": "3ab136950e6d481225b5443bcba2e24cdcfb810fe2e8b193a4aea8f665f2601a",
          "sha1": "acbb902c907df62da1b9bf02e774cc5e601630f3",
          "md5": "04abcc3db3ed1bbc18a04f7a12b102a2"
        }
      ]
    }
  ]
}
