{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.1.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.1-dev.jar",
          "url": "honoka-utils-1.1.1-dev.jar",
          "size": 75968,
          "sha512": "3e462834304fb10a91565febe6dc151bf74211b86a8645c16b1e6778e34eb487d28d7f478b75ef4482a39dd11b1b22beead010ef4df22f33f41224beb2949d06",
          "sha256": "610a696f54791841dfe26844abed726f326940e093f24530b1940ca9ec377465",
          "sha1": "aaee7a1cba2cb06e94c5b0695b49c233d6a38c82",
          "md5": "38a439b700d176a69962c65f7c81b7b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.1-dev.jar",
          "url": "honoka-utils-1.1.1-dev.jar",
          "size": 75968,
          "sha512": "3e462834304fb10a91565febe6dc151bf74211b86a8645c16b1e6778e34eb487d28d7f478b75ef4482a39dd11b1b22beead010ef4df22f33f41224beb2949d06",
          "sha256": "610a696f54791841dfe26844abed726f326940e093f24530b1940ca9ec377465",
          "sha1": "aaee7a1cba2cb06e94c5b0695b49c233d6a38c82",
          "md5": "38a439b700d176a69962c65f7c81b7b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.1.1-dev-sources.jar",
          "url": "honoka-utils-1.1.1-dev-sources.jar",
          "size": 40246,
          "sha512": "e05b68cd1cd6ea61acbaeaf8f026a8e251a86aee37d0c5c77033febb0d6b589f037c5bc9be4fbe51a392b432b3e35eaba068a1f7069c2f74335c3673959d2a87",
          "sha256": "4457635b72df5329539e540ccb3d09c5aa4787fd0f4585872df8f1369f77121d",
          "sha1": "40e6b8691be73f5306a26d4c5899c6770157c0bc",
          "md5": "5074f61d75cc6051fac6f6bc9036fffc"
        }
      ]
    }
  ]
}
