{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.1.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.1-dev.jar",
          "url": "honoka-kotlin-utils-1.1.1-dev.jar",
          "size": 132655,
          "sha512": "5ad512ce1e549ab074520f5f893ef8345456d2c70638c682636870b269fa6301561c1ddd58587ab15a4cd8762bf9b6cfc6abbb06173b0665ce7547af81f69891",
          "sha256": "f0a0319b726e0232dc5150291d2689479c35b3fbcf75b0b9b5c8ddead979d16e",
          "sha1": "a92e2fce55f82561aca380ca0839ade2166005da",
          "md5": "b12055b536cdbb552cf7568bc99cc307"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.1-dev.jar",
          "url": "honoka-kotlin-utils-1.1.1-dev.jar",
          "size": 132655,
          "sha512": "5ad512ce1e549ab074520f5f893ef8345456d2c70638c682636870b269fa6301561c1ddd58587ab15a4cd8762bf9b6cfc6abbb06173b0665ce7547af81f69891",
          "sha256": "f0a0319b726e0232dc5150291d2689479c35b3fbcf75b0b9b5c8ddead979d16e",
          "sha1": "a92e2fce55f82561aca380ca0839ade2166005da",
          "md5": "b12055b536cdbb552cf7568bc99cc307"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.1-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.1-dev-sources.jar",
          "size": 24592,
          "sha512": "d1434a3fba2bf63c69053e15123d7a0bf545f1da862945b1a14f54bb8d796dd9579bcafda76975ef7c62ddc29ae04e2b5b8b094657e7a4ae2279f125344acddb",
          "sha256": "76ee6f964847967565739f6ccb408b74d06efcf48f1f99ab2e1b9a64fb1508f1",
          "sha1": "5890d29339001df083352ef7c971a74d1cb51dc7",
          "md5": "a7630dbc1e017ca73527675923635d86"
        }
      ]
    }
  ]
}
