{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.1.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.1-dev.jar",
          "url": "honoka-kotlin-utils-1.1.1-dev.jar",
          "size": 133320,
          "sha512": "ef1092931ec6a4318b000cb00d0877378a02fb112140012a89146c09e754342f515c2d6a1077a58f3554e7088afb0f70c4b72637630e4b2484605e281a90ae72",
          "sha256": "482a4ff94e6108c8b52a9ce4adaf6caeda89095143e780c286ad2430af2eb45b",
          "sha1": "4e28200598b70717037f627d4256cdf0ad0a181c",
          "md5": "f04e2025fee1ce8179be299aa3138e11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.1-dev.jar",
          "url": "honoka-kotlin-utils-1.1.1-dev.jar",
          "size": 133320,
          "sha512": "ef1092931ec6a4318b000cb00d0877378a02fb112140012a89146c09e754342f515c2d6a1077a58f3554e7088afb0f70c4b72637630e4b2484605e281a90ae72",
          "sha256": "482a4ff94e6108c8b52a9ce4adaf6caeda89095143e780c286ad2430af2eb45b",
          "sha1": "4e28200598b70717037f627d4256cdf0ad0a181c",
          "md5": "f04e2025fee1ce8179be299aa3138e11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.1-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.1-dev-sources.jar",
          "size": 25243,
          "sha512": "21179ce463261eeb18dcbe175d377f04f47906d2c3da27ea6930be1111eb2323ee926fe7c039e6eea658faf8983898de02a9348c20a81d3dcbd8c39246501e50",
          "sha256": "b6355ad8917325efe920d4bb85974155f6d3bf084cefc2eb90ebefd4f281ee70",
          "sha1": "969a2a1f235f35f2a777b6d410fce3886ba61c7d",
          "md5": "996923bdabd030881169c17e74a42168"
        }
      ]
    }
  ]
}
