{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.0.jar",
          "url": "qqrobot-spring-boot-starter-2.0.0.jar",
          "size": 1186947,
          "sha512": "1ff53822d9c681fcdd3bd6e37de0242691fe86cdf596f4387a27a71a97c682db172f3d628dd706f4e5048012217b18c0624152e52ae238640eea42bf7446d6ff",
          "sha256": "cf073dc17db64a7ccef9be3ffdabac9e59f3190e60271973a317c40636447fb0",
          "sha1": "000c135e495333e942ff9b0b7702399621a970e8",
          "md5": "72737a84e02fbe1a64ef7732d4fab256"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "net.mamoe",
          "module": "mirai-core-jvm",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "net.mamoe",
          "module": "mirai-console-compiler-annotations-jvm",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.0.jar",
          "url": "qqrobot-spring-boot-starter-2.0.0.jar",
          "size": 1186947,
          "sha512": "1ff53822d9c681fcdd3bd6e37de0242691fe86cdf596f4387a27a71a97c682db172f3d628dd706f4e5048012217b18c0624152e52ae238640eea42bf7446d6ff",
          "sha256": "cf073dc17db64a7ccef9be3ffdabac9e59f3190e60271973a317c40636447fb0",
          "sha1": "000c135e495333e942ff9b0b7702399621a970e8",
          "md5": "72737a84e02fbe1a64ef7732d4fab256"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.0-sources.jar",
          "url": "qqrobot-spring-boot-starter-2.0.0-sources.jar",
          "size": 1111295,
          "sha512": "75e3f1bdf6034917e9c1ef52841a24bf64bec64397ea7c8c35601d4934ce93bd44f3ec6872eb763212c7c66dd287ffd570bf1c8bd773ead04b1ddcbe7f81bb1c",
          "sha256": "20e6b10068ba45b4faf1d21ee9c3b8eaefdc61796ba306b55c467d57e278c785",
          "sha1": "073892ad81f13d7e8614ab4c69cbf50d5c725e27",
          "md5": "1b239a7c15cb397087e03550ad1daf56"
        }
      ]
    }
  ]
}
