{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-android-plugin",
    "version": "1.0.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-android-plugin-1.0.2-dev.jar",
          "url": "honoka-android-plugin-1.0.2-dev.jar",
          "size": 20834,
          "sha512": "a66737d1b73ec03b311cc901a383d43b8a72f46b77bca3cd582d4455ddf155549be48f425a9c212ee60ce94ddf6b4c4271f208bbd3dccf2f9e872fbe27532305",
          "sha256": "0f81c9c07263905c66fa42329486dee6d5647bb8fc56bd677203974770c6c5eb",
          "sha1": "63f4d3314705bda6cc5e56626bbd8321ea5968a3",
          "md5": "703ff46208c4a4c195d096830a2f1581"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle.plugin",
          "module": "honoka-basic-plugin",
          "version": {
            "requires": "1.0.4-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-android-plugin-1.0.2-dev.jar",
          "url": "honoka-android-plugin-1.0.2-dev.jar",
          "size": 20834,
          "sha512": "a66737d1b73ec03b311cc901a383d43b8a72f46b77bca3cd582d4455ddf155549be48f425a9c212ee60ce94ddf6b4c4271f208bbd3dccf2f9e872fbe27532305",
          "sha256": "0f81c9c07263905c66fa42329486dee6d5647bb8fc56bd677203974770c6c5eb",
          "sha1": "63f4d3314705bda6cc5e56626bbd8321ea5968a3",
          "md5": "703ff46208c4a4c195d096830a2f1581"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-android-plugin-1.0.2-dev-sources.jar",
          "url": "honoka-android-plugin-1.0.2-dev-sources.jar",
          "size": 3940,
          "sha512": "598892f1c2d9fa88f1fba048f142d9fe9813c59e83115af40d014ee9ce4cb088312d13a7b02882e4b721cd83d78a74500f6392d087faf8a731c602dc3948f2dd",
          "sha256": "6ec32e286f621031ad93651c2eaa6ce9426860b8a97b21387eb1ac6ef59e9612",
          "sha1": "47f8dffa2d158566ac1ae8b1f6b2253eb3e80719",
          "md5": "f5e0425a419283c43b9c0e9acfa19b06"
        }
      ]
    }
  ]
}
