{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-android-plugin",
    "version": "1.0.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-android-plugin-1.0.2-dev.jar",
          "url": "honoka-android-plugin-1.0.2-dev.jar",
          "size": 20832,
          "sha512": "ed01019697c4693211779c009350fc5b2dd85dca01934b6c3b18502f68385cb3e3b1cfcac67a8f563adb7997fd718dad439d5435453aadf8bddbf7fab14d0c1f",
          "sha256": "8d1ff35ae0afa2f5223c311d86d38dd17f19e3e133f5cad21346cc1918af7dcb",
          "sha1": "7c66d140cf3f6339c5ff7f0b6322f3b67df1926e",
          "md5": "f1889d4a342553ea3fa2796c9e77c55e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle.plugin",
          "module": "honoka-basic-plugin",
          "version": {
            "requires": "1.0.4-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-android-plugin-1.0.2-dev.jar",
          "url": "honoka-android-plugin-1.0.2-dev.jar",
          "size": 20832,
          "sha512": "ed01019697c4693211779c009350fc5b2dd85dca01934b6c3b18502f68385cb3e3b1cfcac67a8f563adb7997fd718dad439d5435453aadf8bddbf7fab14d0c1f",
          "sha256": "8d1ff35ae0afa2f5223c311d86d38dd17f19e3e133f5cad21346cc1918af7dcb",
          "sha1": "7c66d140cf3f6339c5ff7f0b6322f3b67df1926e",
          "md5": "f1889d4a342553ea3fa2796c9e77c55e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-android-plugin-1.0.2-dev-sources.jar",
          "url": "honoka-android-plugin-1.0.2-dev-sources.jar",
          "size": 3940,
          "sha512": "598892f1c2d9fa88f1fba048f142d9fe9813c59e83115af40d014ee9ce4cb088312d13a7b02882e4b721cd83d78a74500f6392d087faf8a731c602dc3948f2dd",
          "sha256": "6ec32e286f621031ad93651c2eaa6ce9426860b8a97b21387eb1ac6ef59e9612",
          "sha1": "47f8dffa2d158566ac1ae8b1f6b2253eb3e80719",
          "md5": "f5e0425a419283c43b9c0e9acfa19b06"
        }
      ]
    }
  ]
}
