{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.8.jar",
          "url": "honoka-utils-1.0.8.jar",
          "size": 66078,
          "sha512": "11744a63eb491132db5da5f90c91e254d2d3853795a0e6b50e9be4a35906c6fa2279c7e79b8965f20d243a9ce3217f722692bd720d55227e72247de8aabd169f",
          "sha256": "0294345f449a589efa16551f3580ab4aa891e17385548dadcc8fcf852118380a",
          "sha1": "ac0ec4256e48c012cfa9ccc8e118e0075a2478e7",
          "md5": "938b189b7ef6545c298c964fa0406532"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.8.jar",
          "url": "honoka-utils-1.0.8.jar",
          "size": 66078,
          "sha512": "11744a63eb491132db5da5f90c91e254d2d3853795a0e6b50e9be4a35906c6fa2279c7e79b8965f20d243a9ce3217f722692bd720d55227e72247de8aabd169f",
          "sha256": "0294345f449a589efa16551f3580ab4aa891e17385548dadcc8fcf852118380a",
          "sha1": "ac0ec4256e48c012cfa9ccc8e118e0075a2478e7",
          "md5": "938b189b7ef6545c298c964fa0406532"
        }
      ]
    }
  ]
}
