{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.8.jar",
          "url": "honoka-utils-1.0.8.jar",
          "size": 66078,
          "sha512": "633bddbdd3126484afde602d6164ac5a813264060f289db1289df5ace27fe8b267a9b9888c9eeb7b7e5d1a9ec324571394f75d301e0bfd0155dd990dba1f1714",
          "sha256": "10063421a2d290dca1f877a525752cc2b67808eba10fc91f1c560098e1014d77",
          "sha1": "4dc0eb5b3ca39f353860d4506e108bc8862c5b44",
          "md5": "475bbc25c0e32978c9f9e62610fc9380"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.8.jar",
          "url": "honoka-utils-1.0.8.jar",
          "size": 66078,
          "sha512": "633bddbdd3126484afde602d6164ac5a813264060f289db1289df5ace27fe8b267a9b9888c9eeb7b7e5d1a9ec324571394f75d301e0bfd0155dd990dba1f1714",
          "sha256": "10063421a2d290dca1f877a525752cc2b67808eba10fc91f1c560098e1014d77",
          "sha1": "4dc0eb5b3ca39f353860d4506e108bc8862c5b44",
          "md5": "475bbc25c0e32978c9f9e62610fc9380"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.0.8-sources.jar",
          "url": "honoka-utils-1.0.8-sources.jar",
          "size": 36189,
          "sha512": "e5897690815781021c9b5b19bf9e5e67ba24369578958c85112bc66c5b7680c8d1b1ce8f5a3a74be4ac4c42d0d22be5de297ddc91795fc654f0ea590381654ad",
          "sha256": "2e9f661a3aa9ae734a14936800855ebc28810195416a85db03aec9c3f740e71b",
          "sha1": "e410a65535949eb2916f714ddd1f99d73ddc1357",
          "md5": "0833240a06c1d3df4157a999343cf045"
        }
      ]
    }
  ]
}
