{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.8.jar",
          "url": "honoka-utils-1.0.8.jar",
          "size": 66078,
          "sha512": "4bf3f60756e097e6c6457e1a393491e2a352d319916c21fc33f159e2a201c09fed49402500b8357556b849929cd9fe30ac20e4dacab6a21c57e1d90805642fe6",
          "sha256": "65689ef83ccc6141f018f2ff7d6c076e23342718facb41746cb1023759c0a6fb",
          "sha1": "9da025cda7d7fc0e5707070f639b463fd6cf859f",
          "md5": "aec9bff2602b281354313d89f2cbfb50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.8.jar",
          "url": "honoka-utils-1.0.8.jar",
          "size": 66078,
          "sha512": "4bf3f60756e097e6c6457e1a393491e2a352d319916c21fc33f159e2a201c09fed49402500b8357556b849929cd9fe30ac20e4dacab6a21c57e1d90805642fe6",
          "sha256": "65689ef83ccc6141f018f2ff7d6c076e23342718facb41746cb1023759c0a6fb",
          "sha1": "9da025cda7d7fc0e5707070f639b463fd6cf859f",
          "md5": "aec9bff2602b281354313d89f2cbfb50"
        }
      ]
    }
  ]
}
