{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-2.0.0.jar",
          "url": "honoka-utils-2.0.0.jar",
          "size": 72035,
          "sha512": "235a01e8c48f9979b2895b6056d8049b219a38a6ed3d534a7ca271f81ed03d73061338631b333e06434e2c7d7047bf85dd05dcc074d3ebe8448b67bdb6ba9c82",
          "sha256": "53ea1332f1a8185a6149ee994f3d08896dbe48f69763bca934ad492fc17ae6b3",
          "sha1": "b7532faa2a96cd6d0ee38e459527ee5659a59d0e",
          "md5": "2c4298f934dc4009d5a5e5a65f2555d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-2.0.0.jar",
          "url": "honoka-utils-2.0.0.jar",
          "size": 72035,
          "sha512": "235a01e8c48f9979b2895b6056d8049b219a38a6ed3d534a7ca271f81ed03d73061338631b333e06434e2c7d7047bf85dd05dcc074d3ebe8448b67bdb6ba9c82",
          "sha256": "53ea1332f1a8185a6149ee994f3d08896dbe48f69763bca934ad492fc17ae6b3",
          "sha1": "b7532faa2a96cd6d0ee38e459527ee5659a59d0e",
          "md5": "2c4298f934dc4009d5a5e5a65f2555d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-2.0.0-sources.jar",
          "url": "honoka-utils-2.0.0-sources.jar",
          "size": 38277,
          "sha512": "4139cd1404d352d1d742527ab1f706504266206ce66b1f889b7dcecf77766ffae40700b995ce3eeb5eea0cfc706d7dfd0acea9814ed5543b72628fcd650f9b50",
          "sha256": "cffd15162f72b4a1cedc8eb591f62eca1fe3a1f223b3ee7493b2681a05b988e2",
          "sha1": "779c5b86637cb66d1297a2f23e97d24bd3f12a67",
          "md5": "71f6f80a0a82ef39fa01488cbe6749b0"
        }
      ]
    }
  ]
}
