{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-2.0.0.jar",
          "url": "honoka-utils-2.0.0.jar",
          "size": 72035,
          "sha512": "db06c73f557529040a3e7c35f52b1945c040f0b21a09833342c291e8ed507ec2ff48cfd0b2fdb9ae6fd427f13ce18f926b6470e4830c12af59176f3837e8e428",
          "sha256": "3b11285a992a0c424f806b96bdc223beead83ad2e0229b3aaaf5b60ab911f212",
          "sha1": "d41a2af43317031bbf8ef79c6c467bc34eec7613",
          "md5": "a81eb7d18c3bf8ec677a1d23da36cc06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-2.0.0.jar",
          "url": "honoka-utils-2.0.0.jar",
          "size": 72035,
          "sha512": "db06c73f557529040a3e7c35f52b1945c040f0b21a09833342c291e8ed507ec2ff48cfd0b2fdb9ae6fd427f13ce18f926b6470e4830c12af59176f3837e8e428",
          "sha256": "3b11285a992a0c424f806b96bdc223beead83ad2e0229b3aaaf5b60ab911f212",
          "sha1": "d41a2af43317031bbf8ef79c6c467bc34eec7613",
          "md5": "a81eb7d18c3bf8ec677a1d23da36cc06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-2.0.0-sources.jar",
          "url": "honoka-utils-2.0.0-sources.jar",
          "size": 38277,
          "sha512": "e469107550c3b55b58fcdb46b28aa175d9847f1bd5883e856e5ecc75a222af8e2638245345fe92e00baed8a9ca35b1fd97e588364d852cee0f3ff693985d9115",
          "sha256": "1bc46eb0d644fb1c57f7d514f775d8059bc6fe546161a2ca8285efe3f0cd4b02",
          "sha1": "704742f22cd6ee0eff19846441f6eaf407eea087",
          "md5": "9b2ca47d56c7871216773d2cbaeca7b4"
        }
      ]
    }
  ]
}
