{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-2.0.0.jar",
          "url": "honoka-utils-2.0.0.jar",
          "size": 72035,
          "sha512": "2b7af00cf7f76ab8dae48a2960c61a598b717233087d46d57aae3541bc00c329bee33ff45992346d1c3a996c8cc66960530f1b92efc9122b1b8cf75161de8ffa",
          "sha256": "6b8655c08f0f3e7b3308a5c509309d027b3f693d26315379fc17254177fdad1d",
          "sha1": "0376a0fd81df6a392fa05aa80fc3ce3da341a108",
          "md5": "d2efe1e0659392251e486e74cd9a8af5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-2.0.0.jar",
          "url": "honoka-utils-2.0.0.jar",
          "size": 72035,
          "sha512": "2b7af00cf7f76ab8dae48a2960c61a598b717233087d46d57aae3541bc00c329bee33ff45992346d1c3a996c8cc66960530f1b92efc9122b1b8cf75161de8ffa",
          "sha256": "6b8655c08f0f3e7b3308a5c509309d027b3f693d26315379fc17254177fdad1d",
          "sha1": "0376a0fd81df6a392fa05aa80fc3ce3da341a108",
          "md5": "d2efe1e0659392251e486e74cd9a8af5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-2.0.0-sources.jar",
          "url": "honoka-utils-2.0.0-sources.jar",
          "size": 38277,
          "sha512": "4a4c36f45489c87b8e939163d7302094643557013dbf5582f615d6a5a9dba803b684ecb0487c499ff75411ca75396e08e07b8409fdddca4a0d797f9e24b9f88c",
          "sha256": "2c271d2f38ea8b197a6b20fae09aea3970c08dd0e892ce34d51678dfd1b25776",
          "sha1": "a51c7ffb3c8c5f1d45fed8dc51d50a992e05c26a",
          "md5": "60a941aed8df2b9eeff684349239f7a6"
        }
      ]
    }
  ]
}
