{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle",
    "module": "honoka-gradle-utils",
    "version": "1.0.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.2-dev.jar",
          "url": "honoka-gradle-utils-1.0.2-dev.jar",
          "size": 28730,
          "sha512": "d570869a7c10ca28f94370485e9946417ce0ee4f758ae02d783e88ad8c186a961e822254d6cc38303010e958fdabffefcb1adb2a3a74f56cd80cd772939b3b98",
          "sha256": "401e0fd9b33d0a6e429bae21319d71a3a523f514e74b6fa5c3b7f461a8884898",
          "sha1": "28911623105f7386902a290110bb11921b60ae9a",
          "md5": "42c361fd4745c01cc35d32072861089e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.2-dev.jar",
          "url": "honoka-gradle-utils-1.0.2-dev.jar",
          "size": 28730,
          "sha512": "d570869a7c10ca28f94370485e9946417ce0ee4f758ae02d783e88ad8c186a961e822254d6cc38303010e958fdabffefcb1adb2a3a74f56cd80cd772939b3b98",
          "sha256": "401e0fd9b33d0a6e429bae21319d71a3a523f514e74b6fa5c3b7f461a8884898",
          "sha1": "28911623105f7386902a290110bb11921b60ae9a",
          "md5": "42c361fd4745c01cc35d32072861089e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.2-dev-sources.jar",
          "url": "honoka-gradle-utils-1.0.2-dev-sources.jar",
          "size": 5317,
          "sha512": "17d4864254b5a4c89d676861f5aa52669514fbd44b7652a35b08e5d8d6b89ff31372a932aba8267f1c032aaf6704428347c4eef5acdd4c53ab6448c2da9e0045",
          "sha256": "f9bcc3f42e23dd5200c0540c8c7099bf3a1dd8af8ed25984e740c0f6f0f835ea",
          "sha1": "dd0cd970335cefb9cd9cae0ad74f9496382d114e",
          "md5": "1994ec35cfe79f72107c9871f266a038"
        }
      ]
    }
  ]
}
