{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle",
    "module": "honoka-gradle-utils",
    "version": "1.0.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.2-dev.jar",
          "url": "honoka-gradle-utils-1.0.2-dev.jar",
          "size": 24719,
          "sha512": "3f96254a29f43340caecc84c8dcd74d322934b4cd8fa3eb1a0addf02733801944e0afc01a0bc4106bf7ec79578cf7c9d0bd45af7e6b0ca75073ae2e9f75c7e60",
          "sha256": "2b216092433bdbd4ef61332d528d8533175f6a209e1e34765244b6ea10b91b80",
          "sha1": "0da7e319bc9947e888c5848a46a8340763b4f0b0",
          "md5": "4cc27a91bef8ed36e290ea3b519ff98d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.2-dev.jar",
          "url": "honoka-gradle-utils-1.0.2-dev.jar",
          "size": 24719,
          "sha512": "3f96254a29f43340caecc84c8dcd74d322934b4cd8fa3eb1a0addf02733801944e0afc01a0bc4106bf7ec79578cf7c9d0bd45af7e6b0ca75073ae2e9f75c7e60",
          "sha256": "2b216092433bdbd4ef61332d528d8533175f6a209e1e34765244b6ea10b91b80",
          "sha1": "0da7e319bc9947e888c5848a46a8340763b4f0b0",
          "md5": "4cc27a91bef8ed36e290ea3b519ff98d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.2-dev-sources.jar",
          "url": "honoka-gradle-utils-1.0.2-dev-sources.jar",
          "size": 5317,
          "sha512": "84a7663053a425bbb10d5a80b3c6c93b0fd36536a58be0d52e1aac5c4169643e4a2d4b6f3020bbe222cf691f61b97fbbb478ddbc4593355dc750485281250525",
          "sha256": "44f6655916541104dd9c8808cb8a01065ec8b0959bbfc0ec9f7230d3bd21b447",
          "sha1": "c50b95b5b9f741f94c9b633fd1c266401bc0af00",
          "md5": "da4ed11b09dacf97797fe78acd9140ba"
        }
      ]
    }
  ]
}
