{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-json-api",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "honoka-json-api-1.1.3.jar",
          "url": "honoka-json-api-1.1.3.jar",
          "size": 11145,
          "sha512": "54e7dea2f90992c22b49c192faf19fcbdfaa295bed8786313ff181cf0e0120907da984542331ebc65ef85e62bacedfc6ba76ffda4675a601fddc02c564ea6a41",
          "sha256": "1e13f216b353fd318217470903eb8bce7f71d88ced5d49e07c977e74b968eb7d",
          "sha1": "b3499ea328684f25754787ce1647ec7e2708f9bd",
          "md5": "c641267e2ecb2128c2193fbe9a84b81e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-api-1.1.3.jar",
          "url": "honoka-json-api-1.1.3.jar",
          "size": 11145,
          "sha512": "54e7dea2f90992c22b49c192faf19fcbdfaa295bed8786313ff181cf0e0120907da984542331ebc65ef85e62bacedfc6ba76ffda4675a601fddc02c564ea6a41",
          "sha256": "1e13f216b353fd318217470903eb8bce7f71d88ced5d49e07c977e74b968eb7d",
          "sha1": "b3499ea328684f25754787ce1647ec7e2708f9bd",
          "md5": "c641267e2ecb2128c2193fbe9a84b81e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-json-api-1.1.3-sources.jar",
          "url": "honoka-json-api-1.1.3-sources.jar",
          "size": 6903,
          "sha512": "81ce355465ccf7f345802b23297b9eca2456f60f9782c4c9e3227e3d36ae344e6060d2884b4e2a9a26d1d7935e25436a06b65425f3507dbaac28c5e2c4179ce8",
          "sha256": "87ab0c9bcc35cd22b27e6b9dae6d7bebc093aa5700bee78964842ca04b13d481",
          "sha1": "3ad4c31bbb4db91204b4a2de416934f5bd8aac61",
          "md5": "798fd0ca90a7a7425511cdce6783e7b0"
        }
      ]
    }
  ]
}
