{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-json-api",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "honoka-json-api-1.1.3.jar",
          "url": "honoka-json-api-1.1.3.jar",
          "size": 11145,
          "sha512": "685ab3c1b789e46135dd0e42b62a20563b19c59d0780d8b8bec1e8d4a930c33595ada1609d2719f53659e2cf9c8dda57b64a58b8afa7c442cf9ec73f44be672a",
          "sha256": "74a51569487a2b7358e42f4e90dda5c1e80941aad34964448ac586b64ca9f63b",
          "sha1": "ad2a423fe1afa8d297596be5da54d7d9334e104a",
          "md5": "ecd9b88fcffbc10da80a4f45a03e3601"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-api-1.1.3.jar",
          "url": "honoka-json-api-1.1.3.jar",
          "size": 11145,
          "sha512": "685ab3c1b789e46135dd0e42b62a20563b19c59d0780d8b8bec1e8d4a930c33595ada1609d2719f53659e2cf9c8dda57b64a58b8afa7c442cf9ec73f44be672a",
          "sha256": "74a51569487a2b7358e42f4e90dda5c1e80941aad34964448ac586b64ca9f63b",
          "sha1": "ad2a423fe1afa8d297596be5da54d7d9334e104a",
          "md5": "ecd9b88fcffbc10da80a4f45a03e3601"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-json-api-1.1.3-sources.jar",
          "url": "honoka-json-api-1.1.3-sources.jar",
          "size": 6903,
          "sha512": "4c2d149cebc75442fac3dcad9d1f6a1108c1fb97da2e9bec18c1a02d501342e57742f484a83a59477a39a1ec1ce372471322ff441c34691f676ee083d88469be",
          "sha256": "1826b157c02f31104b6b0767f4fe384477cab34b8ddf73a39966dc3aacf17ce7",
          "sha1": "28d3ef506e4b30a6233c52613389da4decf48db9",
          "md5": "d75adf953b413d8a4aca241282d8ddd1"
        }
      ]
    }
  ]
}
