{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-json-api",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "honoka-json-api-1.1.3.jar",
          "url": "honoka-json-api-1.1.3.jar",
          "size": 11145,
          "sha512": "2080545d53a34752e0d1ca9948e2f6ab837727b194d48ec33569fe1f31f304b76f08cfc997b7a7b77fb60a579734b20682c70efecdb99e622c868102f40b523c",
          "sha256": "444c6a50aea81ea73e3446915490a13775686c09617050e3b4fba8da218c3497",
          "sha1": "abe091ccab15b3ca8d5c7061c83c5ccb6b67a170",
          "md5": "59f057a7e6629a31d5c3e9206a2d2666"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-api-1.1.3.jar",
          "url": "honoka-json-api-1.1.3.jar",
          "size": 11145,
          "sha512": "2080545d53a34752e0d1ca9948e2f6ab837727b194d48ec33569fe1f31f304b76f08cfc997b7a7b77fb60a579734b20682c70efecdb99e622c868102f40b523c",
          "sha256": "444c6a50aea81ea73e3446915490a13775686c09617050e3b4fba8da218c3497",
          "sha1": "abe091ccab15b3ca8d5c7061c83c5ccb6b67a170",
          "md5": "59f057a7e6629a31d5c3e9206a2d2666"
        }
      ]
    }
  ]
}
