{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle",
    "module": "honoka-gradle-utils",
    "version": "1.1.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.1.0-dev.jar",
          "url": "honoka-gradle-utils-1.1.0-dev.jar",
          "size": 27876,
          "sha512": "73d83013d3f216b31b357407004989c3cdef0f11ffdaa0562fffa0390277a8058ae0499111f1b2045daefa73d5f47135beaf87f5eaba6177f0d00b5c7580837c",
          "sha256": "a8a549ae435f9bbfa92a66641ec4a974024994f878159ef5ccf2a13364c932da",
          "sha1": "073db7ecfadddcba732bd3f5ed477c9c0c1cbff8",
          "md5": "12d05ce997bf2464e325cf77ea68d2c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.1.0-dev.jar",
          "url": "honoka-gradle-utils-1.1.0-dev.jar",
          "size": 27876,
          "sha512": "73d83013d3f216b31b357407004989c3cdef0f11ffdaa0562fffa0390277a8058ae0499111f1b2045daefa73d5f47135beaf87f5eaba6177f0d00b5c7580837c",
          "sha256": "a8a549ae435f9bbfa92a66641ec4a974024994f878159ef5ccf2a13364c932da",
          "sha1": "073db7ecfadddcba732bd3f5ed477c9c0c1cbff8",
          "md5": "12d05ce997bf2464e325cf77ea68d2c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.1.0-dev-sources.jar",
          "url": "honoka-gradle-utils-1.1.0-dev-sources.jar",
          "size": 5618,
          "sha512": "e89b695825b8928aa6400c1cabb6769b1c1c579e4f72d4368aaa4447657eef3567afbaa8b8aba14abcb44e402d408026a8e1f3a621febebaa96c1774570e15c8",
          "sha256": "f696ab4e33527bb0d69dc611c6994d2442d8705a7f2138976b8685bc3bdda695",
          "sha1": "bc62369491400b8d0ac4b772758c2461c6301fc2",
          "md5": "573a14c50733a71d927c199915675e62"
        }
      ]
    }
  ]
}
