{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle",
    "module": "honoka-gradle-utils",
    "version": "1.1.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.1.0-dev.jar",
          "url": "honoka-gradle-utils-1.1.0-dev.jar",
          "size": 29180,
          "sha512": "1131c65b79c32ebcda963c7c516c9f9e057971285d817aea31486c2ec7a1dc8fa8012a137a0888e5987ddeaa781d1642a049db48f14db92deb006625f4dd9117",
          "sha256": "7d3847a4d316df93ef2e4b44b6b8e7421715cc710633ea8848ba82b2b4f2f001",
          "sha1": "1d56d9ce415ab9a386fe122dcbc12d1af4ae605e",
          "md5": "8bc037e0a9186a4fbce7f92449642b17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.1.0-dev.jar",
          "url": "honoka-gradle-utils-1.1.0-dev.jar",
          "size": 29180,
          "sha512": "1131c65b79c32ebcda963c7c516c9f9e057971285d817aea31486c2ec7a1dc8fa8012a137a0888e5987ddeaa781d1642a049db48f14db92deb006625f4dd9117",
          "sha256": "7d3847a4d316df93ef2e4b44b6b8e7421715cc710633ea8848ba82b2b4f2f001",
          "sha1": "1d56d9ce415ab9a386fe122dcbc12d1af4ae605e",
          "md5": "8bc037e0a9186a4fbce7f92449642b17"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.1.0-dev-sources.jar",
          "url": "honoka-gradle-utils-1.1.0-dev-sources.jar",
          "size": 6145,
          "sha512": "7ee7df45b3c2ebe168c664d24ebbf12cd167aff05f48754a0ed2679f702d864f2da22e037c22e2d023ce07541146a92cf5c4e5fe6e2fe72fbfe7006ee492844e",
          "sha256": "ddc82fd936d591a79e203e694ef7dd5d94d00cb08111de0f5bfe1b025be4afff",
          "sha1": "d5e23ff97962381b9a911650b4f58aee031325ed",
          "md5": "7576e36ca551b5d08717d8ce225d4954"
        }
      ]
    }
  ]
}
