{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle",
    "module": "honoka-gradle-utils",
    "version": "1.1.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.1.0-dev.jar",
          "url": "honoka-gradle-utils-1.1.0-dev.jar",
          "size": 27818,
          "sha512": "688adc0c71b15c360be8a563d21e50014558565e94674fd9b56901a61028db78afb51bf85ffa9128d3abe5e82d67eba22051671446afe440b207dfa6a76ef318",
          "sha256": "949b2b60c69c9f73f42a2ad37a404834986dc997c33e6686c6b9bc6cb94790b0",
          "sha1": "4d31f07782758c7e94ed083f81afd01ea4861aba",
          "md5": "38386196bfb7a8e79f6d9c699026f50b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.1.0-dev.jar",
          "url": "honoka-gradle-utils-1.1.0-dev.jar",
          "size": 27818,
          "sha512": "688adc0c71b15c360be8a563d21e50014558565e94674fd9b56901a61028db78afb51bf85ffa9128d3abe5e82d67eba22051671446afe440b207dfa6a76ef318",
          "sha256": "949b2b60c69c9f73f42a2ad37a404834986dc997c33e6686c6b9bc6cb94790b0",
          "sha1": "4d31f07782758c7e94ed083f81afd01ea4861aba",
          "md5": "38386196bfb7a8e79f6d9c699026f50b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.1.0-dev-sources.jar",
          "url": "honoka-gradle-utils-1.1.0-dev-sources.jar",
          "size": 5612,
          "sha512": "a1afa463aa491f7298b1a45337499813e821f7e8008b54bad1bd0cfd967a55d937a2b4531d27fbe0d4df3521e7c5639917a2e05c35e44297713560c0b040b357",
          "sha256": "5f49aba11bd94fbc353cd93ee21575e5180eeb79b7be739183fa56723d4d34af",
          "sha1": "651c8f0bab887cfed8d690bfaa3e2163cd614ddf",
          "md5": "c3a447c8776bc15a3136d5231959bcd5"
        }
      ]
    }
  ]
}
