{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-basic-plugin",
    "version": "1.0.4-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.4-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.4-dev.jar",
          "url": "honoka-basic-plugin-1.0.4-dev.jar",
          "size": 25169,
          "sha512": "85d33b9c4c3176757c091964e2508e43997fc12e40f5f4949b57ea8a5d12945f5019869f26182e390229031a18517b995c5e46143a81fccb4b03cc2bb88e3aad",
          "sha256": "6a63e0e1caed857d8af3c548046e2fa03534fbff3b21422cc1c868b34f75a1cc",
          "sha1": "c59d94886f2263c118dae137d6b1ad1af488b899",
          "md5": "8e4c330bd803aed181b1a71779dbfac4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.4-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.4-dev.jar",
          "url": "honoka-basic-plugin-1.0.4-dev.jar",
          "size": 25169,
          "sha512": "85d33b9c4c3176757c091964e2508e43997fc12e40f5f4949b57ea8a5d12945f5019869f26182e390229031a18517b995c5e46143a81fccb4b03cc2bb88e3aad",
          "sha256": "6a63e0e1caed857d8af3c548046e2fa03534fbff3b21422cc1c868b34f75a1cc",
          "sha1": "c59d94886f2263c118dae137d6b1ad1af488b899",
          "md5": "8e4c330bd803aed181b1a71779dbfac4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.4-dev-sources.jar",
          "url": "honoka-basic-plugin-1.0.4-dev-sources.jar",
          "size": 3774,
          "sha512": "185ad28814c0f78fd4669e0c9c93171fa7156667456bde23b5df5a890a2da495347b555667ec1590833904a40cf758b237177bca4c3914a3100143873654486e",
          "sha256": "6b1596092baa6eb77641d366a09050210ebb9d781b049bb9ccbaf4468ecaf3ac",
          "sha1": "52b3b8927c7423e1e7d4b6f94ecb04bb7a033e30",
          "md5": "e4b1f55babcb9c1e7e244163347bf90a"
        }
      ]
    }
  ]
}
