{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-basic-plugin",
    "version": "1.0.4-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.4-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.4-dev.jar",
          "url": "honoka-basic-plugin-1.0.4-dev.jar",
          "size": 25079,
          "sha512": "70b233bb466b63f4861635ddb225ef8ee899c4e0b7203eefb5abf60373d2cc2623ed4e2efa7cf483aa191a766826b0bb2025b1cfec5eb193fe992f121ae86a0b",
          "sha256": "8175fe71ca450564071ec6ca56cf23b275a09f060e2c5bf26003ddf3b572664e",
          "sha1": "8bf32a9fa3dfeb9bda121eb418e1f9494fe02162",
          "md5": "7b187e7f86f1f5b658c6735a9d322177"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.4-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.4-dev.jar",
          "url": "honoka-basic-plugin-1.0.4-dev.jar",
          "size": 25079,
          "sha512": "70b233bb466b63f4861635ddb225ef8ee899c4e0b7203eefb5abf60373d2cc2623ed4e2efa7cf483aa191a766826b0bb2025b1cfec5eb193fe992f121ae86a0b",
          "sha256": "8175fe71ca450564071ec6ca56cf23b275a09f060e2c5bf26003ddf3b572664e",
          "sha1": "8bf32a9fa3dfeb9bda121eb418e1f9494fe02162",
          "md5": "7b187e7f86f1f5b658c6735a9d322177"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.4-dev-sources.jar",
          "url": "honoka-basic-plugin-1.0.4-dev-sources.jar",
          "size": 3774,
          "sha512": "185ad28814c0f78fd4669e0c9c93171fa7156667456bde23b5df5a890a2da495347b555667ec1590833904a40cf758b237177bca4c3914a3100143873654486e",
          "sha256": "6b1596092baa6eb77641d366a09050210ebb9d781b049bb9ccbaf4468ecaf3ac",
          "sha1": "52b3b8927c7423e1e7d4b6f94ecb04bb7a033e30",
          "md5": "e4b1f55babcb9c1e7e244163347bf90a"
        }
      ]
    }
  ]
}
