{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender",
    "module": "lavsource-spring-boot-starter",
    "version": "1.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "lavsource-spring-boot-starter-1.0.1-dev.jar",
          "url": "lavsource-spring-boot-starter-1.0.1-dev.jar",
          "size": 20001,
          "sha512": "6d4bf10fbe06ec9e2e5f5bc4d473e00ca5167f6a87d8f88ec6f573177aeaace7cde78e94f71bbe4ee7e0394ab0777e1e6fc38f4bac5d0ae10fc06444abb82d04",
          "sha256": "e074b0a0273e8a577b5f701314f3bdfc2b5e950890ba6d59e6bd5672ed4653e9",
          "sha1": "37db71e5b488ed3762a3ddfba89ac7ef6f962302",
          "md5": "6e0c6afed5338106b2f84b8216627848"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.1-dev"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-framework-utils",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        }
      ],
      "files": [
        {
          "name": "lavsource-spring-boot-starter-1.0.1-dev.jar",
          "url": "lavsource-spring-boot-starter-1.0.1-dev.jar",
          "size": 20001,
          "sha512": "6d4bf10fbe06ec9e2e5f5bc4d473e00ca5167f6a87d8f88ec6f573177aeaace7cde78e94f71bbe4ee7e0394ab0777e1e6fc38f4bac5d0ae10fc06444abb82d04",
          "sha256": "e074b0a0273e8a577b5f701314f3bdfc2b5e950890ba6d59e6bd5672ed4653e9",
          "sha1": "37db71e5b488ed3762a3ddfba89ac7ef6f962302",
          "md5": "6e0c6afed5338106b2f84b8216627848"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavsource-spring-boot-starter-1.0.1-dev-sources.jar",
          "url": "lavsource-spring-boot-starter-1.0.1-dev-sources.jar",
          "size": 7396,
          "sha512": "5ccba7f010164b1356d59020915abc80111f20b6a7d8bac61fe622069911c8ae307badf948454c1cda35a4d99f563c3ba7056ff50097e0034c20275c029dcb6e",
          "sha256": "d9787209602c48f46df74c036c4436e7e5a919d585268c41b4e99d4a8763bb14",
          "sha1": "036bf5053c32d3a7aabda6065f40d849cd519882",
          "md5": "54256fb27d6dfb669ed98ceb8bb57e6f"
        }
      ]
    }
  ]
}
