{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender",
    "module": "lavsource-spring-boot-starter",
    "version": "1.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "lavsource-spring-boot-starter-1.0.1-dev.jar",
          "url": "lavsource-spring-boot-starter-1.0.1-dev.jar",
          "size": 20000,
          "sha512": "d7774bad3867ca66584e3246713a373b3d9ff76c8eee4aa48fd5aee71a2073841ac19f5bf317b89f2b21abf03d1ac2e2cb696765911579a19071fb1ac6a2c886",
          "sha256": "3712211a4b5119633b2e8f9b397b2bdef7d9406a1a519a8f47afaa23f53af990",
          "sha1": "fd989a0aada5464c106369a229690a54e30db560",
          "md5": "a228f2b3ca2dfa9cabbff834e666a2ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.1-dev"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-framework-utils",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        }
      ],
      "files": [
        {
          "name": "lavsource-spring-boot-starter-1.0.1-dev.jar",
          "url": "lavsource-spring-boot-starter-1.0.1-dev.jar",
          "size": 20000,
          "sha512": "d7774bad3867ca66584e3246713a373b3d9ff76c8eee4aa48fd5aee71a2073841ac19f5bf317b89f2b21abf03d1ac2e2cb696765911579a19071fb1ac6a2c886",
          "sha256": "3712211a4b5119633b2e8f9b397b2bdef7d9406a1a519a8f47afaa23f53af990",
          "sha1": "fd989a0aada5464c106369a229690a54e30db560",
          "md5": "a228f2b3ca2dfa9cabbff834e666a2ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavsource-spring-boot-starter-1.0.1-dev-sources.jar",
          "url": "lavsource-spring-boot-starter-1.0.1-dev-sources.jar",
          "size": 7393,
          "sha512": "9a9261570f4b7082c8d7933c3892a784d223f9a9bede529ba6d88800fe27cddcf4fb778d95f43b7f1917771c425742d2cb3dcc07d2cbd511197fc0ed333ff8a2",
          "sha256": "7cc23ae921dd57d03ebab5f096352c86bc19ce79186612a88cd8c6b5abd8fa48",
          "sha1": "0823fd9a9c2593a823d2676f839ed1e36cbddf43",
          "md5": "87b960bc3139ca92f87a3c7b5f51924e"
        }
      ]
    }
  ]
}
