{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.2.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.2.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.2.0-dev.jar",
          "url": "honoka-kotlin-utils-1.2.0-dev.jar",
          "size": 119458,
          "sha512": "6c734271fda78210de241632944211bedc8c7f72202888c25b40e93d12f819c9d4c9b5c4c35b590207bf99febfb1ee2a6fff8468346eda949cd0bc849bdee8c2",
          "sha256": "83795af1409c5ef6f4797c09eac539b42749a0a7b4ac0b496ca0f5158b1d28e8",
          "sha1": "d40294923d4a41af66faa60f4101d3af10dcaa2c",
          "md5": "947b6fda29717fc8fb69f98d4ee89af0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.2.0-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.2.0-dev.jar",
          "url": "honoka-kotlin-utils-1.2.0-dev.jar",
          "size": 119458,
          "sha512": "6c734271fda78210de241632944211bedc8c7f72202888c25b40e93d12f819c9d4c9b5c4c35b590207bf99febfb1ee2a6fff8468346eda949cd0bc849bdee8c2",
          "sha256": "83795af1409c5ef6f4797c09eac539b42749a0a7b4ac0b496ca0f5158b1d28e8",
          "sha1": "d40294923d4a41af66faa60f4101d3af10dcaa2c",
          "md5": "947b6fda29717fc8fb69f98d4ee89af0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.2.0-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.2.0-dev-sources.jar",
          "size": 26483,
          "sha512": "af78705579cfe2b758b9a384a200f040f98c531a110b7c041cf6744cc9ade57a20877160b610eccda0ae3c78eaa149362cfd9ec9cea350ac4178eeca2cbae72f",
          "sha256": "2055acca3eedc412010a5570a0ab797e7d9cd924e78ef77a514782d51452ccd5",
          "sha1": "fe380739e43240da61ee26dfe409d6c1fd650fcf",
          "md5": "d1e727a84cb14bbb10f38dc2721a6f17"
        },
        {
          "name": "honoka-kotlin-utils-1.2.0-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.2.0-dev-sources.jar",
          "size": 26483,
          "sha512": "af78705579cfe2b758b9a384a200f040f98c531a110b7c041cf6744cc9ade57a20877160b610eccda0ae3c78eaa149362cfd9ec9cea350ac4178eeca2cbae72f",
          "sha256": "2055acca3eedc412010a5570a0ab797e7d9cd924e78ef77a514782d51452ccd5",
          "sha1": "fe380739e43240da61ee26dfe409d6c1fd650fcf",
          "md5": "d1e727a84cb14bbb10f38dc2721a6f17"
        }
      ]
    }
  ]
}
