{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.2.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.2.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.2.0-dev.jar",
          "url": "honoka-kotlin-utils-1.2.0-dev.jar",
          "size": 85135,
          "sha512": "892bb4593e772dbeeb5bf2602a76f3f9d6a045db8ecd59390f6d33b00995ce61030cf72cce37bd001280ec952cda1976455191d62adaf1ca3bd8c6a937b2b063",
          "sha256": "9355b1788b290deb42e182254dc2c66f83f51360a3f86545f98d02c6c926e1b8",
          "sha1": "4f507022d8fda2841ddbfe50d6c8941b89f002ae",
          "md5": "deb4651f361d6eac8714f3d13b850a3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.2.0-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.2.0-dev.jar",
          "url": "honoka-kotlin-utils-1.2.0-dev.jar",
          "size": 85135,
          "sha512": "892bb4593e772dbeeb5bf2602a76f3f9d6a045db8ecd59390f6d33b00995ce61030cf72cce37bd001280ec952cda1976455191d62adaf1ca3bd8c6a937b2b063",
          "sha256": "9355b1788b290deb42e182254dc2c66f83f51360a3f86545f98d02c6c926e1b8",
          "sha1": "4f507022d8fda2841ddbfe50d6c8941b89f002ae",
          "md5": "deb4651f361d6eac8714f3d13b850a3e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.2.0-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.2.0-dev-sources.jar",
          "size": 21491,
          "sha512": "e1b81e676326871dfb8e5370804652cba3b94567d859d2d20b83190d6f66c95d392aa4c8778482389c9f634e0f9ca2b810c717a70d926111cb7967ca2bf95c7a",
          "sha256": "7de5a1b6a3c7f8a7069235ed7c91439597366b09d64d7578f7a6093d2c5f18f4",
          "sha1": "e218e655f5609f901b6c785b965e2f06e7661262",
          "md5": "940607dbc5309b7e4fee9fa09197abb9"
        },
        {
          "name": "honoka-kotlin-utils-1.2.0-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.2.0-dev-sources.jar",
          "size": 21491,
          "sha512": "e1b81e676326871dfb8e5370804652cba3b94567d859d2d20b83190d6f66c95d392aa4c8778482389c9f634e0f9ca2b810c717a70d926111cb7967ca2bf95c7a",
          "sha256": "7de5a1b6a3c7f8a7069235ed7c91439597366b09d64d7578f7a6093d2c5f18f4",
          "sha1": "e218e655f5609f901b6c785b965e2f06e7661262",
          "md5": "940607dbc5309b7e4fee9fa09197abb9"
        }
      ]
    }
  ]
}
