{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.2.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.2.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.2.0-dev.jar",
          "url": "honoka-kotlin-utils-1.2.0-dev.jar",
          "size": 89354,
          "sha512": "5e2a042183f8a39ee1fdcc208867c7f3b7803a9ef9319e3933ce3c8e75bbd30a75db92f29857f85d5a3855bb6cc988b64238192135b6e8ed930fbd54c1e902b3",
          "sha256": "286a0cab0e05aca033bf8c5e7d79e9c72bd74cf1607bfcdaaada79310e0a4063",
          "sha1": "baf9eb85f805ba5099d5edbad41ba02dc0196833",
          "md5": "13e2c0300e415a580e716bee76487524"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.2.0-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.2.0-dev.jar",
          "url": "honoka-kotlin-utils-1.2.0-dev.jar",
          "size": 89354,
          "sha512": "5e2a042183f8a39ee1fdcc208867c7f3b7803a9ef9319e3933ce3c8e75bbd30a75db92f29857f85d5a3855bb6cc988b64238192135b6e8ed930fbd54c1e902b3",
          "sha256": "286a0cab0e05aca033bf8c5e7d79e9c72bd74cf1607bfcdaaada79310e0a4063",
          "sha1": "baf9eb85f805ba5099d5edbad41ba02dc0196833",
          "md5": "13e2c0300e415a580e716bee76487524"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.2.0-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.2.0-dev-sources.jar",
          "size": 21952,
          "sha512": "da6a1d5ab70854bd8f4c35553e9f67b9ad6870f4a1a1192f9c61d3213e7e282b69da2b9bb07b9dcc414679b190a90c6f49a752e9d38fb15d56e2ce145bd2467f",
          "sha256": "c723eb62132a358081b922f07cf749ebe78d7d3b575206ac03eb2faf31f3977c",
          "sha1": "88d03e5f5fca165c1e035298cf9fd65ee3826fd7",
          "md5": "c6559d923b6834a7010027400d1b8a7c"
        },
        {
          "name": "honoka-kotlin-utils-1.2.0-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.2.0-dev-sources.jar",
          "size": 21952,
          "sha512": "da6a1d5ab70854bd8f4c35553e9f67b9ad6870f4a1a1192f9c61d3213e7e282b69da2b9bb07b9dcc414679b190a90c6f49a752e9d38fb15d56e2ce145bd2467f",
          "sha256": "c723eb62132a358081b922f07cf749ebe78d7d3b575206ac03eb2faf31f3977c",
          "sha1": "88d03e5f5fca165c1e035298cf9fd65ee3826fd7",
          "md5": "c6559d923b6834a7010027400d1b8a7c"
        }
      ]
    }
  ]
}
