{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.0.jar",
          "url": "honoka-spring-boot-starter-1.0.0.jar",
          "size": 50125,
          "sha512": "20ffe9b27fe5b2bd3e3b101d569671fd32d715882ade71c0dd460e3b0b1b831c04c01b36f230f6fc7cfeaf95cf2c62f6277e98f02fca5a4550bee3d43dcd413c",
          "sha256": "72aee4619e69dbf443638f00b8c3efefe82c06906f7c7af5f22ad35bebd1aa71",
          "sha1": "8156fb5cdfdfbed0c7619db832d2ae6bb905a8b7",
          "md5": "aa7487809ade0899214ba6151e6ce12e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.0.jar",
          "url": "honoka-spring-boot-starter-1.0.0.jar",
          "size": 50125,
          "sha512": "20ffe9b27fe5b2bd3e3b101d569671fd32d715882ade71c0dd460e3b0b1b831c04c01b36f230f6fc7cfeaf95cf2c62f6277e98f02fca5a4550bee3d43dcd413c",
          "sha256": "72aee4619e69dbf443638f00b8c3efefe82c06906f7c7af5f22ad35bebd1aa71",
          "sha1": "8156fb5cdfdfbed0c7619db832d2ae6bb905a8b7",
          "md5": "aa7487809ade0899214ba6151e6ce12e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.0-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.0-sources.jar",
          "size": 17685,
          "sha512": "093b13bb6e3f350423d32220f1961c35510726e46f6107ad20f70be349e2f3b874806a718537f1a1764bac7abade0777291bf5c7f41cc5a46c974a87b96bd174",
          "sha256": "7a844f652a8c12bdb11425dd1dd726a1d1177f680bba0e7e67f773592a60a648",
          "sha1": "4d4ce65e737f93e7af2f551bb777324a24f5af6b",
          "md5": "9f540b63e6855898840f69702d016f84"
        }
      ]
    }
  ]
}
