{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.9.jar",
          "url": "honoka-utils-1.0.9.jar",
          "size": 70924,
          "sha512": "ba2dd3e962168dd050620de6c76b4e8942c8a6b18069ef64bfde7f2e0120a6a77c2bba867ecc98e787f2c70903a3e5534c1c3043c69cbfa8332ad3c1e4767f4e",
          "sha256": "f85cecbc21e2f598181f13e56105e43b1e214a09b6a4675d40aed848a6184a4f",
          "sha1": "0c015ec2c7052c1602006f4a45fdbe0de3ee7b7e",
          "md5": "ffbb58fc957346d7cf9f75a5420cc252"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.9.jar",
          "url": "honoka-utils-1.0.9.jar",
          "size": 70924,
          "sha512": "ba2dd3e962168dd050620de6c76b4e8942c8a6b18069ef64bfde7f2e0120a6a77c2bba867ecc98e787f2c70903a3e5534c1c3043c69cbfa8332ad3c1e4767f4e",
          "sha256": "f85cecbc21e2f598181f13e56105e43b1e214a09b6a4675d40aed848a6184a4f",
          "sha1": "0c015ec2c7052c1602006f4a45fdbe0de3ee7b7e",
          "md5": "ffbb58fc957346d7cf9f75a5420cc252"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.0.9-sources.jar",
          "url": "honoka-utils-1.0.9-sources.jar",
          "size": 37835,
          "sha512": "62d2d38cf261136b3eb07f1556ce8fcaae4e293eb12c57629e7819533bb152ee8b647c150394d41be216be67cb4cdce56aeed07d70ddadca0c6279bef882c0ae",
          "sha256": "2a0fbee2a9710dfec818237113a22ba89853a2052a101d4cc1c460b2e3735da8",
          "sha1": "2554bf4f15d2880942f6a58ca0bcf8d783f65546",
          "md5": "827819b048d944685230a44e7c611699"
        }
      ]
    }
  ]
}
