{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.0.3-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.3-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.3-dev.jar",
          "size": 64727,
          "sha512": "722d3a4219c0b3b5f18e4607e518f9d39644608a102af9b1b4c9b042b4f91f0e3a87da6d94d71f6422587e9a9d440976c29b01206bcbdb31fe35364a48ee2771",
          "sha256": "305c9625d2a85c386170e87a8a46b006a196daddbfc1589960a2e17329640df6",
          "sha1": "c5bbce02ac00106d9d608cded11865ee5b488463",
          "md5": "4b24c4a6daf19890b00679a082b659f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.3-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.3-dev.jar",
          "size": 64727,
          "sha512": "722d3a4219c0b3b5f18e4607e518f9d39644608a102af9b1b4c9b042b4f91f0e3a87da6d94d71f6422587e9a9d440976c29b01206bcbdb31fe35364a48ee2771",
          "sha256": "305c9625d2a85c386170e87a8a46b006a196daddbfc1589960a2e17329640df6",
          "sha1": "c5bbce02ac00106d9d608cded11865ee5b488463",
          "md5": "4b24c4a6daf19890b00679a082b659f3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.3-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.3-dev-sources.jar",
          "size": 19437,
          "sha512": "dd791c8c7f2056a1785349e66795a8c66482048f7447b3e2e22f9ed6d3cc3b883731a3da1610c074ad40acc2e7d2d58e4078f09ea3f29ae6e969b06ca74eeb1a",
          "sha256": "6e363a17a33d67ffe48602bbf2a3197b64686487631ba4512d85ffe78bb0ee2f",
          "sha1": "5815cc45155edfecfb30a23cd4f672a6c4db0ffa",
          "md5": "7cb0b9dd9353085c8231356974fe9157"
        }
      ]
    }
  ]
}
