{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.0.3-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.3-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.3-dev.jar",
          "size": 65368,
          "sha512": "55779ea1de70f0fe15d7cf6abb0a67953c4b1f524044929ca344c118550663ca46f3f1bf584b3272ac5c315bd9eec0a8d62ec125ba7b3667565e730a305d21e4",
          "sha256": "dcf02b9c5eb230a11ee2b5adbe5cc60db512d71bce98ba20fb9da583267e1d06",
          "sha1": "d3dce543203c76980b96fa96f609d90bd0a4445e",
          "md5": "699c35196d72e0ec69cacf199abbd9d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.3-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.3-dev.jar",
          "size": 65368,
          "sha512": "55779ea1de70f0fe15d7cf6abb0a67953c4b1f524044929ca344c118550663ca46f3f1bf584b3272ac5c315bd9eec0a8d62ec125ba7b3667565e730a305d21e4",
          "sha256": "dcf02b9c5eb230a11ee2b5adbe5cc60db512d71bce98ba20fb9da583267e1d06",
          "sha1": "d3dce543203c76980b96fa96f609d90bd0a4445e",
          "md5": "699c35196d72e0ec69cacf199abbd9d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.3-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.3-dev-sources.jar",
          "size": 19433,
          "sha512": "d964f400f881adaaefe392ee725169a2a15acaace661e994d02affedc284b6c1d7b16c5bc4ff014b63353929c45a8f72e07df7884d260b6c69d532eb039f7dad",
          "sha256": "f896ccfb0d34e94f5da21516df7a7bc5c1c4a4f67041c1468ea526d5e7a25693",
          "sha1": "5cdde594e79c57a858c6c6befc8ad738678ea607",
          "md5": "d0dc01505f33a7a320d891c5ee19cdc8"
        }
      ]
    }
  ]
}
