{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.0.3-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.3-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.3-dev.jar",
          "size": 64401,
          "sha512": "bd562acda9f27151bf1109ef69c492be066864cca2e91795a6dd83cae0313a590f33f018c87a7ac07bd1353a1d4b45739b3a09769fdfe87b0f3147c865f8ab4e",
          "sha256": "4f95df6a07fab2dacf36bb2a6cabc38437b28042b3cdbcb071109411ef5f5085",
          "sha1": "ff9b13f29ced925277b13b6e8408b976365a7e38",
          "md5": "e339cef79115b262d0700e1b4b6179c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.3-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.3-dev.jar",
          "size": 64401,
          "sha512": "bd562acda9f27151bf1109ef69c492be066864cca2e91795a6dd83cae0313a590f33f018c87a7ac07bd1353a1d4b45739b3a09769fdfe87b0f3147c865f8ab4e",
          "sha256": "4f95df6a07fab2dacf36bb2a6cabc38437b28042b3cdbcb071109411ef5f5085",
          "sha1": "ff9b13f29ced925277b13b6e8408b976365a7e38",
          "md5": "e339cef79115b262d0700e1b4b6179c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.3-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.3-dev-sources.jar",
          "size": 19407,
          "sha512": "844483a186f0036b47aa62bd54d82f85ecb48c1c7b220a236e1c5a9f5f4fed27554b2e7ba189c70f682555962bed23a579bc16cfa488b78013b95d9b853bfee8",
          "sha256": "85d49f13a41b5f57277348153fa5faedb7cfa4b02bce09c3eb0d5d1bcc0936d2",
          "sha1": "afa57e04b59c995ddbae84803c990d9222c7f878",
          "md5": "9f9ccff3b67bdfaa3c1c84155ece5760"
        }
      ]
    }
  ]
}
