{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender",
    "module": "lavender-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lavender-api-1.0.0.jar",
          "url": "lavender-api-1.0.0.jar",
          "size": 23329,
          "sha512": "49b58ee6dbf9e23c4a24881e7d2b76f608ac79ea58ec39ea1cd318eda7730c7ca45e346d64fc1e899ed42b41fb2d684c09b086a255ea863dc094cdc13f3ceb56",
          "sha256": "0be2b273712faf2ccc41d0c41be03e6a6299758c14125d9dc873751aea83a2ac",
          "sha1": "32fa1dc2d85b7f2009dc97840cfb9447df317f84",
          "md5": "9a8460a3695ab7c40c7bc155b2037594"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "lavender-api-1.0.0.jar",
          "url": "lavender-api-1.0.0.jar",
          "size": 23329,
          "sha512": "49b58ee6dbf9e23c4a24881e7d2b76f608ac79ea58ec39ea1cd318eda7730c7ca45e346d64fc1e899ed42b41fb2d684c09b086a255ea863dc094cdc13f3ceb56",
          "sha256": "0be2b273712faf2ccc41d0c41be03e6a6299758c14125d9dc873751aea83a2ac",
          "sha1": "32fa1dc2d85b7f2009dc97840cfb9447df317f84",
          "md5": "9a8460a3695ab7c40c7bc155b2037594"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavender-api-1.0.0-sources.jar",
          "url": "lavender-api-1.0.0-sources.jar",
          "size": 2929,
          "sha512": "6fa0554e3c7c4403338fe8cd406eee2846796525d770885fec8e5d0f223992ea0b1a0d6207be7456dfb22e76ae7cf867eed64ffbd3a99c93223a1dbfa35ef2a3",
          "sha256": "7a9f3828da8a6c87bc074b7d11608d452a7756be5d4539c27fb7612fafcd7ca7",
          "sha1": "173ec4f9158e9fd23e5575ce23300c703ce28c42",
          "md5": "57f00f4d2115dbdd5f46020ede494c7a"
        }
      ]
    }
  ]
}
