{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.2.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.2.0-dev.jar",
          "url": "honoka-utils-1.2.0-dev.jar",
          "size": 63589,
          "sha512": "273b17230d04d426dac9e94ce585003a88520dd34cfa81647d5eae22fcbeb7153fa5625937992f1a2db2e73f8872ba68e3e1846afc520aa93cc76b5e6cd019b7",
          "sha256": "c33d7b810614e74647427156d88b3dadffd84d36a15c837a36fa52ced99eeb55",
          "sha1": "bf8faf27a23d25ada8e96003b12766308af9ff6a",
          "md5": "4deb713c4978a79b742abfeb6ba81d7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.80"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.2.0-dev.jar",
          "url": "honoka-utils-1.2.0-dev.jar",
          "size": 63589,
          "sha512": "273b17230d04d426dac9e94ce585003a88520dd34cfa81647d5eae22fcbeb7153fa5625937992f1a2db2e73f8872ba68e3e1846afc520aa93cc76b5e6cd019b7",
          "sha256": "c33d7b810614e74647427156d88b3dadffd84d36a15c837a36fa52ced99eeb55",
          "sha1": "bf8faf27a23d25ada8e96003b12766308af9ff6a",
          "md5": "4deb713c4978a79b742abfeb6ba81d7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.2.0-dev-sources.jar",
          "url": "honoka-utils-1.2.0-dev-sources.jar",
          "size": 35308,
          "sha512": "b692d8641593f0454f12c27c5201440e308c0cf634aa5cca6a421457198a65f2ef7d75de49de9136a359a9c36918951ec005760288431b2b249febda9e09ec62",
          "sha256": "7367894beda212769df49504329f25fc3d0871f790ce02be6ac8c5be0520ba70",
          "sha1": "9aecaa583ad0d0d1d40104ffd5bcbed4102948f2",
          "md5": "ea605d2bbf1cd03df61314f39bbaa425"
        }
      ]
    }
  ]
}
