{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.2.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.2.0-dev.jar",
          "url": "honoka-utils-1.2.0-dev.jar",
          "size": 64362,
          "sha512": "7eaf658a50c55e79c7971bc462511a0cb357d96f007179227ca5d86b2aa0d31135b114dcf7f00dbbba596eceeec9abda516f63b280516b37d1cc6d7c74ac1a8a",
          "sha256": "e8c016dacbc49cc69573adea882272d80a95fad03bf1c194541261d662ea6bfe",
          "sha1": "3cd96d388f5930ffa093e24bf9e3d3609746bb2a",
          "md5": "4e897d60162235f770d449b01802d93f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.80"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.2.0-dev.jar",
          "url": "honoka-utils-1.2.0-dev.jar",
          "size": 64362,
          "sha512": "7eaf658a50c55e79c7971bc462511a0cb357d96f007179227ca5d86b2aa0d31135b114dcf7f00dbbba596eceeec9abda516f63b280516b37d1cc6d7c74ac1a8a",
          "sha256": "e8c016dacbc49cc69573adea882272d80a95fad03bf1c194541261d662ea6bfe",
          "sha1": "3cd96d388f5930ffa093e24bf9e3d3609746bb2a",
          "md5": "4e897d60162235f770d449b01802d93f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.2.0-dev-sources.jar",
          "url": "honoka-utils-1.2.0-dev-sources.jar",
          "size": 35780,
          "sha512": "877a7becb02a5c2888f9e6555dd8150e98292745bd1d92cb7987d952d320b08b581b6c5de886c22117d0f4459ba5556cb28614c725d06862b1b0a68e5692fab0",
          "sha256": "5959504ac7cf695ece193dd19a37059258c94129c97645dd4bab9a4ee00e61e1",
          "sha1": "6e0bd167cc55984fea1050a2ed117d3cd83174f2",
          "md5": "9b3f7daed2e333d492848f25e5a35eb1"
        }
      ]
    }
  ]
}
