{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.2.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.2.0-dev.jar",
          "url": "honoka-utils-1.2.0-dev.jar",
          "size": 70586,
          "sha512": "1a17a8ebd91bef67f73d01cd0e53fd94298761167fe48ecc58ef140f410905dd8897d8e69969f7552f3015b1ef1bb44c2d8ecc681b816e1d0b27d3e24dd4186c",
          "sha256": "b4b2f0e2044cb2792c758533b9f7dd0bcfcbe248239ab75b4d3222ee3367ddc8",
          "sha1": "05a6159d4c4c1796107f24b0905b94598a74acac",
          "md5": "dac64baa974be2ab52284fbd4a7f5132"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.80"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.2.0-dev.jar",
          "url": "honoka-utils-1.2.0-dev.jar",
          "size": 70586,
          "sha512": "1a17a8ebd91bef67f73d01cd0e53fd94298761167fe48ecc58ef140f410905dd8897d8e69969f7552f3015b1ef1bb44c2d8ecc681b816e1d0b27d3e24dd4186c",
          "sha256": "b4b2f0e2044cb2792c758533b9f7dd0bcfcbe248239ab75b4d3222ee3367ddc8",
          "sha1": "05a6159d4c4c1796107f24b0905b94598a74acac",
          "md5": "dac64baa974be2ab52284fbd4a7f5132"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.2.0-dev-sources.jar",
          "url": "honoka-utils-1.2.0-dev-sources.jar",
          "size": 38145,
          "sha512": "9cf8857bf82e4a95e371dc8b8b60454d3690d32550ae768d852ae54c26c14fda011038d8f596e94a828b07afafbbd2e4d8dc8fad76ceda908747d4c559c302d3",
          "sha256": "39cca769627c2b0c2fa9745a03ab2674c398de6d3a6d5fff4d57f6460544e8b1",
          "sha1": "7bf776eedd1b2b0b0f7e3b7f54d829fa34480635",
          "md5": "e35902e16c3e9a09cfbc339f3dd107b6"
        }
      ]
    }
  ]
}
