{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-basic-plugin",
    "version": "1.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.0-dev.jar",
          "url": "honoka-basic-plugin-1.0.0-dev.jar",
          "size": 25419,
          "sha512": "a0e9491199bbd082c073a5a9e8468960310ff0a0f9da31b99eee9240a2366c1f4f1892bc068259efd6ab25f19db48b9c801eab0bee5c4e6ee294a41d0a271b5a",
          "sha256": "f442b95115b241952667636aa3a3a4f4e746e51233f91cee020d632f8184caca",
          "sha1": "69ec6188ae5ec8e7ace1a91de6dc37402b14f578",
          "md5": "4b4f47a71b0ad7046fedca3898a3f184"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.0-dev.jar",
          "url": "honoka-basic-plugin-1.0.0-dev.jar",
          "size": 25419,
          "sha512": "a0e9491199bbd082c073a5a9e8468960310ff0a0f9da31b99eee9240a2366c1f4f1892bc068259efd6ab25f19db48b9c801eab0bee5c4e6ee294a41d0a271b5a",
          "sha256": "f442b95115b241952667636aa3a3a4f4e746e51233f91cee020d632f8184caca",
          "sha1": "69ec6188ae5ec8e7ace1a91de6dc37402b14f578",
          "md5": "4b4f47a71b0ad7046fedca3898a3f184"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.0-dev-sources.jar",
          "url": "honoka-basic-plugin-1.0.0-dev-sources.jar",
          "size": 3909,
          "sha512": "4cbceb07c52c7e14aaba65155f32aa8931d779c368808c9479bcd1adccae47425701d1ee6abf29f121ff20c1e981e9b378525a445bccbcc98b39fe4edbc0eae2",
          "sha256": "0b08c2fce88fe651ac865a367ba6e8d98751c263c33daa6d07bf4a47b18f8e9c",
          "sha1": "8ab3e451befd0104682c86d54fab74c2b494b7aa",
          "md5": "66b3b220ead9ea60dea12bb480146f82"
        }
      ]
    }
  ]
}
