{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-basic-plugin",
    "version": "1.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.0-dev.jar",
          "url": "honoka-basic-plugin-1.0.0-dev.jar",
          "size": 26290,
          "sha512": "3d917903056ef085cff6860a97b5547a0d2d0a044ceae2bf6e4a855678a34e92725c4cf0ca8046754cacd9376a1be8afd38d3037ab068ef332bab5b260cf3df3",
          "sha256": "820603535b316b0a43013c183188cfe9cf2bbf780a706e7e455d84395baf4677",
          "sha1": "9f8a086512d4a161f4799b873973b6ce3793b118",
          "md5": "f22fdfa3e5e0809c3a9b2cb372b9561b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.0-dev.jar",
          "url": "honoka-basic-plugin-1.0.0-dev.jar",
          "size": 26290,
          "sha512": "3d917903056ef085cff6860a97b5547a0d2d0a044ceae2bf6e4a855678a34e92725c4cf0ca8046754cacd9376a1be8afd38d3037ab068ef332bab5b260cf3df3",
          "sha256": "820603535b316b0a43013c183188cfe9cf2bbf780a706e7e455d84395baf4677",
          "sha1": "9f8a086512d4a161f4799b873973b6ce3793b118",
          "md5": "f22fdfa3e5e0809c3a9b2cb372b9561b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.0-dev-sources.jar",
          "url": "honoka-basic-plugin-1.0.0-dev-sources.jar",
          "size": 4005,
          "sha512": "3876a75f88a417645336c1d93081dee6084a26897f24c166ec7045939667d843f2c0fe015618c0181fce928dc92f39d0d5b5d57e03c3653752f5a11b1348e16f",
          "sha256": "8842148bcb6ef3f6a057dba0a0f472a7ee9122b3c69d811accaedb86ae6abe32",
          "sha1": "517addbe01ecb8f6f06d2d1235ded96bcb3e5f92",
          "md5": "69025e40271c0e82416514ff3d0e640a"
        }
      ]
    }
  ]
}
