{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle",
    "module": "honoka-gradle-utils",
    "version": "1.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.1-dev.jar",
          "url": "honoka-gradle-utils-1.0.1-dev.jar",
          "size": 27016,
          "sha512": "d9572b49a4cea7e77efe97c960a7763d439650221dfbb374e776c0fb9cf01ca466bf0fad446dd064c70e17a4401999dc7a9b554c13f36a76a093b39c3902dd61",
          "sha256": "5ca49a4f93780489adbc15db6b6b86e82617df5d46cef00d68bcc45a352cc054",
          "sha1": "85e49d7d15275dd2e7b6f592a6e08605b147fd87",
          "md5": "03474d68e32ede69e418759f53b4da88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.1-dev.jar",
          "url": "honoka-gradle-utils-1.0.1-dev.jar",
          "size": 27016,
          "sha512": "d9572b49a4cea7e77efe97c960a7763d439650221dfbb374e776c0fb9cf01ca466bf0fad446dd064c70e17a4401999dc7a9b554c13f36a76a093b39c3902dd61",
          "sha256": "5ca49a4f93780489adbc15db6b6b86e82617df5d46cef00d68bcc45a352cc054",
          "sha1": "85e49d7d15275dd2e7b6f592a6e08605b147fd87",
          "md5": "03474d68e32ede69e418759f53b4da88"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.1-dev-sources.jar",
          "url": "honoka-gradle-utils-1.0.1-dev-sources.jar",
          "size": 4893,
          "sha512": "7e40f36276548461986f3b83246ee6602fe7ccf195444a1b255c193ff64cc4a95c9ff86f4025d80005f3bfba662b3f366e4883cae47b54b723f050f5171d7577",
          "sha256": "94fa8fdf42abbda020e59d851621d166e5c2d6e3f09d5dd494e89dec6f6e016f",
          "sha1": "9e947800a074b4a5a7bda778d5015d4c9f683b63",
          "md5": "9b8a1b5ba2c855ba66bc29c71992950e"
        }
      ]
    }
  ]
}
