{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle",
    "module": "honoka-gradle-utils",
    "version": "1.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.1-dev.jar",
          "url": "honoka-gradle-utils-1.0.1-dev.jar",
          "size": 27016,
          "sha512": "104b2992a42340c49d41d5be8d4e90018cafe84810615c4b46f8edefcc01eab607ce870e9fca0bdd9bf679bcb86dee3d3ca6c0d2d55e56ecd64e7b171838f491",
          "sha256": "bca58e77e7db5a3a8478d8d1a2428a74fe9e4c8bd136e31365a53e996b51f31c",
          "sha1": "ea118225708db3c7e5d6a3ccc3ab26adab4dff1d",
          "md5": "410686b8e6a1a9314d733cb46f612126"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.1-dev.jar",
          "url": "honoka-gradle-utils-1.0.1-dev.jar",
          "size": 27016,
          "sha512": "104b2992a42340c49d41d5be8d4e90018cafe84810615c4b46f8edefcc01eab607ce870e9fca0bdd9bf679bcb86dee3d3ca6c0d2d55e56ecd64e7b171838f491",
          "sha256": "bca58e77e7db5a3a8478d8d1a2428a74fe9e4c8bd136e31365a53e996b51f31c",
          "sha1": "ea118225708db3c7e5d6a3ccc3ab26adab4dff1d",
          "md5": "410686b8e6a1a9314d733cb46f612126"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.1-dev-sources.jar",
          "url": "honoka-gradle-utils-1.0.1-dev-sources.jar",
          "size": 4893,
          "sha512": "3bd6bc3e628db02d7b14e20a05969cf793dcad4fa145036079af5fa3f48fc7913b7abb1582a8d3645663e1070fe424caaaa52c23f07f23d729da1772ca57be1d",
          "sha256": "940094354dd5f9ed509fe4388d2833421dfc27f9dd674b6e803f4fdd36733236",
          "sha1": "6b0d852a20a4ff36898457f6c0f88fb4cda036b8",
          "md5": "d36bfceef0850a00bc4cf1a59da22aa9"
        }
      ]
    }
  ]
}
