{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.0.jar",
          "url": "qqrobot-framework-api-2.0.0.jar",
          "size": 8883,
          "sha512": "56a5156aeb707cd9d543ab7dcd8f755a1787ceadf20af475eba657afd78a9fe91549678e120a93f72069b2565a98b1440ea8e0b9080ea672dd0c9b7d028b71a0",
          "sha256": "5adf8d18ecf0d33936c76037335e02e93c815f91904800d8e108aa1442ef40a8",
          "sha1": "7d0dc47de9b39b99e56369b8493d333ffaa70916",
          "md5": "2282dfc13ea07984faaad48259c4bb3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.0.jar",
          "url": "qqrobot-framework-api-2.0.0.jar",
          "size": 8883,
          "sha512": "56a5156aeb707cd9d543ab7dcd8f755a1787ceadf20af475eba657afd78a9fe91549678e120a93f72069b2565a98b1440ea8e0b9080ea672dd0c9b7d028b71a0",
          "sha256": "5adf8d18ecf0d33936c76037335e02e93c815f91904800d8e108aa1442ef40a8",
          "sha1": "7d0dc47de9b39b99e56369b8493d333ffaa70916",
          "md5": "2282dfc13ea07984faaad48259c4bb3b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.0-sources.jar",
          "url": "qqrobot-framework-api-2.0.0-sources.jar",
          "size": 4934,
          "sha512": "70b6b3a5b8bedc542da7ebae8ba031dd1d7975f0ed71945cdc482d8f45f9b667c92436d3dd61bced269cda921a74a9236eb0aad699585b3775341e1efc854557",
          "sha256": "4e5757d876cbb945b22661bda58760b8035d3346bb22169c2de4f39cba2fecf9",
          "sha1": "8b25ef6f006c70c41d523a4f5d3a7558097c8477",
          "md5": "04795bf7b63eda298c4117527303471e"
        }
      ]
    }
  ]
}
