{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.7.jar",
          "url": "honoka-utils-1.0.7.jar",
          "size": 63919,
          "sha512": "c906e88c06313627fba12d5efa3f031f3eafd08d46542ac9ba40b7e0557a234e396fd428f8e4ef0981ec75980c32f08403bc31627285fd507e32d271440ccbe2",
          "sha256": "0109c4ec87016580996ac98763cf7abfe839d969d093ec34e9afd6d3ec6dd739",
          "sha1": "64911fb12c28fe9579725d9a4d490195c8c42a54",
          "md5": "8d8cd2387014f5d408e087a550574529"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.7.jar",
          "url": "honoka-utils-1.0.7.jar",
          "size": 63919,
          "sha512": "c906e88c06313627fba12d5efa3f031f3eafd08d46542ac9ba40b7e0557a234e396fd428f8e4ef0981ec75980c32f08403bc31627285fd507e32d271440ccbe2",
          "sha256": "0109c4ec87016580996ac98763cf7abfe839d969d093ec34e9afd6d3ec6dd739",
          "sha1": "64911fb12c28fe9579725d9a4d490195c8c42a54",
          "md5": "8d8cd2387014f5d408e087a550574529"
        }
      ]
    }
  ]
}
