{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.7.jar",
          "url": "honoka-utils-1.0.7.jar",
          "size": 63915,
          "sha512": "d7aff68a9cc9fc3ce0ee90e2ca9b020b5411e23e259889b323507889a0d1348b99c92f210ce8e600b94a3307a58c897b1c0d94fcaaa2981c5b6acda7f1fabe84",
          "sha256": "4a31e304d1183458b33bf9170fd9e239ed4f2ebc2774d49edeb211a45e28d390",
          "sha1": "0c3b03a43deefd4f1170b51e12d9f9ec8cadab7b",
          "md5": "7dddd5e695f59ac4e6b0f6345d7db36e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.7.jar",
          "url": "honoka-utils-1.0.7.jar",
          "size": 63915,
          "sha512": "d7aff68a9cc9fc3ce0ee90e2ca9b020b5411e23e259889b323507889a0d1348b99c92f210ce8e600b94a3307a58c897b1c0d94fcaaa2981c5b6acda7f1fabe84",
          "sha256": "4a31e304d1183458b33bf9170fd9e239ed4f2ebc2774d49edeb211a45e28d390",
          "sha1": "0c3b03a43deefd4f1170b51e12d9f9ec8cadab7b",
          "md5": "7dddd5e695f59ac4e6b0f6345d7db36e"
        }
      ]
    }
  ]
}
