{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.7.jar",
          "url": "honoka-utils-1.0.7.jar",
          "size": 64570,
          "sha512": "7bd0527cbbbf13a97edcc9046ecce303970e6da41fb6769695d15bb9777fd1d0a3e8c6abebb531fbdf6d34ce9f8181b439e1a14825649b251dc06994c3475475",
          "sha256": "9302409b49506a97dd63502f60bfaf35fc62d9a51526ad1dc5265c45d26aadef",
          "sha1": "3ad27d3a110afcbc7c0b8316fb9bcd463c11a497",
          "md5": "8f80212c7c6284c6227b995168dac77c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.7.jar",
          "url": "honoka-utils-1.0.7.jar",
          "size": 64570,
          "sha512": "7bd0527cbbbf13a97edcc9046ecce303970e6da41fb6769695d15bb9777fd1d0a3e8c6abebb531fbdf6d34ce9f8181b439e1a14825649b251dc06994c3475475",
          "sha256": "9302409b49506a97dd63502f60bfaf35fc62d9a51526ad1dc5265c45d26aadef",
          "sha1": "3ad27d3a110afcbc7c0b8316fb9bcd463c11a497",
          "md5": "8f80212c7c6284c6227b995168dac77c"
        }
      ]
    }
  ]
}
