{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "2.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-2.0.1-dev.jar",
          "url": "honoka-utils-2.0.1-dev.jar",
          "size": 73399,
          "sha512": "b1b15107216686d5f233bc5760481b9a44ccc145699ca5e5ffd570f2c8f284e3ad67944f50eaf4272742f3a3f770bd8fd52cd0e894eb00b269d3af9dc32b8cd8",
          "sha256": "d62bd4c6de117f97fe92b6eff19ae2c52d793ccbb8ab14b528a654e2b881576f",
          "sha1": "f22c0d7c5c50cb18fb9b81097be2e14e726eed49",
          "md5": "ea69b63f02db8d243d8e0160bfc9f375"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-2.0.1-dev.jar",
          "url": "honoka-utils-2.0.1-dev.jar",
          "size": 73399,
          "sha512": "b1b15107216686d5f233bc5760481b9a44ccc145699ca5e5ffd570f2c8f284e3ad67944f50eaf4272742f3a3f770bd8fd52cd0e894eb00b269d3af9dc32b8cd8",
          "sha256": "d62bd4c6de117f97fe92b6eff19ae2c52d793ccbb8ab14b528a654e2b881576f",
          "sha1": "f22c0d7c5c50cb18fb9b81097be2e14e726eed49",
          "md5": "ea69b63f02db8d243d8e0160bfc9f375"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-2.0.1-dev-sources.jar",
          "url": "honoka-utils-2.0.1-dev-sources.jar",
          "size": 38837,
          "sha512": "761f65e5c150d92b98de3d5e5f125da032a01c40e5aaf4396072df98a2b0da492d3ff4e6d0204a5e4bd69cc6932c26f25289ad2f5db0cc89dd4eb19b7b90ba21",
          "sha256": "3ef57a04f6055a1d3f4f7bd9ebb0b8080f971c769a3543f9ea28e9a79ee8dbad",
          "sha1": "35913d8d060f5f1246ba902e72a24771e62b1f11",
          "md5": "c0d89c584268d0906e88f64a5f3fc2a0"
        }
      ]
    }
  ]
}
