{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "2.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-2.0.1-dev.jar",
          "url": "honoka-utils-2.0.1-dev.jar",
          "size": 73399,
          "sha512": "e872147bf76862c5aec698ddba032443ffd5512ef1faf1719b67426d4031ff01da184a0daad20afa8a9d32f1c2dd928c41e7df0c3ca9974816196846afc7ca34",
          "sha256": "6ad21b1ec71c85317452ccca8d06321e5fab1d881132dc2d9379384c245deaf7",
          "sha1": "022c60f92ce5cdbb8b780fc5f1a1bf8adc618019",
          "md5": "35bc8c18370b1ed708f4440ae1a15bff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-2.0.1-dev.jar",
          "url": "honoka-utils-2.0.1-dev.jar",
          "size": 73399,
          "sha512": "e872147bf76862c5aec698ddba032443ffd5512ef1faf1719b67426d4031ff01da184a0daad20afa8a9d32f1c2dd928c41e7df0c3ca9974816196846afc7ca34",
          "sha256": "6ad21b1ec71c85317452ccca8d06321e5fab1d881132dc2d9379384c245deaf7",
          "sha1": "022c60f92ce5cdbb8b780fc5f1a1bf8adc618019",
          "md5": "35bc8c18370b1ed708f4440ae1a15bff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-2.0.1-dev-sources.jar",
          "url": "honoka-utils-2.0.1-dev-sources.jar",
          "size": 38837,
          "sha512": "9663c3ba66424f7fbe10fde53de45b9b1deac1e7ef58062731dd1ff5e20a74861594dfbb477c361f51e2843361fad059f4188199edcdb46179b18b5c4f70ee24",
          "sha256": "a0316a5653701f24cb24d23c26d672e6a72afc8557f5c9e7644542fd10c07a79",
          "sha1": "6ba853556e34d424a30582da450b4259ecdd490e",
          "md5": "0ed9c9f3018817a51681ba47788ceea3"
        }
      ]
    }
  ]
}
