{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.1.3-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.3-dev.jar",
          "url": "honoka-utils-1.1.3-dev.jar",
          "size": 82502,
          "sha512": "480aa42bb342b26322798aebfd40ce852fa8ff7a020f10b0908867a0fb5c8801203655acd8ab61a1b7a055d6146e95a500797e1c97d8338f8104b3f29a889c55",
          "sha256": "7a9071d139419c0866fe86140a30c8a5c87becc8f5f0bc3eda5bb6e6359b5fb2",
          "sha1": "aed69054f2bd6a89dc601bcfab2bd20b01af647a",
          "md5": "1cac454b1fe0fdb482830eac46181979"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.3-dev.jar",
          "url": "honoka-utils-1.1.3-dev.jar",
          "size": 82502,
          "sha512": "480aa42bb342b26322798aebfd40ce852fa8ff7a020f10b0908867a0fb5c8801203655acd8ab61a1b7a055d6146e95a500797e1c97d8338f8104b3f29a889c55",
          "sha256": "7a9071d139419c0866fe86140a30c8a5c87becc8f5f0bc3eda5bb6e6359b5fb2",
          "sha1": "aed69054f2bd6a89dc601bcfab2bd20b01af647a",
          "md5": "1cac454b1fe0fdb482830eac46181979"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.1.3-dev-sources.jar",
          "url": "honoka-utils-1.1.3-dev-sources.jar",
          "size": 43471,
          "sha512": "09c34c196af8023accdcffac26a782c58948ea157000fc428661c876a6fe2dc9fa8964387ba64cd94a6038ccc3c071a79b49308a8d975129b5588dc82466a099",
          "sha256": "87cbfe654b44db301e148bcafd63837fb646871bee586d144e941e5db014f404",
          "sha1": "03d290228e1b947bad1a0631bae0da07fba88a48",
          "md5": "c04f4ae80bf1c660aa56cd9f760fc00d"
        }
      ]
    }
  ]
}
