{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.1.3-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.3-dev.jar",
          "url": "honoka-utils-1.1.3-dev.jar",
          "size": 82592,
          "sha512": "7945f020d08cb1e7cb5c0e56718185ba818e775e2fb3061b7e629a8fcad8f60e355cb1968109981fc14a73aa8da806a7409a4938d5e8386eb84b2cb9c1b5e8ab",
          "sha256": "a1f79155a7743fbc7a20eeb4b1b7d49488c118ed5fa2237b41e22f6b51a00f07",
          "sha1": "531aecea4d4574e13d53755406e236f397ad3037",
          "md5": "8126acdf5bfd855644ec939f48a500ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.3-dev.jar",
          "url": "honoka-utils-1.1.3-dev.jar",
          "size": 82592,
          "sha512": "7945f020d08cb1e7cb5c0e56718185ba818e775e2fb3061b7e629a8fcad8f60e355cb1968109981fc14a73aa8da806a7409a4938d5e8386eb84b2cb9c1b5e8ab",
          "sha256": "a1f79155a7743fbc7a20eeb4b1b7d49488c118ed5fa2237b41e22f6b51a00f07",
          "sha1": "531aecea4d4574e13d53755406e236f397ad3037",
          "md5": "8126acdf5bfd855644ec939f48a500ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.1.3-dev-sources.jar",
          "url": "honoka-utils-1.1.3-dev-sources.jar",
          "size": 43480,
          "sha512": "1e61e0ece58aef555acb548712a08c29c2c1f0305c70c810ae4a6b98c90b4d5f40f4f0fe87ceacf6aa5563007f175b9b1fd5b749fd467700257389cc54faf2ce",
          "sha256": "3b0bf5f826a674129f6ce8fb09d10422cf6469848417e8b0de1bef948eba0255",
          "sha1": "7ecb113674b3e8599606f1b68dd7da990450dd55",
          "md5": "39564852804317354787cbd8dce20d4e"
        }
      ]
    }
  ]
}
