{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.1.3-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.3-dev.jar",
          "url": "honoka-utils-1.1.3-dev.jar",
          "size": 82398,
          "sha512": "edb0e8501a002089044bf071145b65f480baf3fddd9650c34ea0c01c7ae1717b569799b63374b3d279b4e4c3627b81e3ec1d5083e25e1cf68be65d0a1917a4d0",
          "sha256": "773174fff759c4f6dee358bfc371366ee60d61e05b39ea3417a6bfc8bc5f36f4",
          "sha1": "2d7b09c5f23b7c14fa0aef9f986d7bdd729794e9",
          "md5": "9097dc3d13b348792ff140b7874c0053"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.3-dev.jar",
          "url": "honoka-utils-1.1.3-dev.jar",
          "size": 82398,
          "sha512": "edb0e8501a002089044bf071145b65f480baf3fddd9650c34ea0c01c7ae1717b569799b63374b3d279b4e4c3627b81e3ec1d5083e25e1cf68be65d0a1917a4d0",
          "sha256": "773174fff759c4f6dee358bfc371366ee60d61e05b39ea3417a6bfc8bc5f36f4",
          "sha1": "2d7b09c5f23b7c14fa0aef9f986d7bdd729794e9",
          "md5": "9097dc3d13b348792ff140b7874c0053"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.1.3-dev-sources.jar",
          "url": "honoka-utils-1.1.3-dev-sources.jar",
          "size": 43399,
          "sha512": "602e878a7c9413f8c016272db7dc96db46b2102b0ede2d805a03a0d953bdbcc15d67f7f32d0665655a801549cd97fa7f881444e01f40c0b5e570639d4ab3b432",
          "sha256": "c3e07f70f5a811e927a4a230a2742e51fd5957faf112985287964dc3bcd19093",
          "sha1": "cdeb47db9f39ed06c7da9a191ff87ccf6867489f",
          "md5": "cb61e2d258b47604654167ebc424b9b7"
        }
      ]
    }
  ]
}
