{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "2.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.0.1-dev"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.1-dev.jar",
          "url": "qqrobot-spring-boot-starter-2.0.1-dev.jar",
          "size": 1222054,
          "sha512": "647a0c341162e1892c15b845b1af35dd7361b268981a01ecf51c1f6fd10c50a437cf86e8ecb6c45c77379b2114a1f23320f392b21e9dcf5ab0fa8941d256093f",
          "sha256": "b45eb9ac7dd39dc91fdecc267ef565cfa30d161148a4d704b2fd6b26ce6e918a",
          "sha1": "bc6b101045ef4e20b7bc6b7909d3163ed307273b",
          "md5": "00da6244c13f2821aa9267ad74123668"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.0.1-dev"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.1-dev.jar",
          "url": "qqrobot-spring-boot-starter-2.0.1-dev.jar",
          "size": 1222054,
          "sha512": "647a0c341162e1892c15b845b1af35dd7361b268981a01ecf51c1f6fd10c50a437cf86e8ecb6c45c77379b2114a1f23320f392b21e9dcf5ab0fa8941d256093f",
          "sha256": "b45eb9ac7dd39dc91fdecc267ef565cfa30d161148a4d704b2fd6b26ce6e918a",
          "sha1": "bc6b101045ef4e20b7bc6b7909d3163ed307273b",
          "md5": "00da6244c13f2821aa9267ad74123668"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.1-dev-sources.jar",
          "url": "qqrobot-spring-boot-starter-2.0.1-dev-sources.jar",
          "size": 1144707,
          "sha512": "7ec7bb53f801fcfc26ff374efd144cc4ecb2d798638e0ae68bb257c666bd28e3fc8c87e489c2eff57569dc6a9e04ecee1a906f49c56cb0f321e03554b6808087",
          "sha256": "234180d5b242664bee05debd69ee14cf7c47f42113a04fd1cad456567ecb6170",
          "sha1": "2494e93bd2b1b82a8d4679c8dc618432a670397b",
          "md5": "9888b41dc03ef4b38484711492f0ae1c"
        }
      ]
    }
  ]
}
