{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "2.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.1-dev.jar",
          "url": "qqrobot-spring-boot-starter-2.0.1-dev.jar",
          "size": 1219790,
          "sha512": "5f4d7b520cdee1d3d965ddbd89f3ff0e26156dc10667bdd259843a79ced8636b7aa24796f3f4121a7bbc85eb5ba6f93b3bda8550e795e972381a5ca1b3517535",
          "sha256": "4ebb30793a726ff29e71bf523f0e75747556336508157259b3c3896f834b33c9",
          "sha1": "78215977cabd4939def6e7e3ac556aac3416e27b",
          "md5": "730aa0089292527233b74ab5f66e6e99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.0.1-dev"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "net.mamoe",
          "module": "mirai-core-jvm",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "net.mamoe",
          "module": "mirai-console-compiler-annotations-jvm",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.1-dev.jar",
          "url": "qqrobot-spring-boot-starter-2.0.1-dev.jar",
          "size": 1219790,
          "sha512": "5f4d7b520cdee1d3d965ddbd89f3ff0e26156dc10667bdd259843a79ced8636b7aa24796f3f4121a7bbc85eb5ba6f93b3bda8550e795e972381a5ca1b3517535",
          "sha256": "4ebb30793a726ff29e71bf523f0e75747556336508157259b3c3896f834b33c9",
          "sha1": "78215977cabd4939def6e7e3ac556aac3416e27b",
          "md5": "730aa0089292527233b74ab5f66e6e99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.1-dev-sources.jar",
          "url": "qqrobot-spring-boot-starter-2.0.1-dev-sources.jar",
          "size": 1144099,
          "sha512": "fc41eaa57b2d0f7bb08bade24faa8b975feba13ef04a027f1eb051c48ec4b98e915dd62f6a284aad97cd216c6c69776fd97cf8a3704817cf6310adae71750e1e",
          "sha256": "f928dff072d79541be48c01aca630a073e179798f403205167a58e28b644f0fd",
          "sha1": "88a078b8407bce5d47e0f711458727f2dfc0e83d",
          "md5": "2f2c7115fc7485949cf2ac31387036a5"
        }
      ]
    }
  ]
}
