{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "2.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.0.2-dev"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.1-dev.jar",
          "url": "qqrobot-spring-boot-starter-2.0.1-dev.jar",
          "size": 151322,
          "sha512": "1a19bc209d055085d02fac9e173fea46057a8df736e935884a052a7c6539768fa60ce8076956d2a4c483ce288b604a0bd43f599f01afb1f8e5218716f5e006ee",
          "sha256": "44ad29c687cda51fdb180cd0c6f35991b13bd9a40114974f5661a90962ea1c2f",
          "sha1": "9ef7d06c323d591286d08912bec3805a67ed70a8",
          "md5": "f3b60d42d4a31a2d08a56b391f1f4917"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.0.2-dev"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "2.0.1-dev"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.1-dev.jar",
          "url": "qqrobot-spring-boot-starter-2.0.1-dev.jar",
          "size": 151322,
          "sha512": "1a19bc209d055085d02fac9e173fea46057a8df736e935884a052a7c6539768fa60ce8076956d2a4c483ce288b604a0bd43f599f01afb1f8e5218716f5e006ee",
          "sha256": "44ad29c687cda51fdb180cd0c6f35991b13bd9a40114974f5661a90962ea1c2f",
          "sha1": "9ef7d06c323d591286d08912bec3805a67ed70a8",
          "md5": "f3b60d42d4a31a2d08a56b391f1f4917"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-2.0.1-dev-sources.jar",
          "url": "qqrobot-spring-boot-starter-2.0.1-dev-sources.jar",
          "size": 53924,
          "sha512": "1d525ce4ee13c057e2d8d559dd2b23c9ad7cc15c561a2466912f5b87b030516a1a65b8c6a8a7cdaad2f4b63b36d1729f58ca6e5d125bd349917a229174890f74",
          "sha256": "da3b15eec631624284f0de1e3f54513db663811f76d2cd3f4d529d806f0b2f9c",
          "sha1": "32d910f69aed8a063a95a45e8066e1abb84e6b5c",
          "md5": "6846de794ad624d073baacf07fb0bfb3"
        }
      ]
    }
  ]
}
