{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-2.0.0.jar",
          "url": "honoka-spring-boot-starter-2.0.0.jar",
          "size": 52979,
          "sha512": "0ed73ad2b526f07da0e8cc1e7724346c6313f9323243eb237c4f966d108fac7b6f866c25dc608861b3b2431cc1453b8aae72d35dc7a0333fb3fc1de4fbd09a1e",
          "sha256": "dd51036b3dcfbc360051ed09a0755f8ed827f701830e4e9a5ec4803f6daa09d0",
          "sha1": "32d379e22bda0f01145e64fae7514004b824b79e",
          "md5": "ea5970926d79ffce5984f5f3fcbc8d5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-2.0.0.jar",
          "url": "honoka-spring-boot-starter-2.0.0.jar",
          "size": 52979,
          "sha512": "0ed73ad2b526f07da0e8cc1e7724346c6313f9323243eb237c4f966d108fac7b6f866c25dc608861b3b2431cc1453b8aae72d35dc7a0333fb3fc1de4fbd09a1e",
          "sha256": "dd51036b3dcfbc360051ed09a0755f8ed827f701830e4e9a5ec4803f6daa09d0",
          "sha1": "32d379e22bda0f01145e64fae7514004b824b79e",
          "md5": "ea5970926d79ffce5984f5f3fcbc8d5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-2.0.0-sources.jar",
          "url": "honoka-spring-boot-starter-2.0.0-sources.jar",
          "size": 18682,
          "sha512": "8a4ec9461ecb7f80414c7fa5bcf0d0019dc2ccdebfa15256e58f22047e4a99e9ec101a594528583fe0fa76e3c31dfec46da96a38a10d496be8e4c45d1e3b567c",
          "sha256": "34273e9f4f3b358a54483e59fde683143742643fc3d3a1a7de613d53d42e64cf",
          "sha1": "afe4adad54c307d9a21ede375031293f11addaed",
          "md5": "17105299be1ac31539b73b1c4b910908"
        }
      ]
    }
  ]
}
