{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-2.0.0.jar",
          "url": "honoka-spring-boot-starter-2.0.0.jar",
          "size": 51740,
          "sha512": "c2a2655cc9cc3c7f96c99dc012eb52c2c9e0bfa061dfb6a175eda685699934bb7e25197c6651d6c34458505e047219c81dc19f9604801e15a6db99992729c295",
          "sha256": "2606d725a67a3750b1c2876179b8b61e1ee00ab6a6cfb32e31c1dff1a56585f1",
          "sha1": "33ae26e9e42dabd0c7483b0312ecbcad994ad682",
          "md5": "2e83d529d5854ae2788e5686288e671d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-2.0.0.jar",
          "url": "honoka-spring-boot-starter-2.0.0.jar",
          "size": 51740,
          "sha512": "c2a2655cc9cc3c7f96c99dc012eb52c2c9e0bfa061dfb6a175eda685699934bb7e25197c6651d6c34458505e047219c81dc19f9604801e15a6db99992729c295",
          "sha256": "2606d725a67a3750b1c2876179b8b61e1ee00ab6a6cfb32e31c1dff1a56585f1",
          "sha1": "33ae26e9e42dabd0c7483b0312ecbcad994ad682",
          "md5": "2e83d529d5854ae2788e5686288e671d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-2.0.0-sources.jar",
          "url": "honoka-spring-boot-starter-2.0.0-sources.jar",
          "size": 18539,
          "sha512": "2f64849ca581caff107438aaa47d9c561e53c1e9f0c6a345905f969c1047aea6e20de1e0775e13bcdf82d7f076595ca8c5f5ebb4b14df131f29765281b84f265",
          "sha256": "dfa4090f8930191a4945e979493de76b7dcc45e93f31c7bb100d2a8038c47ddf",
          "sha1": "cc4ebc7c12dca69c63217f86ec9cc0fdc1898014",
          "md5": "1ee2f7d8a6f128fad64d3ef7c0b72ac7"
        }
      ]
    }
  ]
}
