{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-json-api",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "honoka-json-api-1.1.2.jar",
          "url": "honoka-json-api-1.1.2.jar",
          "size": 10837,
          "sha512": "72e9c53c0274962ffceca5389a50465cf508280b0f45266b1c58c8ba6c10d459d42d185d9e9509c1066484ee8a9b951f298051d64a9c177e7a38b210592626c2",
          "sha256": "4a23c571251cfe53df838a3942af421864a5ccc855be733d01d193494693cf62",
          "sha1": "db12a15c8a3b59550110b56c2cbf0787072a0a6b",
          "md5": "6ff7f9f9b3b53e7de2c8b81f7d8a3730"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-api-1.1.2.jar",
          "url": "honoka-json-api-1.1.2.jar",
          "size": 10837,
          "sha512": "72e9c53c0274962ffceca5389a50465cf508280b0f45266b1c58c8ba6c10d459d42d185d9e9509c1066484ee8a9b951f298051d64a9c177e7a38b210592626c2",
          "sha256": "4a23c571251cfe53df838a3942af421864a5ccc855be733d01d193494693cf62",
          "sha1": "db12a15c8a3b59550110b56c2cbf0787072a0a6b",
          "md5": "6ff7f9f9b3b53e7de2c8b81f7d8a3730"
        }
      ]
    }
  ]
}
