{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.2.0.jar",
          "url": "qqrobot-spring-boot-starter-1.2.0.jar",
          "size": 887884,
          "sha512": "2edff08c7ce1aecb265371cfb94d1a86f1e1c6ec80de508af04ce31f54820a37501c3bcd6e5308346f5fa625ba7faf4ee98c449cd2b42541a87ece1091b76ab4",
          "sha256": "3c80fb54e38d03e897c0df1861473c39767d5803374dd750923c593e5fb98284",
          "sha1": "384a6ca0f598a53cdbb8543e566a4f0493674519",
          "md5": "1cc14e254d6a205339b9b4cbca837f92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-framework-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.mamoe",
          "module": "mirai-core-jvm",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.2.0.jar",
          "url": "qqrobot-spring-boot-starter-1.2.0.jar",
          "size": 887884,
          "sha512": "2edff08c7ce1aecb265371cfb94d1a86f1e1c6ec80de508af04ce31f54820a37501c3bcd6e5308346f5fa625ba7faf4ee98c449cd2b42541a87ece1091b76ab4",
          "sha256": "3c80fb54e38d03e897c0df1861473c39767d5803374dd750923c593e5fb98284",
          "sha1": "384a6ca0f598a53cdbb8543e566a4f0493674519",
          "md5": "1cc14e254d6a205339b9b4cbca837f92"
        }
      ]
    }
  ]
}
