{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender",
    "module": "lavsource-spring-boot-starter",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lavsource-spring-boot-starter-1.0.0.jar",
          "url": "lavsource-spring-boot-starter-1.0.0.jar",
          "size": 19157,
          "sha512": "08b637f690b0dbe84fc4951086c2bb3e0c254294effaaf6404110d792d449bd4403c36ad257c55b72604f4c7c3dd2dc7b391b14615ead832105015f4947ce533",
          "sha256": "7fed9c32ae6b57e3f2271260f24c074ca6f5897ffe1e4790da14b420b37d7a06",
          "sha1": "1066c8dcd590233e8a64fb2352cbba1b3546d6a3",
          "md5": "85d3c6efcc5f798a827f2e628c8f88af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-framework-utils",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        }
      ],
      "files": [
        {
          "name": "lavsource-spring-boot-starter-1.0.0.jar",
          "url": "lavsource-spring-boot-starter-1.0.0.jar",
          "size": 19157,
          "sha512": "08b637f690b0dbe84fc4951086c2bb3e0c254294effaaf6404110d792d449bd4403c36ad257c55b72604f4c7c3dd2dc7b391b14615ead832105015f4947ce533",
          "sha256": "7fed9c32ae6b57e3f2271260f24c074ca6f5897ffe1e4790da14b420b37d7a06",
          "sha1": "1066c8dcd590233e8a64fb2352cbba1b3546d6a3",
          "md5": "85d3c6efcc5f798a827f2e628c8f88af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavsource-spring-boot-starter-1.0.0-sources.jar",
          "url": "lavsource-spring-boot-starter-1.0.0-sources.jar",
          "size": 7144,
          "sha512": "619d14731dd2f0b0497fbaa79995f49188740e9363759d2769d388d25fa77848f46be8f5e9b865a11c761281d972c9c557f7fb27521bf628e720b1e66bd8f59d",
          "sha256": "f8c79aaa1b26efffaff9e17325a1283703dd1875260807ca531b3442b70057cb",
          "sha1": "69ae4cfdf96b1e5c579e224470f22fe4bc794e71",
          "md5": "6920469b4cdbbd0ad19003df8c071789"
        }
      ]
    }
  ]
}
