{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.0.jar",
          "url": "honoka-kotlin-utils-1.1.0.jar",
          "size": 119149,
          "sha512": "1567e16e2ac8e0c163a678fdc270fbb0e524fe6f436146a1930dc05a4bcc57c18f2f8bf707c6206669fe1fea914282cf8e70c029b2c0a962101840e85968ad89",
          "sha256": "757c4833e29e3f053a6c517cb42c2b4ef88fd31abcc136fe6fb5acfd77021053",
          "sha1": "6c655e8083f0fb1149dbf892497a3ac55f7d3882",
          "md5": "b4c804b9f82e39415e5265e5bfd72199"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.0.jar",
          "url": "honoka-kotlin-utils-1.1.0.jar",
          "size": 119149,
          "sha512": "1567e16e2ac8e0c163a678fdc270fbb0e524fe6f436146a1930dc05a4bcc57c18f2f8bf707c6206669fe1fea914282cf8e70c029b2c0a962101840e85968ad89",
          "sha256": "757c4833e29e3f053a6c517cb42c2b4ef88fd31abcc136fe6fb5acfd77021053",
          "sha1": "6c655e8083f0fb1149dbf892497a3ac55f7d3882",
          "md5": "b4c804b9f82e39415e5265e5bfd72199"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.0-sources.jar",
          "url": "honoka-kotlin-utils-1.1.0-sources.jar",
          "size": 23486,
          "sha512": "7ee615dbd2361ef30ecf0672269c7485d04828f504525079acdcbf3fc3aeb4ed71156342637e177b62fb1a341321264dfaa15af4911d49b6370c24ee040c28ff",
          "sha256": "88d686e15d768d5258776506796f73234fcab5c720848951f3a6ff0dd7f4e63e",
          "sha1": "6b5c192e4c5fd950addd852dd1bcf445113bc20a",
          "md5": "43cc99700777211cac320c8765024dac"
        }
      ]
    }
  ]
}
