{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-json-gson",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-json-api",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-gson-1.1.3.jar",
          "url": "honoka-json-gson-1.1.3.jar",
          "size": 11978,
          "sha512": "be1818b4c40dc0a6c96ab8bd8e94535b272489ecb4d0ffbf587db724cb618299b3199243d9c870d9c3a0355bd30a528e2e0b7733a7ff74e6ba179cfffd8e2e81",
          "sha256": "cf5fa75c5eb0267422bcd30c711e33fd753258de2f06823389cd4f986280e870",
          "sha1": "2176bd0ca7285f4aaf9c83f85e42eebb15bdb3ef",
          "md5": "1c13b7f8ad7c9e26af968e042204e409"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-json-api",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-gson-1.1.3.jar",
          "url": "honoka-json-gson-1.1.3.jar",
          "size": 11978,
          "sha512": "be1818b4c40dc0a6c96ab8bd8e94535b272489ecb4d0ffbf587db724cb618299b3199243d9c870d9c3a0355bd30a528e2e0b7733a7ff74e6ba179cfffd8e2e81",
          "sha256": "cf5fa75c5eb0267422bcd30c711e33fd753258de2f06823389cd4f986280e870",
          "sha1": "2176bd0ca7285f4aaf9c83f85e42eebb15bdb3ef",
          "md5": "1c13b7f8ad7c9e26af968e042204e409"
        }
      ]
    }
  ]
}
