{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-json-gson",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-json-api",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-gson-1.1.3.jar",
          "url": "honoka-json-gson-1.1.3.jar",
          "size": 11975,
          "sha512": "8c06abdaf7fbfd6a5ca59b5a86f2cb5eaa21e78291a96766bab56f3fc26cad34070e3176952dac92faf5389eee3ede4180245faea70ca954470b905520b8de32",
          "sha256": "2f7a1da5f084f8e2dcfa5fe0d106d0800c5ddf1147e3a609373627bddf1cd101",
          "sha1": "8c0d0c7ed2c87ceab7782c9c24121aef56e6b7f9",
          "md5": "883bc5666fa5667f355930e9fff13609"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-json-api",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-gson-1.1.3.jar",
          "url": "honoka-json-gson-1.1.3.jar",
          "size": 11975,
          "sha512": "8c06abdaf7fbfd6a5ca59b5a86f2cb5eaa21e78291a96766bab56f3fc26cad34070e3176952dac92faf5389eee3ede4180245faea70ca954470b905520b8de32",
          "sha256": "2f7a1da5f084f8e2dcfa5fe0d106d0800c5ddf1147e3a609373627bddf1cd101",
          "sha1": "8c0d0c7ed2c87ceab7782c9c24121aef56e6b7f9",
          "md5": "883bc5666fa5667f355930e9fff13609"
        }
      ]
    }
  ]
}
