{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-json-gson",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-json-api",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-gson-1.1.3.jar",
          "url": "honoka-json-gson-1.1.3.jar",
          "size": 11975,
          "sha512": "a5238d324d737422c4ef67ef388564e4ffeebef2cde245227a8e3b692c3407a15262ab7b1f3f3f20b54778d67dcc7ef596b4a135bb8b64d9d1cc6a01a67bd12d",
          "sha256": "2f7013577af732d2bde42b07da452af2355fe3cfe36211476b2d213cdeb88540",
          "sha1": "fd27fdd3355ace1733956e9107466cd27ca06a99",
          "md5": "970b28d288149f5bf82880757371dbe4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-json-api",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-gson-1.1.3.jar",
          "url": "honoka-json-gson-1.1.3.jar",
          "size": 11975,
          "sha512": "a5238d324d737422c4ef67ef388564e4ffeebef2cde245227a8e3b692c3407a15262ab7b1f3f3f20b54778d67dcc7ef596b4a135bb8b64d9d1cc6a01a67bd12d",
          "sha256": "2f7013577af732d2bde42b07da452af2355fe3cfe36211476b2d213cdeb88540",
          "sha1": "fd27fdd3355ace1733956e9107466cd27ca06a99",
          "md5": "970b28d288149f5bf82880757371dbe4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-json-gson-1.1.3-sources.jar",
          "url": "honoka-json-gson-1.1.3-sources.jar",
          "size": 6310,
          "sha512": "8c50d8f4e33eab1dfc7e7268b95e2d26f3f2e83cf72f1486a34b67e068f94ac596f41a41e2f6f9188f28901a2f7cab9a4ecaf753553ec458f46f3fd6f1c86ee3",
          "sha256": "2367b9dafe1d49d57623dd8dab34083f5e6691d8e18dcc7d472538adf744afdf",
          "sha1": "35f1f5eb512e3a567f9dde5baf162a6ed7598079",
          "md5": "7dafac26ee5d52139d3610c06e84d5a7"
        }
      ]
    }
  ]
}
