{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.2.2.jar",
          "url": "qqrobot-spring-boot-starter-1.2.2.jar",
          "size": 891135,
          "sha512": "ba4f08d385668058f43070f9936d6e10a79d11e74d1f5f9561ae086ef1068d44a3b16f81eabf2c8bed6e3496a695f13905f51335f35d689d38308352780d53f8",
          "sha256": "50618031ad6fdc3479dd158787495d22aefd4fbcb0bff4e82880e4d8655071d7",
          "sha1": "ef3b74028622af0f7c8201932e878c434ee570c7",
          "md5": "fbf20ea63b7a614e32ed7c083323ea18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-framework-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.mamoe",
          "module": "mirai-core-jvm",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.2.2.jar",
          "url": "qqrobot-spring-boot-starter-1.2.2.jar",
          "size": 891135,
          "sha512": "ba4f08d385668058f43070f9936d6e10a79d11e74d1f5f9561ae086ef1068d44a3b16f81eabf2c8bed6e3496a695f13905f51335f35d689d38308352780d53f8",
          "sha256": "50618031ad6fdc3479dd158787495d22aefd4fbcb0bff4e82880e4d8655071d7",
          "sha1": "ef3b74028622af0f7c8201932e878c434ee570c7",
          "md5": "fbf20ea63b7a614e32ed7c083323ea18"
        }
      ]
    }
  ]
}
