{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-framework-utils",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.1.jar",
          "url": "honoka-framework-utils-1.0.1.jar",
          "size": 13329,
          "sha512": "9de2b80cd6a74779113f43a26472b03867ad274f2a4857ecb5b6206e1c372f308af2347bd90b419d134e5b192442537ba07a000eedd40eda3d7bf6dda255f5c6",
          "sha256": "4c1afa38a4af57777f515044425afa4b3a0d4d33314d456b14435d396a08d8a9",
          "sha1": "4a2d1c5f09733a7c5c2fb5d2746baefce457580f",
          "md5": "4382e28f6f763da151346c8e6714cab2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.1.jar",
          "url": "honoka-framework-utils-1.0.1.jar",
          "size": 13329,
          "sha512": "9de2b80cd6a74779113f43a26472b03867ad274f2a4857ecb5b6206e1c372f308af2347bd90b419d134e5b192442537ba07a000eedd40eda3d7bf6dda255f5c6",
          "sha256": "4c1afa38a4af57777f515044425afa4b3a0d4d33314d456b14435d396a08d8a9",
          "sha1": "4a2d1c5f09733a7c5c2fb5d2746baefce457580f",
          "md5": "4382e28f6f763da151346c8e6714cab2"
        }
      ]
    }
  ]
}
