{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-framework-utils",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.1.jar",
          "url": "honoka-framework-utils-1.0.1.jar",
          "size": 13414,
          "sha512": "914565b964619c05ed2ab276f4a2920fe27763bb7456fe04eff7261e479cc8b6b1b0f7a83dc271c14ca8cfe4799b8318a3ffbe26e8a42097a676e0be1d6f40dd",
          "sha256": "9783886541f5044fae46b87ee06558b2fd16324b73c7241dfa350c774188d240",
          "sha1": "3c5322087e02632f940fbc9f92e1e4469d77bae7",
          "md5": "8d42690875d630d54437673703fd6fb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.1.jar",
          "url": "honoka-framework-utils-1.0.1.jar",
          "size": 13414,
          "sha512": "914565b964619c05ed2ab276f4a2920fe27763bb7456fe04eff7261e479cc8b6b1b0f7a83dc271c14ca8cfe4799b8318a3ffbe26e8a42097a676e0be1d6f40dd",
          "sha256": "9783886541f5044fae46b87ee06558b2fd16324b73c7241dfa350c774188d240",
          "sha1": "3c5322087e02632f940fbc9f92e1e4469d77bae7",
          "md5": "8d42690875d630d54437673703fd6fb5"
        }
      ]
    }
  ]
}
