{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-framework-utils",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.1.jar",
          "url": "honoka-framework-utils-1.0.1.jar",
          "size": 13414,
          "sha512": "f0c278e9c4214456fabc67e4dde444a367cd34c0b2a3596d7e7d781f6ba644c6b6cdb40d22bce826b886307aa9c5735691bf90e6ee4137cbd960ef7d98be10a5",
          "sha256": "784600c1de689f211836cb3883946473586c000cfef4a660ef83876ab0d86f47",
          "sha1": "5e9c6d1116aae0bc6fa9d56a11902c9797482aab",
          "md5": "1d434ecdab8836d756bd80a22ac903ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.1.jar",
          "url": "honoka-framework-utils-1.0.1.jar",
          "size": 13414,
          "sha512": "f0c278e9c4214456fabc67e4dde444a367cd34c0b2a3596d7e7d781f6ba644c6b6cdb40d22bce826b886307aa9c5735691bf90e6ee4137cbd960ef7d98be10a5",
          "sha256": "784600c1de689f211836cb3883946473586c000cfef4a660ef83876ab0d86f47",
          "sha1": "5e9c6d1116aae0bc6fa9d56a11902c9797482aab",
          "md5": "1d434ecdab8836d756bd80a22ac903ca"
        }
      ]
    }
  ]
}
