{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-json-fastjson",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-json-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-fastjson-1.1.2.jar",
          "url": "honoka-json-fastjson-1.1.2.jar",
          "size": 11083,
          "sha512": "009e96bd355fdc991a97c6db81dc2289678f4c5f09b0fe9f34a7932c03c146df225c7d0b6822ff3d804f2f9f8c8154657af725e8cc9c17a77730b72626775d14",
          "sha256": "eceff2c41b2b031fbddf777c7b06e5098ffadd6c353877167dbed459d1574f42",
          "sha1": "1a89e35ebabbaff3b9bef7dc888c3837b6f7b51a",
          "md5": "662d29e5c7e09f8533eeea7353f82ef1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-json-api",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.75"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-fastjson-1.1.2.jar",
          "url": "honoka-json-fastjson-1.1.2.jar",
          "size": 11083,
          "sha512": "009e96bd355fdc991a97c6db81dc2289678f4c5f09b0fe9f34a7932c03c146df225c7d0b6822ff3d804f2f9f8c8154657af725e8cc9c17a77730b72626775d14",
          "sha256": "eceff2c41b2b031fbddf777c7b06e5098ffadd6c353877167dbed459d1574f42",
          "sha1": "1a89e35ebabbaff3b9bef7dc888c3837b6f7b51a",
          "md5": "662d29e5c7e09f8533eeea7353f82ef1"
        }
      ]
    }
  ]
}
