{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "1.1.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.1.0-dev.jar",
          "url": "qqrobot-framework-api-1.1.0-dev.jar",
          "size": 8790,
          "sha512": "3d1d6b6aff75480e48fed526e62ca5d2f86d026aecb39b5c04446b3b14854947f701a58e5027660ba8eb01f791b695cb3a1466502cdeee36e7e61e31d0eba60c",
          "sha256": "f50c353da87ee2e3dfa2064878df2e62d806bab7d73e033c76eacc361f664674",
          "sha1": "a7da16ad4ac944a5de7e0fb1ece1c79993c598b7",
          "md5": "3c643d2835a1da631bbfd43262843658"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.1.0-dev.jar",
          "url": "qqrobot-framework-api-1.1.0-dev.jar",
          "size": 8790,
          "sha512": "3d1d6b6aff75480e48fed526e62ca5d2f86d026aecb39b5c04446b3b14854947f701a58e5027660ba8eb01f791b695cb3a1466502cdeee36e7e61e31d0eba60c",
          "sha256": "f50c353da87ee2e3dfa2064878df2e62d806bab7d73e033c76eacc361f664674",
          "sha1": "a7da16ad4ac944a5de7e0fb1ece1c79993c598b7",
          "md5": "3c643d2835a1da631bbfd43262843658"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.1.0-dev-sources.jar",
          "url": "qqrobot-framework-api-1.1.0-dev-sources.jar",
          "size": 4894,
          "sha512": "a6da752da4b640a9bcda22045a31f5a6c66c875bb2edfa7e70affa20daaff30c1aa2ac8bb3f7c4d617cd379f9246c9cb4c4006e8955e45a43e06dc64f1b40abc",
          "sha256": "736149063ef3baa85be8487284372a96e89917f32ef13366dfb531de6e991f59",
          "sha1": "a6c51143bbf0aebaecb35716d94c8a37b1c144e9",
          "md5": "8764835e462fce86191f8c543ff09d0f"
        }
      ]
    }
  ]
}
