{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "1.1.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-framework-api-1.1.0-dev.jar",
          "url": "qqrobot-framework-api-1.1.0-dev.jar",
          "size": 8771,
          "sha512": "4c9c422fc78a13699bfb0801245fbb82dadafd09114d38103d5cb0ee0e8bb47b8e6dbffd443a0e6a6c2cfb19b50210d39e0cff1c631980d0e725655f518cd8e5",
          "sha256": "58f4a26e07f73161675634c4c87eaf5ec954cf98e1070959e91d7e182ece3743",
          "sha1": "0f01d844333267a17086ddc5d562d115d7eacf52",
          "md5": "3506aa21901adcfb77f5df945087a7c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-framework-api-1.1.0-dev.jar",
          "url": "qqrobot-framework-api-1.1.0-dev.jar",
          "size": 8771,
          "sha512": "4c9c422fc78a13699bfb0801245fbb82dadafd09114d38103d5cb0ee0e8bb47b8e6dbffd443a0e6a6c2cfb19b50210d39e0cff1c631980d0e725655f518cd8e5",
          "sha256": "58f4a26e07f73161675634c4c87eaf5ec954cf98e1070959e91d7e182ece3743",
          "sha1": "0f01d844333267a17086ddc5d562d115d7eacf52",
          "md5": "3506aa21901adcfb77f5df945087a7c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.1.0-dev-sources.jar",
          "url": "qqrobot-framework-api-1.1.0-dev-sources.jar",
          "size": 4934,
          "sha512": "86cd0405f733b0d9a311e637462050177c5f7a835ba14ae4d2d067cbddc99b8464cc6bc820bb016e301349d338f64df7cd3963e330440a686dd0ce46316db095",
          "sha256": "b7685cc153e377f0d4a87fcec071671746c9addfecc498464db0ed5611ae9a7c",
          "sha1": "9226dfd49a400ba0d4429b333639ee6063d447c4",
          "md5": "c752b5b2581745b3dc309b4b7315cee7"
        }
      ]
    }
  ]
}
