{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "1.1.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.1.0-dev.jar",
          "url": "qqrobot-framework-api-1.1.0-dev.jar",
          "size": 8790,
          "sha512": "8541040a64a67086856a59f30b2f72c68a04b771740a30ea1791ef344f3b7ee1f972d1ffad7e60778494498eb1ae5f911cd92b5e645d3732cfd9bb4a20d7cd91",
          "sha256": "6a17bac595ae0abc9fd63057e8b6fbeb1aff0246610b6f4379e2143962e60b6a",
          "sha1": "63d295db2177452f6f42ed53f31394fee8e5a449",
          "md5": "044d507d7471f7f099774529a799485f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.1.0-dev.jar",
          "url": "qqrobot-framework-api-1.1.0-dev.jar",
          "size": 8790,
          "sha512": "8541040a64a67086856a59f30b2f72c68a04b771740a30ea1791ef344f3b7ee1f972d1ffad7e60778494498eb1ae5f911cd92b5e645d3732cfd9bb4a20d7cd91",
          "sha256": "6a17bac595ae0abc9fd63057e8b6fbeb1aff0246610b6f4379e2143962e60b6a",
          "sha1": "63d295db2177452f6f42ed53f31394fee8e5a449",
          "md5": "044d507d7471f7f099774529a799485f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.1.0-dev-sources.jar",
          "url": "qqrobot-framework-api-1.1.0-dev-sources.jar",
          "size": 4894,
          "sha512": "4fca029cce33eccc223d06790292141427afa87bb3e51255443e1dbc4f5fbb05bd828ec625f0fbe8df5878b557bfd6dd5e3bbb69bcb4c23d217ddad462b0587b",
          "sha256": "130bba6fe8035e70a2ce865717c1e2510d96b30efeb8df1fa5fd28539ace9a17",
          "sha1": "8220389a94b2048a9d361db224478f50c68cfea9",
          "md5": "dd1ff9a734ca19915a5d8c2cf7a71da2"
        }
      ]
    }
  ]
}
