{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-basic-plugin",
    "version": "1.0.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.2-dev.jar",
          "url": "honoka-basic-plugin-1.0.2-dev.jar",
          "size": 32304,
          "sha512": "8d900e24ccc62e48fc6f7d67b8b5217f9eec8cc820fa123bce9cdb1d8b701624cb927e4e0958690a824db2f7086d13fb6ca07721db4adb48a6ce2c2390be89a4",
          "sha256": "f04256cd710d9ad43e225dc4ff9aafe5f85b6980916aaa7695c7fa784897b966",
          "sha1": "1c363fc5f05b460060b43a13326d3145eede4bc8",
          "md5": "f5077d416ee28bd7f4d9619b03c2099a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.2-dev.jar",
          "url": "honoka-basic-plugin-1.0.2-dev.jar",
          "size": 32304,
          "sha512": "8d900e24ccc62e48fc6f7d67b8b5217f9eec8cc820fa123bce9cdb1d8b701624cb927e4e0958690a824db2f7086d13fb6ca07721db4adb48a6ce2c2390be89a4",
          "sha256": "f04256cd710d9ad43e225dc4ff9aafe5f85b6980916aaa7695c7fa784897b966",
          "sha1": "1c363fc5f05b460060b43a13326d3145eede4bc8",
          "md5": "f5077d416ee28bd7f4d9619b03c2099a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.2-dev-sources.jar",
          "url": "honoka-basic-plugin-1.0.2-dev-sources.jar",
          "size": 3618,
          "sha512": "ecbeff65df487d160fcb507d898ee123f6746e20d016d9c4b76eda7f886d56234a49a0ce6db8181f361d9567a07bd6ffca2985dd669daa5c59659ad58f6723d5",
          "sha256": "8901b4ac28295e18ea68d1daf3c0c3552341f3ae92513584617b1fd96c090bb4",
          "sha1": "1efd69d6367b0a334394c3773619ebe2ff9bf744",
          "md5": "834dddfaa8c2fe6fd0e1cb14f8d4dceb"
        }
      ]
    }
  ]
}
