{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-basic-plugin",
    "version": "1.0.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.2-dev.jar",
          "url": "honoka-basic-plugin-1.0.2-dev.jar",
          "size": 25293,
          "sha512": "48b2015340a3099e113522dd7f1806ccbb79797a54b8b9bc22d8143161c70451f49b2b7a1cb8dc22b6cd2bd8caf20e325f95137f44d08b2ca9688649d43adf53",
          "sha256": "9f82beda702d0ac645f76f22eb68ff289b7932a33b889d67d4caeed0f45d1ecc",
          "sha1": "059ae96c3950853e7bd87fc483be409187eafb5f",
          "md5": "4ecb54da0f2f19987f00deecdf96386f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.2-dev.jar",
          "url": "honoka-basic-plugin-1.0.2-dev.jar",
          "size": 25293,
          "sha512": "48b2015340a3099e113522dd7f1806ccbb79797a54b8b9bc22d8143161c70451f49b2b7a1cb8dc22b6cd2bd8caf20e325f95137f44d08b2ca9688649d43adf53",
          "sha256": "9f82beda702d0ac645f76f22eb68ff289b7932a33b889d67d4caeed0f45d1ecc",
          "sha1": "059ae96c3950853e7bd87fc483be409187eafb5f",
          "md5": "4ecb54da0f2f19987f00deecdf96386f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.2-dev-sources.jar",
          "url": "honoka-basic-plugin-1.0.2-dev-sources.jar",
          "size": 3618,
          "sha512": "0be5c774253ac4c001b74bfcb64102e35e0452b92181a4531104e01ed89e76328fb42f2ad11c61e5ed60f9b5cce49e9e7966a9cf506f3a273e82de4d27224e36",
          "sha256": "deebc191c70323e7985b60c7398975cc55b8dd4956eb725b0d4a62057caf053c",
          "sha1": "0828c9daece3f5fd123b610d5465794afc947a59",
          "md5": "de383650d555d791f62f055c9fa525c1"
        }
      ]
    }
  ]
}
