{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-basic-plugin",
    "version": "1.0.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.2-dev.jar",
          "url": "honoka-basic-plugin-1.0.2-dev.jar",
          "size": 32304,
          "sha512": "6dd98a493d6c4485a31937480339370031fb94e24b0ada4edbe62904b08d5808677f7e73f61c3c89edc163929f91b01c44b256815a27e222af25eb319d84cd03",
          "sha256": "605a2735a1457192369d1b88a6662b2d7373b697820d22829f22320772b49a6d",
          "sha1": "a12d03ccd05fd6adead96bc5ffc842ce1a368e4d",
          "md5": "fb0d8f1c835d4d98f3549d6a87a95a70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.2-dev.jar",
          "url": "honoka-basic-plugin-1.0.2-dev.jar",
          "size": 32304,
          "sha512": "6dd98a493d6c4485a31937480339370031fb94e24b0ada4edbe62904b08d5808677f7e73f61c3c89edc163929f91b01c44b256815a27e222af25eb319d84cd03",
          "sha256": "605a2735a1457192369d1b88a6662b2d7373b697820d22829f22320772b49a6d",
          "sha1": "a12d03ccd05fd6adead96bc5ffc842ce1a368e4d",
          "md5": "fb0d8f1c835d4d98f3549d6a87a95a70"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.2-dev-sources.jar",
          "url": "honoka-basic-plugin-1.0.2-dev-sources.jar",
          "size": 3618,
          "sha512": "254a97e3e808bd200a8aab4e5dc3c7d7bffebc1c7571c124dfb0aea8ec5212b087dcc6b3aa5ef9bc6935de94243133a150ba34ac2b4ae3a170f8b388bdf661e9",
          "sha256": "9f876fa76f14e61f7c74fe88fed2ec4f0dfa9fb49a603a0a3b146f027b9415be",
          "sha1": "b97ee9bc1cf3df92e30a4f524bb1599c0f6d7cd1",
          "md5": "401dd2744cd0c298c795284c983a5b2f"
        }
      ]
    }
  ]
}
