{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0.jar",
          "url": "honoka-kotlin-utils-2.0.0.jar",
          "size": 8519,
          "sha512": "3b38a9997553de0e679f92e6ee19e7f1113efb62830d1656d6ee8d1a7b99cbe312fa6065b290096e28c43fa3c88991a7550f55eea0f9b59412d25cede563645b",
          "sha256": "9ecb3ca7c2588bf09f2ac92e8d9bf5893cc970af730476a481827d54eb892801",
          "sha1": "dae6fd9ffedd00a478613a5a754725c04b405fcf",
          "md5": "57f7d7f69ececfb11f83173580b284e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0.jar",
          "url": "honoka-kotlin-utils-2.0.0.jar",
          "size": 8519,
          "sha512": "3b38a9997553de0e679f92e6ee19e7f1113efb62830d1656d6ee8d1a7b99cbe312fa6065b290096e28c43fa3c88991a7550f55eea0f9b59412d25cede563645b",
          "sha256": "9ecb3ca7c2588bf09f2ac92e8d9bf5893cc970af730476a481827d54eb892801",
          "sha1": "dae6fd9ffedd00a478613a5a754725c04b405fcf",
          "md5": "57f7d7f69ececfb11f83173580b284e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0-sources.jar",
          "url": "honoka-kotlin-utils-2.0.0-sources.jar",
          "size": 3854,
          "sha512": "98cbed6e37e3ee20e927c5a56031ea76f26d531b300e77180327b69c88a0e3a096d9c99ea79bc832005aa65d13ea6818dd7b0f09f92dcdec0ede38c12ad07b69",
          "sha256": "840eff3a791d4d0f6b8fa8e9aebb7e73cac49e298403fe06a0adef18811c4b0e",
          "sha1": "0814c0aa486fd7abee0133bdc4071a7a15f61176",
          "md5": "643f6079cd02d53a46c3ffef04799d92"
        }
      ]
    }
  ]
}
