{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0.jar",
          "url": "honoka-kotlin-utils-2.0.0.jar",
          "size": 8519,
          "sha512": "c305dc9af4cbbc8a2f061fa4960be8bef2db6ea67111deba72d8c01bee87bee41eec0d57f2d0a05c7ffb58a23ebbcb0f59ad062b14406c6d95fdabe4072e9c65",
          "sha256": "43a1491baa5eb5b6a3698d0c130557569b742af0c8d5edc04f7fae367e7c35fd",
          "sha1": "fc128b3dd5d6989928733abce3248cbb6850f9a0",
          "md5": "f328b378aeef42b4d3366806748406e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0.jar",
          "url": "honoka-kotlin-utils-2.0.0.jar",
          "size": 8519,
          "sha512": "c305dc9af4cbbc8a2f061fa4960be8bef2db6ea67111deba72d8c01bee87bee41eec0d57f2d0a05c7ffb58a23ebbcb0f59ad062b14406c6d95fdabe4072e9c65",
          "sha256": "43a1491baa5eb5b6a3698d0c130557569b742af0c8d5edc04f7fae367e7c35fd",
          "sha1": "fc128b3dd5d6989928733abce3248cbb6850f9a0",
          "md5": "f328b378aeef42b4d3366806748406e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0-sources.jar",
          "url": "honoka-kotlin-utils-2.0.0-sources.jar",
          "size": 3854,
          "sha512": "a619319abbe815587e14c40144af8aafade94def0ebcf46c9835c2a34908912fa79acb9f7a016df7fbbcc336c6578b3a904de9eb29dec834a3e38af52d6d087a",
          "sha256": "a2dc11b8a2f9ea0d267b511e9338167bc06f4c34d3f823a322a31ec86cb72e22",
          "sha1": "80d3f671b49a6e3e4cd77fce73bc67b807820f84",
          "md5": "0c32787e936099a79622c5eef1b5df76"
        }
      ]
    }
  ]
}
