{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0.jar",
          "url": "honoka-kotlin-utils-2.0.0.jar",
          "size": 8519,
          "sha512": "8ac9fc976b7e9efe5573282cbb2ef69cb35654858f367c07b1276721fed8818304171a06666d47c75c191416a0a0c83672f5ad344ce5195a9b8671f4539c18e0",
          "sha256": "e7d57696f05f1a59997e8cf0048d8c58a5400c4d08d090d34ef3f1a4f171a579",
          "sha1": "c10c09750d764b3edb9b84ab8bcf882c1123df65",
          "md5": "9d7c091d08110fa2a88efba98ce7612a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0.jar",
          "url": "honoka-kotlin-utils-2.0.0.jar",
          "size": 8519,
          "sha512": "8ac9fc976b7e9efe5573282cbb2ef69cb35654858f367c07b1276721fed8818304171a06666d47c75c191416a0a0c83672f5ad344ce5195a9b8671f4539c18e0",
          "sha256": "e7d57696f05f1a59997e8cf0048d8c58a5400c4d08d090d34ef3f1a4f171a579",
          "sha1": "c10c09750d764b3edb9b84ab8bcf882c1123df65",
          "md5": "9d7c091d08110fa2a88efba98ce7612a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.0-sources.jar",
          "url": "honoka-kotlin-utils-2.0.0-sources.jar",
          "size": 3854,
          "sha512": "9f4a33c24b7193f5d720a4fadc58783f5f46e891e9a39eeba99c66cba86b5c22c0b74b9ef6f68d320bff7bde156808f2b593b7153a77ba2acc82bdcd6ef8996b",
          "sha256": "b46a59ee322777637ab4acb7b813bfe2df54dad1d7173cef7c2aa163252e3cd2",
          "sha1": "562e382f3a55cef2606e389d206633467058ab70",
          "md5": "5af1ea3fbea4dd9d004769cf8e1db50a"
        }
      ]
    }
  ]
}
