{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.3.jar",
          "url": "qqrobot-framework-api-1.0.3.jar",
          "size": 8552,
          "sha512": "22c743f516f000fce311371041cd305d9cca53c1fde503763d03330e615888d4c9daa8a091d781abc9dd5169d3c54fd2a51692d4e71b0c3aa582e09c1c3bb4bd",
          "sha256": "7e5531844109add3b562d53d6a5e433d9330f8a80397c5e58aa50a760af3c7c5",
          "sha1": "bd4c3fbd654847119f5a1d6abcef3a047106a855",
          "md5": "f14bafcb418abaa6e2428fccc93fb6b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.3.jar",
          "url": "qqrobot-framework-api-1.0.3.jar",
          "size": 8552,
          "sha512": "22c743f516f000fce311371041cd305d9cca53c1fde503763d03330e615888d4c9daa8a091d781abc9dd5169d3c54fd2a51692d4e71b0c3aa582e09c1c3bb4bd",
          "sha256": "7e5531844109add3b562d53d6a5e433d9330f8a80397c5e58aa50a760af3c7c5",
          "sha1": "bd4c3fbd654847119f5a1d6abcef3a047106a855",
          "md5": "f14bafcb418abaa6e2428fccc93fb6b0"
        }
      ]
    }
  ]
}
