{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.3.jar",
          "url": "qqrobot-framework-api-1.0.3.jar",
          "size": 8476,
          "sha512": "203c9ed6ba12047884b6ee1ad135907723938152d32690d13c275130292f8df0f76523499e3ac951ceb37a70ea377a569b7731745f551a7261de3a28c7ce9cdc",
          "sha256": "843d86b1190144107817358ecc6b453e01547f75eb88d6a5249128714c3c1aec",
          "sha1": "32e7471fff3fd4286e78b9c001bc3395f11b1673",
          "md5": "04a4315dc866d2867f43024755006be2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.3.jar",
          "url": "qqrobot-framework-api-1.0.3.jar",
          "size": 8476,
          "sha512": "203c9ed6ba12047884b6ee1ad135907723938152d32690d13c275130292f8df0f76523499e3ac951ceb37a70ea377a569b7731745f551a7261de3a28c7ce9cdc",
          "sha256": "843d86b1190144107817358ecc6b453e01547f75eb88d6a5249128714c3c1aec",
          "sha1": "32e7471fff3fd4286e78b9c001bc3395f11b1673",
          "md5": "04a4315dc866d2867f43024755006be2"
        }
      ]
    }
  ]
}
