{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.3.jar",
          "url": "qqrobot-framework-api-1.0.3.jar",
          "size": 8552,
          "sha512": "807be2c0e4390f865d294f2d0738382b80133c1a40ef14d1f7433f92eb8a6ecf703fc2dbaaba90403eb4f051e11cdf78f9c8a2cb6293c5c3c9b28b0155fe3165",
          "sha256": "a194bce3565c678466f39aef6e218bef79c1d2793bfa7f0a205f6b59c0c5ce61",
          "sha1": "da6aec00b59a1bed1a75e12041e165dc7bbdaa02",
          "md5": "2ec8a0b069292b067c259d4d2a39edfa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.3.jar",
          "url": "qqrobot-framework-api-1.0.3.jar",
          "size": 8552,
          "sha512": "807be2c0e4390f865d294f2d0738382b80133c1a40ef14d1f7433f92eb8a6ecf703fc2dbaaba90403eb4f051e11cdf78f9c8a2cb6293c5c3c9b28b0155fe3165",
          "sha256": "a194bce3565c678466f39aef6e218bef79c1d2793bfa7f0a205f6b59c0c5ce61",
          "sha1": "da6aec00b59a1bed1a75e12041e165dc7bbdaa02",
          "md5": "2ec8a0b069292b067c259d4d2a39edfa"
        }
      ]
    }
  ]
}
