{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.2.jar",
          "url": "qqrobot-framework-api-1.0.2.jar",
          "size": 8417,
          "sha512": "7fd05a8d28c29acf8c81e254c317f8fbc5dd74aa06c811d2678d1b9cac1d602c4727e035faf01d4e7b585f7be6b823d5e13a4184638c7d84a7be1900137b2a87",
          "sha256": "bcdf7fe27a6948e6b800eac540df163a38df331e27356a8ad6af6865be8dc478",
          "sha1": "7ad6119658896f7d6c7b15233cd50288a1b72a7a",
          "md5": "b4b73a548ac28612fe05e01ea16040e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-1.0.2.jar",
          "url": "qqrobot-framework-api-1.0.2.jar",
          "size": 8417,
          "sha512": "7fd05a8d28c29acf8c81e254c317f8fbc5dd74aa06c811d2678d1b9cac1d602c4727e035faf01d4e7b585f7be6b823d5e13a4184638c7d84a7be1900137b2a87",
          "sha256": "bcdf7fe27a6948e6b800eac540df163a38df331e27356a8ad6af6865be8dc478",
          "sha1": "7ad6119658896f7d6c7b15233cd50288a1b72a7a",
          "md5": "b4b73a548ac28612fe05e01ea16040e5"
        }
      ]
    }
  ]
}
