{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.1.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.3-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.2-dev.jar",
          "url": "honoka-kotlin-utils-1.1.2-dev.jar",
          "size": 71269,
          "sha512": "8411e3ca5593036a4fb960c2d86453ca0c8a49bb806daaf7f4f6c548c0ab885fcdfb413013f1fb670abf02c00bb677798df5a6557605a34b53d9e06db7798c57",
          "sha256": "ac092232f8cbb2cbb530b75f43261d225dafdc7b21671978f9b8846241220f79",
          "sha1": "b7e14e6b2370c290e7401f74c1fce0bcb04c499f",
          "md5": "a9d13de62464f095934686acf223af2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.3-dev"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.2-dev.jar",
          "url": "honoka-kotlin-utils-1.1.2-dev.jar",
          "size": 71269,
          "sha512": "8411e3ca5593036a4fb960c2d86453ca0c8a49bb806daaf7f4f6c548c0ab885fcdfb413013f1fb670abf02c00bb677798df5a6557605a34b53d9e06db7798c57",
          "sha256": "ac092232f8cbb2cbb530b75f43261d225dafdc7b21671978f9b8846241220f79",
          "sha1": "b7e14e6b2370c290e7401f74c1fce0bcb04c499f",
          "md5": "a9d13de62464f095934686acf223af2b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.2-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.2-dev-sources.jar",
          "size": 17154,
          "sha512": "2fcdb9af07d8091a93fd2effdd34bc0892878e2fdbf9d82c99906b44afb2594d57f58c9e3d9ee0ee8c586bebcc21c1d75f29364b28696edbc2e12f0f8296c507",
          "sha256": "cd19a5e611625d5a5e59eca414ffb67120c6b08f177fa62505579b1685974d9d",
          "sha1": "f0167cf45595237193aef167718399ce417c4054",
          "md5": "22e918b5d6c191b40fce96c92d14a4f2"
        }
      ]
    }
  ]
}
