{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.1.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.3-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.2-dev.jar",
          "url": "honoka-kotlin-utils-1.1.2-dev.jar",
          "size": 72309,
          "sha512": "bb0dc3508681f307ab5d61ef96dcb2cf1ff3e7e1845794d044c3d25f8132b6a134b43b7f3d949345b228b1fb52e41486b65ec53bb85621cddf6e656f7e1b084c",
          "sha256": "7347a770f60bfce13087086a90d6d7eafc0230e99bdeb1e0aa0394455cf7ed37",
          "sha1": "ab02faa82f51e950c386b7a0fd86cedfa865317b",
          "md5": "dfd4922000f059d3cce1354009477bf5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.3-dev"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.2-dev.jar",
          "url": "honoka-kotlin-utils-1.1.2-dev.jar",
          "size": 72309,
          "sha512": "bb0dc3508681f307ab5d61ef96dcb2cf1ff3e7e1845794d044c3d25f8132b6a134b43b7f3d949345b228b1fb52e41486b65ec53bb85621cddf6e656f7e1b084c",
          "sha256": "7347a770f60bfce13087086a90d6d7eafc0230e99bdeb1e0aa0394455cf7ed37",
          "sha1": "ab02faa82f51e950c386b7a0fd86cedfa865317b",
          "md5": "dfd4922000f059d3cce1354009477bf5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.2-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.2-dev-sources.jar",
          "size": 17910,
          "sha512": "f6464c8aff54bbc5a97c663e12a96ce14115afd763bef652c01d39ef82145b24e3f00169838ce5441204dda536cffa3e0f4d734d4f0c36987b2f522faa031b02",
          "sha256": "760c9e395e2a43d9639adf6e769c4c912965459f3266560f351e7696dbca0048",
          "sha1": "e2ca4d3f50793090898d1faed3ebc3976425ec94",
          "md5": "c2473dad9a1ba7b60403e2bb8e0eb27d"
        }
      ]
    }
  ]
}
