{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.1.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.3-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.2-dev.jar",
          "url": "honoka-kotlin-utils-1.1.2-dev.jar",
          "size": 71269,
          "sha512": "c5b8e15c55af83c52a0f8a4b2f22ffbab0319e426eecaf95980418b5321e2b14b93e394441e5f45c9d0db635fe5b04eeb500d12d16c5233464b30d33e85b1c3a",
          "sha256": "02ffc6a409fa883582da0f0dd948ac711448601d7cdf6caf400bcdb10bdc7ff6",
          "sha1": "87b1aa24b1088c878aa02691c13a9f60cf74095d",
          "md5": "42f536fe914b9e81f30e8e9c94cde2ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.3-dev"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.2-dev.jar",
          "url": "honoka-kotlin-utils-1.1.2-dev.jar",
          "size": 71269,
          "sha512": "c5b8e15c55af83c52a0f8a4b2f22ffbab0319e426eecaf95980418b5321e2b14b93e394441e5f45c9d0db635fe5b04eeb500d12d16c5233464b30d33e85b1c3a",
          "sha256": "02ffc6a409fa883582da0f0dd948ac711448601d7cdf6caf400bcdb10bdc7ff6",
          "sha1": "87b1aa24b1088c878aa02691c13a9f60cf74095d",
          "md5": "42f536fe914b9e81f30e8e9c94cde2ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.2-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.2-dev-sources.jar",
          "size": 17154,
          "sha512": "d0d8ed1225a77371ff0af45fd65f3fa62401468b63ef3867d29aacb58eaad4895b9b9cdcce610b478cd7bd35a3a45d0a59b02b38c599284cba154025ae3c3a4f",
          "sha256": "65df1c62c64a1afcca98d5e435cfeddc8fc7be8e7e93b417f15dd632de072c3d",
          "sha1": "68a73ae311fe73a54d1e8289ce1110b67b109b83",
          "md5": "7d4c6a18a4f9fcfa2c789c1dde48570f"
        }
      ]
    }
  ]
}
