{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle",
    "module": "honoka-gradle-utils",
    "version": "1.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.0-dev.jar",
          "url": "honoka-gradle-utils-1.0.0-dev.jar",
          "size": 21839,
          "sha512": "16ce85d0b90b86883830841121d99b181923684b67ff2e1b96f76d74ff223139c4eb70bcec75929158927d080a659922f0a721d22b2607e5f78c1c13672d2466",
          "sha256": "fbe386ef256f57b6ffc0e3ecec58cf982f38375c4369977fa2b2bbce29fb6b74",
          "sha1": "320789ff68b6c76e1d2d152850a71b67e0bf05e1",
          "md5": "dae9a6026c4551e888a6af875098870d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.0-dev.jar",
          "url": "honoka-gradle-utils-1.0.0-dev.jar",
          "size": 21839,
          "sha512": "16ce85d0b90b86883830841121d99b181923684b67ff2e1b96f76d74ff223139c4eb70bcec75929158927d080a659922f0a721d22b2607e5f78c1c13672d2466",
          "sha256": "fbe386ef256f57b6ffc0e3ecec58cf982f38375c4369977fa2b2bbce29fb6b74",
          "sha1": "320789ff68b6c76e1d2d152850a71b67e0bf05e1",
          "md5": "dae9a6026c4551e888a6af875098870d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.0-dev-sources.jar",
          "url": "honoka-gradle-utils-1.0.0-dev-sources.jar",
          "size": 4304,
          "sha512": "4dbcabf3d77f68908503083759514415f2d1158c2c9cbb3c76ec1d127202e97269cac24f17edb129de71559af6b0acf3a5749598e77fccc9eb29fee55cebcb98",
          "sha256": "d6149cb44197c729986c878419dbbbe88782f5bb0d14ac5d6f719cff1eb71417",
          "sha1": "b2645b63a9840b80b11e3e8c0ead3f6295ec24d9",
          "md5": "11b2e945de99c3c39e4fe0b7f99da872"
        }
      ]
    }
  ]
}
