{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle",
    "module": "honoka-gradle-utils",
    "version": "1.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.0-dev.jar",
          "url": "honoka-gradle-utils-1.0.0-dev.jar",
          "size": 15856,
          "sha512": "77b851704e595e92bb98d44e2c3df32b1e8596600eb219342048dfa8371fb31ef6413b3c7b7044dec101c6a47d07e94310c05633ccedfc81b99cb7835db82bc3",
          "sha256": "8c2c3b1e93552089511e0ea80ecb72a96188eb3acf0b229a9eee8a226ed2ea48",
          "sha1": "d73a18be0dbaaab1355f29b1c4080f6aed75e561",
          "md5": "352c4c636483733d9f269fd962c4b002"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.0-dev.jar",
          "url": "honoka-gradle-utils-1.0.0-dev.jar",
          "size": 15856,
          "sha512": "77b851704e595e92bb98d44e2c3df32b1e8596600eb219342048dfa8371fb31ef6413b3c7b7044dec101c6a47d07e94310c05633ccedfc81b99cb7835db82bc3",
          "sha256": "8c2c3b1e93552089511e0ea80ecb72a96188eb3acf0b229a9eee8a226ed2ea48",
          "sha1": "d73a18be0dbaaab1355f29b1c4080f6aed75e561",
          "md5": "352c4c636483733d9f269fd962c4b002"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.0-dev-sources.jar",
          "url": "honoka-gradle-utils-1.0.0-dev-sources.jar",
          "size": 3850,
          "sha512": "e31c2a2c752f404ca1c6337694cf60c1a21aba07c6f8dd739a18296930a9a6d0577bf57debe0e775c7e6c122bdc555e6a0aeb219f9050b0017f87c91c6fa0039",
          "sha256": "d2f380a2da7eab981d58340847ea480fc48e36f368c752ec743af33a8fd396cd",
          "sha1": "d32c463fc6b10eee9fcf40a7560f84e8d9d33bbf",
          "md5": "6f8026489a6ea3f623e7bc2826e11da7"
        }
      ]
    }
  ]
}
