{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle",
    "module": "honoka-gradle-utils",
    "version": "1.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.0-dev.jar",
          "url": "honoka-gradle-utils-1.0.0-dev.jar",
          "size": 15856,
          "sha512": "f4f64c84ff4e63b46d8af50748d63e127f685681c6a57fcffc2eeab2cdb7778e24f854f7d7631752aeb3f142e26c031ff9340cca8cf4471f279b0de583a1943d",
          "sha256": "f1a15e50cb6ca437457b85e36b04f17343d1324d6b1c0923a3b1d551931c20bd",
          "sha1": "1105ac38a59d1c1dd717e99c916da6c0c78397d8",
          "md5": "dfee02888dcfbf586b446135794dd111"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.0-dev.jar",
          "url": "honoka-gradle-utils-1.0.0-dev.jar",
          "size": 15856,
          "sha512": "f4f64c84ff4e63b46d8af50748d63e127f685681c6a57fcffc2eeab2cdb7778e24f854f7d7631752aeb3f142e26c031ff9340cca8cf4471f279b0de583a1943d",
          "sha256": "f1a15e50cb6ca437457b85e36b04f17343d1324d6b1c0923a3b1d551931c20bd",
          "sha1": "1105ac38a59d1c1dd717e99c916da6c0c78397d8",
          "md5": "dfee02888dcfbf586b446135794dd111"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.0-dev-sources.jar",
          "url": "honoka-gradle-utils-1.0.0-dev-sources.jar",
          "size": 3850,
          "sha512": "a81a956e0edd94bfaaa7bcac4883a1155fb24fd4dd2e1c766f666ddf4dc7b56ca7dee14b6af9872f68aa5f4b40638273ff773488480848d52d26a3ce9ab62d24",
          "sha256": "dabe2cd2a254cf581b5eec85c876d0bda8111f7ed366aadd84b124dab7bb9129",
          "sha1": "cf6a9394959e00fc3239aae330c911e1f0ce9827",
          "md5": "01a09844c0ba30ab97bd83576125745c"
        }
      ]
    }
  ]
}
