{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle",
    "module": "honoka-gradle-utils",
    "version": "1.0.4-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.4-dev.jar",
          "url": "honoka-gradle-utils-1.0.4-dev.jar",
          "size": 25176,
          "sha512": "d1a1555534efac525dfa06d5b5ecc3564d53cb63eccb6d0e2b79c8102927a400f9089f646bc431085f989e3ab857b15d67a971449ef7e7898356cad9b424557f",
          "sha256": "27fe958ed724e0130cf407b41cdc74a7ed8cda75e5c05b1af3da760d620e8df6",
          "sha1": "26cfecf30e8f6e43a8305e6e79eea1e2347e636a",
          "md5": "98ebf30444c10eb0825f13f6dbbbad48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.4-dev.jar",
          "url": "honoka-gradle-utils-1.0.4-dev.jar",
          "size": 25176,
          "sha512": "d1a1555534efac525dfa06d5b5ecc3564d53cb63eccb6d0e2b79c8102927a400f9089f646bc431085f989e3ab857b15d67a971449ef7e7898356cad9b424557f",
          "sha256": "27fe958ed724e0130cf407b41cdc74a7ed8cda75e5c05b1af3da760d620e8df6",
          "sha1": "26cfecf30e8f6e43a8305e6e79eea1e2347e636a",
          "md5": "98ebf30444c10eb0825f13f6dbbbad48"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.4-dev-sources.jar",
          "url": "honoka-gradle-utils-1.0.4-dev-sources.jar",
          "size": 5199,
          "sha512": "434c334a150854ccc72ded0b3ef196be739dfe30da01d0697fa3e35c4203eb4b8d510a14e44e77a8c819f19f3f22e5665d5a9c3aed7ebc081586de5834cf8d6e",
          "sha256": "7f4f3093f10bc3b369213b08ff94c8487d398d4ef279836e8841d678e7db2a5f",
          "sha1": "ab7f438b2d8a4ba3c5fb0f41565168ac0115baee",
          "md5": "d2de6c5518b54b4ad1b0fb4e410c3bf5"
        }
      ]
    }
  ]
}
