{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle",
    "module": "honoka-gradle-utils",
    "version": "1.0.4-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.4-dev.jar",
          "url": "honoka-gradle-utils-1.0.4-dev.jar",
          "size": 25287,
          "sha512": "e8249671f2f95b574431a35361e7b06463109e1f8722d21494e0d64f7d286881932c81dfec56c8c1960ebe35b1637fbc98ad7e437e03d75b42b0931f16aada9f",
          "sha256": "fa9d886fd92106726d1c70b66d44f52d38f982406db07e723710cc92dd30b839",
          "sha1": "a9c921f4d866bf35b9b683e5d3f1e733d4df4e5b",
          "md5": "45954eb63de587414e962b96dd8e7c49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.4-dev.jar",
          "url": "honoka-gradle-utils-1.0.4-dev.jar",
          "size": 25287,
          "sha512": "e8249671f2f95b574431a35361e7b06463109e1f8722d21494e0d64f7d286881932c81dfec56c8c1960ebe35b1637fbc98ad7e437e03d75b42b0931f16aada9f",
          "sha256": "fa9d886fd92106726d1c70b66d44f52d38f982406db07e723710cc92dd30b839",
          "sha1": "a9c921f4d866bf35b9b683e5d3f1e733d4df4e5b",
          "md5": "45954eb63de587414e962b96dd8e7c49"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.4-dev-sources.jar",
          "url": "honoka-gradle-utils-1.0.4-dev-sources.jar",
          "size": 5199,
          "sha512": "434c334a150854ccc72ded0b3ef196be739dfe30da01d0697fa3e35c4203eb4b8d510a14e44e77a8c819f19f3f22e5665d5a9c3aed7ebc081586de5834cf8d6e",
          "sha256": "7f4f3093f10bc3b369213b08ff94c8487d398d4ef279836e8841d678e7db2a5f",
          "sha1": "ab7f438b2d8a4ba3c5fb0f41565168ac0115baee",
          "md5": "d2de6c5518b54b4ad1b0fb4e410c3bf5"
        }
      ]
    }
  ]
}
