{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle",
    "module": "honoka-gradle-utils",
    "version": "1.0.4-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.4-dev.jar",
          "url": "honoka-gradle-utils-1.0.4-dev.jar",
          "size": 25178,
          "sha512": "5f763b54b6fd7f802b8df729f41bd74cbee3230063ede0769d1de251bf0b644323de8a2dc416665569d0e3a4def3afcdc9d109c848e78864ccd1d1bc75e4d329",
          "sha256": "c749974eabbf948eae4779e81bd8c5f6bbbfedc54644666aaba125194de926f8",
          "sha1": "84bbd878833647f8f8a388ba858f93363fc48b37",
          "md5": "89e568bc74a7097bc3283801479909a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.4-dev.jar",
          "url": "honoka-gradle-utils-1.0.4-dev.jar",
          "size": 25178,
          "sha512": "5f763b54b6fd7f802b8df729f41bd74cbee3230063ede0769d1de251bf0b644323de8a2dc416665569d0e3a4def3afcdc9d109c848e78864ccd1d1bc75e4d329",
          "sha256": "c749974eabbf948eae4779e81bd8c5f6bbbfedc54644666aaba125194de926f8",
          "sha1": "84bbd878833647f8f8a388ba858f93363fc48b37",
          "md5": "89e568bc74a7097bc3283801479909a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.4-dev-sources.jar",
          "url": "honoka-gradle-utils-1.0.4-dev-sources.jar",
          "size": 5199,
          "sha512": "434c334a150854ccc72ded0b3ef196be739dfe30da01d0697fa3e35c4203eb4b8d510a14e44e77a8c819f19f3f22e5665d5a9c3aed7ebc081586de5834cf8d6e",
          "sha256": "7f4f3093f10bc3b369213b08ff94c8487d398d4ef279836e8841d678e7db2a5f",
          "sha1": "ab7f438b2d8a4ba3c5fb0f41565168ac0115baee",
          "md5": "d2de6c5518b54b4ad1b0fb4e410c3bf5"
        }
      ]
    }
  ]
}
