{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-json-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "honoka-json-api-1.0.0.jar",
          "url": "honoka-json-api-1.0.0.jar",
          "size": 7627,
          "sha512": "08c86c841d4721a45b8606c7c4f9ab117ac9d03c4087ef00d4cbccef72927a784195a47da1009469aa0f0228b9e0b6fc69f35420b0f8ee82451fdf63330c6f69",
          "sha256": "0e494b692d30a162abea6e675e1134a14bddbd015ecf56739aa870d0ae07fcea",
          "sha1": "8def7d15f36536268b1acc758baece99827815ce",
          "md5": "7d7eff38f1660917c99c18f7e9a1508a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-api-1.0.0.jar",
          "url": "honoka-json-api-1.0.0.jar",
          "size": 7627,
          "sha512": "08c86c841d4721a45b8606c7c4f9ab117ac9d03c4087ef00d4cbccef72927a784195a47da1009469aa0f0228b9e0b6fc69f35420b0f8ee82451fdf63330c6f69",
          "sha256": "0e494b692d30a162abea6e675e1134a14bddbd015ecf56739aa870d0ae07fcea",
          "sha1": "8def7d15f36536268b1acc758baece99827815ce",
          "md5": "7d7eff38f1660917c99c18f7e9a1508a"
        }
      ]
    }
  ]
}
