{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender",
    "module": "lavender-api",
    "version": "1.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "lavender-api-1.0.1-dev.jar",
          "url": "lavender-api-1.0.1-dev.jar",
          "size": 39490,
          "sha512": "0f1d05ea9e8d7238cc46beb9db89cb8dfc937d7a68bbfbce2c98dd3f3b8faeca60784c7467275039f11ffc778bcf6c0607f883c7c6a4ceacd3326155ee0414e8",
          "sha256": "a3ab85512bdf75a996564047397e493e950796848cff89e00c38ac641f9d6598",
          "sha1": "6101bbf66e0d4ff63c8a0f9de01129494fb811ff",
          "md5": "7d51036183769e94e680c16edb7f717b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "lavender-api-1.0.1-dev.jar",
          "url": "lavender-api-1.0.1-dev.jar",
          "size": 39490,
          "sha512": "0f1d05ea9e8d7238cc46beb9db89cb8dfc937d7a68bbfbce2c98dd3f3b8faeca60784c7467275039f11ffc778bcf6c0607f883c7c6a4ceacd3326155ee0414e8",
          "sha256": "a3ab85512bdf75a996564047397e493e950796848cff89e00c38ac641f9d6598",
          "sha1": "6101bbf66e0d4ff63c8a0f9de01129494fb811ff",
          "md5": "7d51036183769e94e680c16edb7f717b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavender-api-1.0.1-dev-sources.jar",
          "url": "lavender-api-1.0.1-dev-sources.jar",
          "size": 5858,
          "sha512": "c14587ba17d0fc653e935ab5c3c8bf6636288f179e3526fdb97617ee0c1b3ad176c22b15df0eead618f898a7f71f3bef1d8042558ea4ddc981693f132cca9949",
          "sha256": "70487cf66246d7ac4982d876f0751831b07b7018b571739e0427f12e481599ee",
          "sha1": "f9b2ee577ab3c715386032c74b46d63a85eb0d7d",
          "md5": "1f62612e2c0fbd3bfe1183a05e934654"
        }
      ]
    }
  ]
}
