{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender",
    "module": "lavender-api",
    "version": "1.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "lavender-api-1.0.1-dev.jar",
          "url": "lavender-api-1.0.1-dev.jar",
          "size": 39492,
          "sha512": "31e9c06766476ec7254cc76456809ce055f5dc91a576f0909cd36c1352a73c37a782833e87c7d80f24d4134eb8a20605b391f7513869628191181b2a77df1684",
          "sha256": "76f13ab47d7a3c4f29ed16b895ea66f5948f957b17ce4c9d6f83968e17329eca",
          "sha1": "1c5899f493d76b77bd8a5acda0a7012f6dc4af7d",
          "md5": "cff056219d13892bf3eeb2e9630f45ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "lavender-api-1.0.1-dev.jar",
          "url": "lavender-api-1.0.1-dev.jar",
          "size": 39492,
          "sha512": "31e9c06766476ec7254cc76456809ce055f5dc91a576f0909cd36c1352a73c37a782833e87c7d80f24d4134eb8a20605b391f7513869628191181b2a77df1684",
          "sha256": "76f13ab47d7a3c4f29ed16b895ea66f5948f957b17ce4c9d6f83968e17329eca",
          "sha1": "1c5899f493d76b77bd8a5acda0a7012f6dc4af7d",
          "md5": "cff056219d13892bf3eeb2e9630f45ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavender-api-1.0.1-dev-sources.jar",
          "url": "lavender-api-1.0.1-dev-sources.jar",
          "size": 5862,
          "sha512": "118662394972ff4a21d6e8d044bdbdc86ec91bbc1966958c9cb03e03326534494b12f9e02e2e0d052f2c346e4647daf461d420bf3af694954734786329a50b2d",
          "sha256": "79266322b0e0de6981ac2dba47f99a6873cde3a6c538a44f6591fd992c242e3a",
          "sha1": "91a51715b45cc7a53eb5656f94fdeaa89c07fd3d",
          "md5": "082b769f6982a9655e0e47d0f14147d7"
        }
      ]
    }
  ]
}
