{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "2.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "2.0.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-2.0.0-dev.jar",
          "url": "honoka-spring-boot-starter-2.0.0-dev.jar",
          "size": 45304,
          "sha512": "2ad16d5744915e4190dbe7b2234f96e1456196ea01662dd30b1ba1354c20cda79dabbcd0d8aa42c7c86f51c4b846ab4cb581b0f1efa23dc771e8bbfbd833e31c",
          "sha256": "df39e444e6e64facca2607d0d996faef49e56c1024b14e08ec0205213a1dee29",
          "sha1": "67cce22692b54146a2717185b81286e2e1e22acc",
          "md5": "03f49aa4cb9e8a015c795f755a6c1a47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "2.0.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-2.0.0-dev.jar",
          "url": "honoka-spring-boot-starter-2.0.0-dev.jar",
          "size": 45304,
          "sha512": "2ad16d5744915e4190dbe7b2234f96e1456196ea01662dd30b1ba1354c20cda79dabbcd0d8aa42c7c86f51c4b846ab4cb581b0f1efa23dc771e8bbfbd833e31c",
          "sha256": "df39e444e6e64facca2607d0d996faef49e56c1024b14e08ec0205213a1dee29",
          "sha1": "67cce22692b54146a2717185b81286e2e1e22acc",
          "md5": "03f49aa4cb9e8a015c795f755a6c1a47"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-2.0.0-dev-sources.jar",
          "url": "honoka-spring-boot-starter-2.0.0-dev-sources.jar",
          "size": 16621,
          "sha512": "6ecd755007545a4cc4154aa5f6a7c888d815d90eafd660935ea3291d8fc842203442f3bcfeb2cbac8a7d78dcaa96d40a4db8bb04e61fbc8e7bf84cbc680228f5",
          "sha256": "b8a13d968b868e6e0bed0debb5e0d8285462c4285375359a0b520c6ea0a85a2c",
          "sha1": "468f04f3cd924b16ab7c7869543b82d10daaade3",
          "md5": "c47c822e6ae72e168533dce8539f924b"
        }
      ]
    }
  ]
}
