{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "2.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "2.0.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-2.0.0-dev.jar",
          "url": "honoka-spring-boot-starter-2.0.0-dev.jar",
          "size": 51740,
          "sha512": "aedd545eeb6e36551d3af75c8e2b759bf071a5ef9e195e9f0d84b86215c4b11d741a89e9635a9a193519f9653e1b6cc054f8878fd72bdf162cb4c0535958e1fa",
          "sha256": "5c30dccb12e9f50341b511b8c47a621a88d2aa27788d094859420b3fc357991e",
          "sha1": "11214d413c4fe81f12b87e9d3b9aadf4da3295be",
          "md5": "393242b743b62d1f20465d2ab9d85a73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "2.0.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-2.0.0-dev.jar",
          "url": "honoka-spring-boot-starter-2.0.0-dev.jar",
          "size": 51740,
          "sha512": "aedd545eeb6e36551d3af75c8e2b759bf071a5ef9e195e9f0d84b86215c4b11d741a89e9635a9a193519f9653e1b6cc054f8878fd72bdf162cb4c0535958e1fa",
          "sha256": "5c30dccb12e9f50341b511b8c47a621a88d2aa27788d094859420b3fc357991e",
          "sha1": "11214d413c4fe81f12b87e9d3b9aadf4da3295be",
          "md5": "393242b743b62d1f20465d2ab9d85a73"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-2.0.0-dev-sources.jar",
          "url": "honoka-spring-boot-starter-2.0.0-dev-sources.jar",
          "size": 18539,
          "sha512": "7bd37e528e3688f34ebdf5d6a3cd43c5f5cd3d125f3d5ac3afc6ed9a255e7f9ef13d01817e8d2aad3e18add0203f18d19d8ccda71ac063f508ff08d991f8cefc",
          "sha256": "dfb8398b0edd33e6f2c19b350c1185c569b9e1e40848030f78a674089b895f94",
          "sha1": "6bb3eb8cdf39aa8444cf98c69f2e379983c0f9bd",
          "md5": "a10ea21dd8394d7091bd3899ac269bc4"
        }
      ]
    }
  ]
}
