{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "2.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "2.0.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-2.0.0-dev.jar",
          "url": "honoka-spring-boot-starter-2.0.0-dev.jar",
          "size": 51740,
          "sha512": "f6d59d9e9a411860620fc1e4ca5414a07dc0a78f47ba1f3880eb9e719d043b9aaa06fb7bbf36ff91e868c04f5aed2e175c346b42f0850376a74dcc1af3e17796",
          "sha256": "103d157e3ff5efbfd1eb7d80f2ff16990d935fd39deeb84932aa3baa73a1b5f3",
          "sha1": "603cafd9e8f4a7e280510773bbaf539723efc22a",
          "md5": "d8850fb0f10cb81a6adce1e817ac7b7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "2.0.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-2.0.0-dev.jar",
          "url": "honoka-spring-boot-starter-2.0.0-dev.jar",
          "size": 51740,
          "sha512": "f6d59d9e9a411860620fc1e4ca5414a07dc0a78f47ba1f3880eb9e719d043b9aaa06fb7bbf36ff91e868c04f5aed2e175c346b42f0850376a74dcc1af3e17796",
          "sha256": "103d157e3ff5efbfd1eb7d80f2ff16990d935fd39deeb84932aa3baa73a1b5f3",
          "sha1": "603cafd9e8f4a7e280510773bbaf539723efc22a",
          "md5": "d8850fb0f10cb81a6adce1e817ac7b7f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-2.0.0-dev-sources.jar",
          "url": "honoka-spring-boot-starter-2.0.0-dev-sources.jar",
          "size": 18539,
          "sha512": "b8633e818000c2bc3cc1a95519bbd0acb6b0d0216811bdba0f058803ea5f450ab2e1de6dd32753a452357fea4a13f8600c373f8e0c767569608cc728650c64c0",
          "sha256": "9a35fb2658342a7c4df90f471fe2164df1344dc16238acb3e8a9c36f0528ae0e",
          "sha1": "b6fe54a4dd2adcbac6597c10976c7436842b0097",
          "md5": "13d2674bf2de28651a1b9c03f237623f"
        }
      ]
    }
  ]
}
