{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-framework-utils",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.4.jar",
          "url": "honoka-framework-utils-1.0.4.jar",
          "size": 16868,
          "sha512": "ba00a7dd7c9f34a3d3e158319c7980d677cbdf754d002505adac192e0c00fe239b93b83bf47587ea76242bc25bdca2637c83ed79900bd2e3f0175aad04883d69",
          "sha256": "019d125d7853b0776c84342ab3b0bb67b69be0ea686c56517141eb5a277a8925",
          "sha1": "b5de612787a8f11e9071ad352185954f25a34239",
          "md5": "b94a9d963ad1b1cc4bcb4af613b95a8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.4.jar",
          "url": "honoka-framework-utils-1.0.4.jar",
          "size": 16868,
          "sha512": "ba00a7dd7c9f34a3d3e158319c7980d677cbdf754d002505adac192e0c00fe239b93b83bf47587ea76242bc25bdca2637c83ed79900bd2e3f0175aad04883d69",
          "sha256": "019d125d7853b0776c84342ab3b0bb67b69be0ea686c56517141eb5a277a8925",
          "sha1": "b5de612787a8f11e9071ad352185954f25a34239",
          "md5": "b94a9d963ad1b1cc4bcb4af613b95a8f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.4-sources.jar",
          "url": "honoka-framework-utils-1.0.4-sources.jar",
          "size": 10546,
          "sha512": "3bd93faed053d898c7a46d75f0fe6fc8e0c18bc45d57b9d4e9a3c2b86ffab4391eea862ac4794acb6e9c9a6b68eee909a42dfb7d599f78f9d647767b951a69c1",
          "sha256": "7ca8d41bd876c1559b0f1cca050a76b3cef3a334a6e992db19fc9afb24fc6493",
          "sha1": "368705da528637699623773078f41f990379ec73",
          "md5": "544e8b1032ce477a89dec1e7ebaa152c"
        }
      ]
    }
  ]
}
