{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-framework-utils",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.4.jar",
          "url": "honoka-framework-utils-1.0.4.jar",
          "size": 16868,
          "sha512": "bed71557ef7f1ad2e065d1654a3ebb6f9e6d4018a5d284582ca525ca318a71be44a18585da2995d3df8719f4746da7ce3c044fa445e4a463b6bccbcaaf1e89b1",
          "sha256": "c3135de87e247c005526b4e70f8cdde794fdeaa971e5dc95a3c811f7bb3ae28e",
          "sha1": "c8329cbffa3a7d055389d45ad3457deab6181551",
          "md5": "ef6f5c4a79546ed3536b75f90e6f25ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.4.jar",
          "url": "honoka-framework-utils-1.0.4.jar",
          "size": 16868,
          "sha512": "bed71557ef7f1ad2e065d1654a3ebb6f9e6d4018a5d284582ca525ca318a71be44a18585da2995d3df8719f4746da7ce3c044fa445e4a463b6bccbcaaf1e89b1",
          "sha256": "c3135de87e247c005526b4e70f8cdde794fdeaa971e5dc95a3c811f7bb3ae28e",
          "sha1": "c8329cbffa3a7d055389d45ad3457deab6181551",
          "md5": "ef6f5c4a79546ed3536b75f90e6f25ce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.4-sources.jar",
          "url": "honoka-framework-utils-1.0.4-sources.jar",
          "size": 10546,
          "sha512": "dfcf185a85d18de7b5c23ab960e9cf92d699cb7aecb13ea39a501bd63e70485b6b1543fee4a00e8542a7ac4d3f19f2b007549a4480b93221b74ad21efa13cffa",
          "sha256": "c5c53d883570e0d15b3598f93ae940e68f559ceb269f1dab9d42edbfb7d76f0f",
          "sha1": "00560ebb93d68eb40ebad36353d8ab1448e9d540",
          "md5": "43b236e4f1722c2cf814602fdfdd7762"
        }
      ]
    }
  ]
}
