{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-framework-utils",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.4.jar",
          "url": "honoka-framework-utils-1.0.4.jar",
          "size": 16868,
          "sha512": "14cb05c941b1248124429f67b2b9b248eb479240549450950ef45c3ab8a14ea27cbc3ae0153aa823578e311e7ff443d09926c283c21147e63569ad1fa57c8cae",
          "sha256": "8c48d7bdd933512e4151c5fb972396dcca7130e79289af4e5fae8071d6eada1c",
          "sha1": "077ec85efc1dcc2f43f248444bf334b3c5df619a",
          "md5": "fd54990e006295da101a13d0f13bbbd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.4.jar",
          "url": "honoka-framework-utils-1.0.4.jar",
          "size": 16868,
          "sha512": "14cb05c941b1248124429f67b2b9b248eb479240549450950ef45c3ab8a14ea27cbc3ae0153aa823578e311e7ff443d09926c283c21147e63569ad1fa57c8cae",
          "sha256": "8c48d7bdd933512e4151c5fb972396dcca7130e79289af4e5fae8071d6eada1c",
          "sha1": "077ec85efc1dcc2f43f248444bf334b3c5df619a",
          "md5": "fd54990e006295da101a13d0f13bbbd6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.4-sources.jar",
          "url": "honoka-framework-utils-1.0.4-sources.jar",
          "size": 10546,
          "sha512": "7fa168ed8b97e4b35b4db2beb12867101b3676bcc86a68bea96f674a701ab331f7be08f0ce8f45bea0ab68c4a0ccc66b2f33752c2282c674da0b57117ba3c0e7",
          "sha256": "b4dc24c0adb60815cb5f3c25a878ce0bfb0a189540b66b68e15892418be721d1",
          "sha1": "d92286d8e1264ca7213f44c3654a98799ac38803",
          "md5": "5762af82ef4c0e4ab1ac34ac29b34ec0"
        }
      ]
    }
  ]
}
