{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-framework-utils",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.1.jar",
          "url": "honoka-framework-utils-1.0.1.jar",
          "size": 13414,
          "sha512": "3c71d62957f63a6b18f3fd42c951613f334ba23910c70ac312806200401357997c9ca95b5f92935e835e96d70dce032bfc8c32a7058b962f998e59c0b4b5875c",
          "sha256": "c0d4db3617fe15cc59d7454741571882774483232022a86c262866e46d262cf8",
          "sha1": "3670eef4cbcf1b899f2928fca7e6abf69a253262",
          "md5": "68272c4216fe14d4ae7e204fae73aaed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.1.jar",
          "url": "honoka-framework-utils-1.0.1.jar",
          "size": 13414,
          "sha512": "3c71d62957f63a6b18f3fd42c951613f334ba23910c70ac312806200401357997c9ca95b5f92935e835e96d70dce032bfc8c32a7058b962f998e59c0b4b5875c",
          "sha256": "c0d4db3617fe15cc59d7454741571882774483232022a86c262866e46d262cf8",
          "sha1": "3670eef4cbcf1b899f2928fca7e6abf69a253262",
          "md5": "68272c4216fe14d4ae7e204fae73aaed"
        }
      ]
    }
  ]
}
