{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-framework-utils",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.2.jar",
          "url": "honoka-framework-utils-1.0.2.jar",
          "size": 15885,
          "sha512": "7ef2a83f8f3565e6c0ff741a3f5cd2ff3bee16f6e995ab4ac355a64f55c066808456a6c20243da9def1f7dabc7085d40e3f9b2a8fb5ea07053135c0e825ccf38",
          "sha256": "c6f7fadc95e169e94cf507c90f039797eef82bfb1665aabd8e8913cf44ae066a",
          "sha1": "4782bdd15a5273a105720ce242d587489e4ae270",
          "md5": "3f824f8bbd1f33ad495cae8f2a557376"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.2.jar",
          "url": "honoka-framework-utils-1.0.2.jar",
          "size": 15885,
          "sha512": "7ef2a83f8f3565e6c0ff741a3f5cd2ff3bee16f6e995ab4ac355a64f55c066808456a6c20243da9def1f7dabc7085d40e3f9b2a8fb5ea07053135c0e825ccf38",
          "sha256": "c6f7fadc95e169e94cf507c90f039797eef82bfb1665aabd8e8913cf44ae066a",
          "sha1": "4782bdd15a5273a105720ce242d587489e4ae270",
          "md5": "3f824f8bbd1f33ad495cae8f2a557376"
        }
      ]
    }
  ]
}
