{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-framework-utils",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.2.jar",
          "url": "honoka-framework-utils-1.0.2.jar",
          "size": 15885,
          "sha512": "23242062bf587051dc7883ccd5003e6a5f217d5475f65769f43515935b07a2835729fab30634ac26a49bf507fad169f8e3899f17e4d8273f37170577433e926d",
          "sha256": "8e356f2069044cac14bce79aeb6b6f52f3b4d16afbe79c0b88766212c53aa504",
          "sha1": "871217c6267e9d23a9148194f23232f8813d92ed",
          "md5": "b6940145e505247001e8b501f6434c67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.2.jar",
          "url": "honoka-framework-utils-1.0.2.jar",
          "size": 15885,
          "sha512": "23242062bf587051dc7883ccd5003e6a5f217d5475f65769f43515935b07a2835729fab30634ac26a49bf507fad169f8e3899f17e4d8273f37170577433e926d",
          "sha256": "8e356f2069044cac14bce79aeb6b6f52f3b4d16afbe79c0b88766212c53aa504",
          "sha1": "871217c6267e9d23a9148194f23232f8813d92ed",
          "md5": "b6940145e505247001e8b501f6434c67"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.2-sources.jar",
          "url": "honoka-framework-utils-1.0.2-sources.jar",
          "size": 11340,
          "sha512": "ce356725b3a91643ad71bf4b209293146c74e7daf739b1b9193bcadc8f57720b7f94df1cecc54264c0d721d748ec6f7ee1a41a284158afe8316bf6d1f590f190",
          "sha256": "091f17533240b017945158995f4d8bfcef54e85ac0bd04901cb834440e1c9ced",
          "sha1": "7f61ef2c6d3cfcad59b5e4ac1c3b3cd0a3238802",
          "md5": "842cddc8ed94b0e8eb8ca863e0b0147c"
        }
      ]
    }
  ]
}
