{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-android-plugin",
    "version": "1.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-android-plugin-1.0.0-dev.jar",
          "url": "honoka-android-plugin-1.0.0-dev.jar",
          "size": 28019,
          "sha512": "499090c48f7560d651d15ade1a6e50ff8797599257c3cad563905386690dd169ab206555803c523debb7096a54ae824859dec002afba595e7fea4add26f74518",
          "sha256": "a4a0552c3a044f23302515afaf0bc6683d0fd1982bf79d55ec91fce9ddead04f",
          "sha1": "c015917f660381a9babffcbd50d731f0ac6ee2fb",
          "md5": "680db5ccc23d219a1ba23816ec079391"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle.plugin",
          "module": "honoka-basic-plugin",
          "version": {
            "requires": "1.0.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-android-plugin-1.0.0-dev.jar",
          "url": "honoka-android-plugin-1.0.0-dev.jar",
          "size": 28019,
          "sha512": "499090c48f7560d651d15ade1a6e50ff8797599257c3cad563905386690dd169ab206555803c523debb7096a54ae824859dec002afba595e7fea4add26f74518",
          "sha256": "a4a0552c3a044f23302515afaf0bc6683d0fd1982bf79d55ec91fce9ddead04f",
          "sha1": "c015917f660381a9babffcbd50d731f0ac6ee2fb",
          "md5": "680db5ccc23d219a1ba23816ec079391"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-android-plugin-1.0.0-dev-sources.jar",
          "url": "honoka-android-plugin-1.0.0-dev-sources.jar",
          "size": 3933,
          "sha512": "6180eb34b714facd6cb9c61ce1bfcf6ff1e830d12c7a3431af5f409e647d51538e326e41217d1c69812be28c34736db99868326932661aac54e321dcbd57c5ff",
          "sha256": "a2533ddc64ef7696022800de25c093dc54906ef9a2af04cbf7878e484c50aa67",
          "sha1": "d3f385c4d980e927165ddc09a398ac07aa87dc06",
          "md5": "607a679ace75a0152e13e0a50759b6da"
        }
      ]
    }
  ]
}
