{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-android-plugin",
    "version": "1.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-android-plugin-1.0.0-dev.jar",
          "url": "honoka-android-plugin-1.0.0-dev.jar",
          "size": 28019,
          "sha512": "688a5a458d97245576db15bd3b14c065e13e3fcd800955543bfe98efffc37ffb1c0d4782a12a74b8ecc5ec01087a26e9eed0bd4d108d8e0f01740990b3bbe797",
          "sha256": "daa266dceaf5cdd0bf4a913bb157f13b95543c391683e01482a0a9dcef34257c",
          "sha1": "17da1d7bc378c253a7ed4b33d65ad1b6c9fc45d5",
          "md5": "c5697e0a93aeb326981456f918c190c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle.plugin",
          "module": "honoka-basic-plugin",
          "version": {
            "requires": "1.0.2-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-android-plugin-1.0.0-dev.jar",
          "url": "honoka-android-plugin-1.0.0-dev.jar",
          "size": 28019,
          "sha512": "688a5a458d97245576db15bd3b14c065e13e3fcd800955543bfe98efffc37ffb1c0d4782a12a74b8ecc5ec01087a26e9eed0bd4d108d8e0f01740990b3bbe797",
          "sha256": "daa266dceaf5cdd0bf4a913bb157f13b95543c391683e01482a0a9dcef34257c",
          "sha1": "17da1d7bc378c253a7ed4b33d65ad1b6c9fc45d5",
          "md5": "c5697e0a93aeb326981456f918c190c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-android-plugin-1.0.0-dev-sources.jar",
          "url": "honoka-android-plugin-1.0.0-dev-sources.jar",
          "size": 3933,
          "sha512": "af8393f62322fe32e298768dc54ab95d0630ca4d3f9b5401e80422a16a3ddc9c41e1355292cb2d54df9c644b5fd323a6bff21e5846978d07b3363bcd38781bbb",
          "sha256": "98a1ee0c09c8e783bc114f76e82c30d78935662e7bbdececd6935c1012fecab1",
          "sha1": "b31cfb01a7f5dcbd0b6b7bfc9d3e8ff94d63d188",
          "md5": "85650aedf05670eaa3a891bf6f88a80a"
        }
      ]
    }
  ]
}
