{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.0.12-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.12-dev.jar",
          "url": "honoka-utils-1.0.12-dev.jar",
          "size": 71605,
          "sha512": "4630f16e3228016549c53f082792affd893881c7439df6f708812748b65c80ffe7ac300b747fa4aea465aa2b4484ab7ab8e5a5df079f7df80b4adf980dfb0b82",
          "sha256": "9c9c9adaaacfc8b68c480fff9925e153b5e117edda8662615cf992e2e5184494",
          "sha1": "adcd323337e6e06510d05d3639e71707387c1437",
          "md5": "87b76cb34a3faf7907193e758413313a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.12-dev.jar",
          "url": "honoka-utils-1.0.12-dev.jar",
          "size": 71605,
          "sha512": "4630f16e3228016549c53f082792affd893881c7439df6f708812748b65c80ffe7ac300b747fa4aea465aa2b4484ab7ab8e5a5df079f7df80b4adf980dfb0b82",
          "sha256": "9c9c9adaaacfc8b68c480fff9925e153b5e117edda8662615cf992e2e5184494",
          "sha1": "adcd323337e6e06510d05d3639e71707387c1437",
          "md5": "87b76cb34a3faf7907193e758413313a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.0.12-dev-sources.jar",
          "url": "honoka-utils-1.0.12-dev-sources.jar",
          "size": 38283,
          "sha512": "862184ac5a4c5488ca89f8721104b0fa1c51dc8425b71aaedb1cd36ace3f518c4a5472181e60596515ec321e58ce0fd4c1492afd36d340af558a4f6a7f87750e",
          "sha256": "55434e070998f5dd65eda6460c831ebd41a20cc2ef2ffa5879ac050af729dad7",
          "sha1": "a47c3da5206d89555317bfc72cf4350c52c89a80",
          "md5": "06d1d7a98f3bccbb070f564e71598f2a"
        }
      ]
    }
  ]
}
