{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.0.12-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.12-dev.jar",
          "url": "honoka-utils-1.0.12-dev.jar",
          "size": 71472,
          "sha512": "46aafbcacabc1bf2e84548811d4a5a1af9b68ce6657ff2d4e9533efc63e140a00f983b3c8b76f8273584f328d3a49bcf24f88841d9d152700922cf8609639507",
          "sha256": "0aef19588eeec42cddbeaa186c7e49a4d53bb05d89fc3a513f817661a7d5535b",
          "sha1": "225f492228e2490541d26418057fc9f33dcbd9c6",
          "md5": "5dccb81d59d9316ef6e6e89a2e08c573"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.12-dev.jar",
          "url": "honoka-utils-1.0.12-dev.jar",
          "size": 71472,
          "sha512": "46aafbcacabc1bf2e84548811d4a5a1af9b68ce6657ff2d4e9533efc63e140a00f983b3c8b76f8273584f328d3a49bcf24f88841d9d152700922cf8609639507",
          "sha256": "0aef19588eeec42cddbeaa186c7e49a4d53bb05d89fc3a513f817661a7d5535b",
          "sha1": "225f492228e2490541d26418057fc9f33dcbd9c6",
          "md5": "5dccb81d59d9316ef6e6e89a2e08c573"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.0.12-dev-sources.jar",
          "url": "honoka-utils-1.0.12-dev-sources.jar",
          "size": 38211,
          "sha512": "4c62a99e3ef90bde9111e84d9e0f79b06896d3db91d8a8e247d322996f428668e0258cf25246e065f00a28cf4de55e76c00b2d150c59cf7bd0f72d2bcf038617",
          "sha256": "5fcf5477c154a928f7f35a1c32f9da3eb6db71ea49aca50ee09196c1e8baa825",
          "sha1": "13df880d5f6e232be35b0862542bbf30aefc5018",
          "md5": "de42e66e8e3b043750e941e2849f55ed"
        }
      ]
    }
  ]
}
