{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-json-fastjson",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-json-api",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-fastjson-1.1.3.jar",
          "url": "honoka-json-fastjson-1.1.3.jar",
          "size": 11356,
          "sha512": "0dad1ef742895732a66af10aeec495b2cba4688d8bf0290fb486aa03fb4b45db7c7b0057a05b7752e12cd4ac992ea5db97bba0f70a86a20614cd5b157d3b761a",
          "sha256": "1511bd4fd8b3a32622667de9cc428c64155a7c2b25b88f49cf352a759b153d0c",
          "sha1": "126027ec43fc724805b7b1a3fe1d1dc48a707e5e",
          "md5": "5b8a8c529a7942174fd835b0137c7979"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-json-api",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.75"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-fastjson-1.1.3.jar",
          "url": "honoka-json-fastjson-1.1.3.jar",
          "size": 11356,
          "sha512": "0dad1ef742895732a66af10aeec495b2cba4688d8bf0290fb486aa03fb4b45db7c7b0057a05b7752e12cd4ac992ea5db97bba0f70a86a20614cd5b157d3b761a",
          "sha256": "1511bd4fd8b3a32622667de9cc428c64155a7c2b25b88f49cf352a759b153d0c",
          "sha1": "126027ec43fc724805b7b1a3fe1d1dc48a707e5e",
          "md5": "5b8a8c529a7942174fd835b0137c7979"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-json-fastjson-1.1.3-sources.jar",
          "url": "honoka-json-fastjson-1.1.3-sources.jar",
          "size": 6457,
          "sha512": "64982be52d1288340bd1d3011068257d5b3d1a0ae2047537a3ffdaf5612737f2fc6e4102cf98e619e8e20e55eddfaf4cbd0f41c0e89122dc10cb6f48efd61dc1",
          "sha256": "d8374d8b9bd37188ec53b61197564c6e5de587929fcf861fb7ae9f07082de0fe",
          "sha1": "090943e9ae735090ff0b0f54315fd3ba404155e1",
          "md5": "4c322ba9f387f42287ab660cadc550f5"
        }
      ]
    }
  ]
}
