{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-json-fastjson",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-json-api",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-fastjson-1.1.3.jar",
          "url": "honoka-json-fastjson-1.1.3.jar",
          "size": 11272,
          "sha512": "0ef252d39f426670461d34df6a89ebb68d60cfa877cb07bd80fdc3f1a544e5b10aa2b4e885394f722c8a68012c1cad2c7b1cd6d769480a4029f320c6b12498c1",
          "sha256": "f3da586dd0b227e560bd9909fa9310eb093e8d539d093dd2b996f59990af697d",
          "sha1": "099c254fd9fe031b1d93cb6ebef58d6939990c34",
          "md5": "281db94df65aee3280957fb7f4b17e70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-json-api",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.75"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-fastjson-1.1.3.jar",
          "url": "honoka-json-fastjson-1.1.3.jar",
          "size": 11272,
          "sha512": "0ef252d39f426670461d34df6a89ebb68d60cfa877cb07bd80fdc3f1a544e5b10aa2b4e885394f722c8a68012c1cad2c7b1cd6d769480a4029f320c6b12498c1",
          "sha256": "f3da586dd0b227e560bd9909fa9310eb093e8d539d093dd2b996f59990af697d",
          "sha1": "099c254fd9fe031b1d93cb6ebef58d6939990c34",
          "md5": "281db94df65aee3280957fb7f4b17e70"
        }
      ]
    }
  ]
}
