{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.1.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.2.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.1.0-dev.jar",
          "url": "honoka-spring-boot-starter-1.1.0-dev.jar",
          "size": 97622,
          "sha512": "fd72a6c1c2e924b747ab7dae1904b5e0caec09ab4ad30e3b88ec2f8c77c1dfc8d868f6e521493ae9f59dfdeebc52bc3dd5caf44dde35d1e2f4a3462a85b43775",
          "sha256": "cf84faa60cdb54b58d2ebae28cdf19174dc34d9c0bde983acda8e4f8ea1a3029",
          "sha1": "fd058b6d7d230ccbe1fb51eb61c4cf8b372a758d",
          "md5": "11f2cf8c31d08aa37c9b3d8d22341e43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.9"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "*"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.2.0-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.1.0-dev.jar",
          "url": "honoka-spring-boot-starter-1.1.0-dev.jar",
          "size": 97622,
          "sha512": "fd72a6c1c2e924b747ab7dae1904b5e0caec09ab4ad30e3b88ec2f8c77c1dfc8d868f6e521493ae9f59dfdeebc52bc3dd5caf44dde35d1e2f4a3462a85b43775",
          "sha256": "cf84faa60cdb54b58d2ebae28cdf19174dc34d9c0bde983acda8e4f8ea1a3029",
          "sha1": "fd058b6d7d230ccbe1fb51eb61c4cf8b372a758d",
          "md5": "11f2cf8c31d08aa37c9b3d8d22341e43"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.1.0-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.1.0-dev-sources.jar",
          "size": 24155,
          "sha512": "76ad408a8bd64b7df627ed428659ff3fa0c64918e8c4320102c617c98cd1305780939a81f3b621ed2134d18c08ddd9c5973e9fe48708209b8247bb67dfedc353",
          "sha256": "8847cee3869b004c07763ffad2a60319f83fbafe8aa0c456ef19a8b8d127f70f",
          "sha1": "ec921577f2da08f2a735ff19d2f304e97e7bc823",
          "md5": "fd4907fbf9d8e6c11b2caef71624588d"
        },
        {
          "name": "honoka-spring-boot-starter-1.1.0-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.1.0-dev-sources.jar",
          "size": 24155,
          "sha512": "76ad408a8bd64b7df627ed428659ff3fa0c64918e8c4320102c617c98cd1305780939a81f3b621ed2134d18c08ddd9c5973e9fe48708209b8247bb67dfedc353",
          "sha256": "8847cee3869b004c07763ffad2a60319f83fbafe8aa0c456ef19a8b8d127f70f",
          "sha1": "ec921577f2da08f2a735ff19d2f304e97e7bc823",
          "md5": "fd4907fbf9d8e6c11b2caef71624588d"
        }
      ]
    }
  ]
}
