{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.1.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.2.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.1.0-dev.jar",
          "url": "honoka-spring-boot-starter-1.1.0-dev.jar",
          "size": 129344,
          "sha512": "3a7898cc17aa7ac25b5b4801e0f91c5db9d739e97e938b2c67e8b0c13055be39676aa30977f2e7a192085b15ef6b48d925837354e6a206555bdbcaee2218fdbe",
          "sha256": "a9b2583912719c52f86c2c40a64a5a797ffa1706260dde5d27d41c9af209509f",
          "sha1": "d3282d72b31f054a6fea6219c28286e942059d63",
          "md5": "9606149d18eee98512da5880706a9c7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.9"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "*"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.2.0-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.1.0-dev.jar",
          "url": "honoka-spring-boot-starter-1.1.0-dev.jar",
          "size": 129344,
          "sha512": "3a7898cc17aa7ac25b5b4801e0f91c5db9d739e97e938b2c67e8b0c13055be39676aa30977f2e7a192085b15ef6b48d925837354e6a206555bdbcaee2218fdbe",
          "sha256": "a9b2583912719c52f86c2c40a64a5a797ffa1706260dde5d27d41c9af209509f",
          "sha1": "d3282d72b31f054a6fea6219c28286e942059d63",
          "md5": "9606149d18eee98512da5880706a9c7d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.1.0-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.1.0-dev-sources.jar",
          "size": 28798,
          "sha512": "cababd630925980119bd0be9e5abc180a4b3fdf1f0b61b280b1443b683b66a354361aeb7895e2e2d1f641f9294e3be2d7e610ea1b6745a1cb637be353e59abfa",
          "sha256": "5868d7bc6816cdc0af713f417b623d3227b87eed904f537e3837b4b105480d28",
          "sha1": "9964efa088a2998ebf6b1053832c5656d2b0295f",
          "md5": "09dfcaf181f78560aeb60ced6e9c145a"
        },
        {
          "name": "honoka-spring-boot-starter-1.1.0-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.1.0-dev-sources.jar",
          "size": 28798,
          "sha512": "cababd630925980119bd0be9e5abc180a4b3fdf1f0b61b280b1443b683b66a354361aeb7895e2e2d1f641f9294e3be2d7e610ea1b6745a1cb637be353e59abfa",
          "sha256": "5868d7bc6816cdc0af713f417b623d3227b87eed904f537e3837b4b105480d28",
          "sha1": "9964efa088a2998ebf6b1053832c5656d2b0295f",
          "md5": "09dfcaf181f78560aeb60ced6e9c145a"
        }
      ]
    }
  ]
}
