{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.1.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.2.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.1.0-dev.jar",
          "url": "honoka-spring-boot-starter-1.1.0-dev.jar",
          "size": 141717,
          "sha512": "32be7fe1ea79ca85e4965b8644820e5b41aeeb5e2938bd0c75e635d4ace542adfe1a761a2a4894db1f5e34b95476818effae12656c2218d30b70c3befe6a8f47",
          "sha256": "e5a4da66337d5e516bfc999df6c93ec577e37e8396e8b80b1fa29553ea3eddb2",
          "sha1": "d97ec290638ccdf0330f57655190c8613788ae7a",
          "md5": "cda7b8ae4454dba22e66a42a3695b420"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.9"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "*"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.2.0-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.1.0-dev.jar",
          "url": "honoka-spring-boot-starter-1.1.0-dev.jar",
          "size": 141717,
          "sha512": "32be7fe1ea79ca85e4965b8644820e5b41aeeb5e2938bd0c75e635d4ace542adfe1a761a2a4894db1f5e34b95476818effae12656c2218d30b70c3befe6a8f47",
          "sha256": "e5a4da66337d5e516bfc999df6c93ec577e37e8396e8b80b1fa29553ea3eddb2",
          "sha1": "d97ec290638ccdf0330f57655190c8613788ae7a",
          "md5": "cda7b8ae4454dba22e66a42a3695b420"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.1.0-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.1.0-dev-sources.jar",
          "size": 30101,
          "sha512": "1065dc76b392636a0ca003e61f8dd28c05ec1464f9e030ad8b88b5fb46d45aa56ef77c2080f31026b05220fcf08bdcefe85a27321c5cb363d7d2b28fe4c3aa6f",
          "sha256": "fe24ead64d775f3f8add80cbe209f66bc35f96652b6be64ae2f87b0a143b7a0c",
          "sha1": "5a94ecb2e52a5ab19da60baa9fd1da8660043047",
          "md5": "b16ca8318d7a11ee8d1178d01b26a177"
        },
        {
          "name": "honoka-spring-boot-starter-1.1.0-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.1.0-dev-sources.jar",
          "size": 30101,
          "sha512": "1065dc76b392636a0ca003e61f8dd28c05ec1464f9e030ad8b88b5fb46d45aa56ef77c2080f31026b05220fcf08bdcefe85a27321c5cb363d7d2b28fe4c3aa6f",
          "sha256": "fe24ead64d775f3f8add80cbe209f66bc35f96652b6be64ae2f87b0a143b7a0c",
          "sha1": "5a94ecb2e52a5ab19da60baa9fd1da8660043047",
          "md5": "b16ca8318d7a11ee8d1178d01b26a177"
        }
      ]
    }
  ]
}
