{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-framework-utils",
    "version": "1.0.5-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.5-dev.jar",
          "url": "honoka-framework-utils-1.0.5-dev.jar",
          "size": 17991,
          "sha512": "47f2433f59449531cf5e38c0808edab174b3748ba9459fa3a2a8a6a0f6cb8ec51af1ccef16e7a862820f7b15d6a8127512700eff647d409794b0a88b8e283317",
          "sha256": "75fd2c20edeccf26c2b0ba639d9926fcb9e96bc66ec103c0ad1e4f421ee4ce95",
          "sha1": "3b8be46d44a530869b3a8fb350a913d73d52e77d",
          "md5": "48617ffab9810b2205f5612e684f9cc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          },
          "excludes": [
            {
              "group": "jaxen",
              "module": "jaxen"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          },
          "excludes": [
            {
              "group": "jaxen",
              "module": "jaxen"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3"
          },
          "excludes": [
            {
              "group": "jaxen",
              "module": "jaxen"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            }
          ]
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.1-dev"
          },
          "excludes": [
            {
              "group": "jaxen",
              "module": "jaxen"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            }
          ]
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.5-dev.jar",
          "url": "honoka-framework-utils-1.0.5-dev.jar",
          "size": 17991,
          "sha512": "47f2433f59449531cf5e38c0808edab174b3748ba9459fa3a2a8a6a0f6cb8ec51af1ccef16e7a862820f7b15d6a8127512700eff647d409794b0a88b8e283317",
          "sha256": "75fd2c20edeccf26c2b0ba639d9926fcb9e96bc66ec103c0ad1e4f421ee4ce95",
          "sha1": "3b8be46d44a530869b3a8fb350a913d73d52e77d",
          "md5": "48617ffab9810b2205f5612e684f9cc2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.5-dev-sources.jar",
          "url": "honoka-framework-utils-1.0.5-dev-sources.jar",
          "size": 10634,
          "sha512": "f16f76ed184f17d852ceab53663c29a3fb0408ab3a04f881366e973a6470549b78a026dbf438752164d5c7e675ee8d9bec34be38b6915d8ed0b072656d60d2dc",
          "sha256": "ce485c4e14913b78b1689c492362f6944da90e62be07baf3034a0520776c6bdd",
          "sha1": "272bff54345cb81636d13e2d159cd3ba44643bdb",
          "md5": "58321f599d0668aa89335aa7b3c5f1d7"
        }
      ]
    }
  ]
}
