{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-framework-utils",
    "version": "1.0.5-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.5-dev.jar",
          "url": "honoka-framework-utils-1.0.5-dev.jar",
          "size": 18032,
          "sha512": "45d77aab3d42fa1e6529b02f39ef55e5c0a9a221a0297473dfbb39d4ebe08bac6a17a806524aa32c07ffa51f86f86e37321671e80404bd81147dd68ac90821d2",
          "sha256": "8ac388405214c74f3c37055f8f05a730e22614a83b5e136482edb81199c25731",
          "sha1": "c01a187afdcf22d352d1ffc88292e973ec6ee069",
          "md5": "5169ba27f9e400ebc4769d3a8f22225c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          },
          "excludes": [
            {
              "group": "jaxen",
              "module": "jaxen"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          },
          "excludes": [
            {
              "group": "jaxen",
              "module": "jaxen"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3"
          },
          "excludes": [
            {
              "group": "jaxen",
              "module": "jaxen"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            }
          ]
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.1-dev"
          },
          "excludes": [
            {
              "group": "jaxen",
              "module": "jaxen"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            }
          ]
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.5-dev.jar",
          "url": "honoka-framework-utils-1.0.5-dev.jar",
          "size": 18032,
          "sha512": "45d77aab3d42fa1e6529b02f39ef55e5c0a9a221a0297473dfbb39d4ebe08bac6a17a806524aa32c07ffa51f86f86e37321671e80404bd81147dd68ac90821d2",
          "sha256": "8ac388405214c74f3c37055f8f05a730e22614a83b5e136482edb81199c25731",
          "sha1": "c01a187afdcf22d352d1ffc88292e973ec6ee069",
          "md5": "5169ba27f9e400ebc4769d3a8f22225c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.5-dev-sources.jar",
          "url": "honoka-framework-utils-1.0.5-dev-sources.jar",
          "size": 10654,
          "sha512": "134e7d79264c21a0675efcbb0ea5fc9a8e35921ce3784a8867cc5addd7d13f33d38c127a4519ce27ff349a5b924fdce6b892638a76efb208bb2823faf367580e",
          "sha256": "01514b89c16d99820b1408d5c580b385a8e2cdad949f7c0d880fd0bf2eee229d",
          "sha1": "d592539e556ed0f63fde61a4a8683450d6dcb372",
          "md5": "b3add41272e6810fc659873a16ebf62d"
        }
      ]
    }
  ]
}
