{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-framework-utils",
    "version": "1.0.5-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.5-dev.jar",
          "url": "honoka-framework-utils-1.0.5-dev.jar",
          "size": 18032,
          "sha512": "c162ab7f24083e845b18bfbb7ccade96a3e873324c9e9ce5612aa63b9b15160ff66dcea7f226b8f7ccaa6ba3614cfbd3856762c274d2e7486fdacc3db128091d",
          "sha256": "6c45c1b81652044a310b2bb2d94c1cc33972e8dd9c0556ec91671d8aa6225985",
          "sha1": "e053a8c4a64eb7baf58be16cb2c8ebc0ae559483",
          "md5": "1ffee74158ef807637abc50791e7ea7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          },
          "excludes": [
            {
              "group": "jaxen",
              "module": "jaxen"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          },
          "excludes": [
            {
              "group": "jaxen",
              "module": "jaxen"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3"
          },
          "excludes": [
            {
              "group": "jaxen",
              "module": "jaxen"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            }
          ]
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.1-dev"
          },
          "excludes": [
            {
              "group": "jaxen",
              "module": "jaxen"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            }
          ]
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.5-dev.jar",
          "url": "honoka-framework-utils-1.0.5-dev.jar",
          "size": 18032,
          "sha512": "c162ab7f24083e845b18bfbb7ccade96a3e873324c9e9ce5612aa63b9b15160ff66dcea7f226b8f7ccaa6ba3614cfbd3856762c274d2e7486fdacc3db128091d",
          "sha256": "6c45c1b81652044a310b2bb2d94c1cc33972e8dd9c0556ec91671d8aa6225985",
          "sha1": "e053a8c4a64eb7baf58be16cb2c8ebc0ae559483",
          "md5": "1ffee74158ef807637abc50791e7ea7d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.5-dev-sources.jar",
          "url": "honoka-framework-utils-1.0.5-dev-sources.jar",
          "size": 10654,
          "sha512": "e54d6eb957134a7d09ba3a3626fdd21af4006cf35f927400bb7567da871fe13f40cf0933e5d030df10d14a1c730438a5ba58de117ce0142d70bf0bb16761198d",
          "sha256": "80a0c6f8b0dae2d04fe34ee981d37e575938207a36a0c9bd4fbad526878c0ba7",
          "sha1": "16577cc11117092f638ab1fc648156d7c640cc41",
          "md5": "7e50b33ebe84b59c5662c6fee6c4e7c9"
        }
      ]
    }
  ]
}
