{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender.lavsource",
    "module": "lavsource-bilibili-business",
    "version": "1.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "lavsource-bilibili-business-1.0.0-dev.jar",
          "url": "lavsource-bilibili-business-1.0.0-dev.jar",
          "size": 30245,
          "sha512": "914cf464e672104ae1eda3b2cd793ea0fcdf4bacc6b5e4580e2ecb4632d03eadec58ee848411c7612042cb182409e640ecedb6377fae3eeb8a5786816c694fda",
          "sha256": "9129702b52ef7ec5b7eeb9c9d9a468db95453f766ae31d7f9ec706fc45868ad2",
          "sha1": "245a5448a9d908c75358a767a86678ecccf7ea2d",
          "md5": "f05c1635fac95ac2beab6559538a21d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.0-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "lavsource-bilibili-business-1.0.0-dev.jar",
          "url": "lavsource-bilibili-business-1.0.0-dev.jar",
          "size": 30245,
          "sha512": "914cf464e672104ae1eda3b2cd793ea0fcdf4bacc6b5e4580e2ecb4632d03eadec58ee848411c7612042cb182409e640ecedb6377fae3eeb8a5786816c694fda",
          "sha256": "9129702b52ef7ec5b7eeb9c9d9a468db95453f766ae31d7f9ec706fc45868ad2",
          "sha1": "245a5448a9d908c75358a767a86678ecccf7ea2d",
          "md5": "f05c1635fac95ac2beab6559538a21d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavsource-bilibili-business-1.0.0-dev-sources.jar",
          "url": "lavsource-bilibili-business-1.0.0-dev-sources.jar",
          "size": 9489,
          "sha512": "a0cb877f79ef8c2c3b1321c90b4aca70b209fe7bd64c718b1ce1191f6206e5f04aa2b27f5d30cb2f9da99ebb0e7b2b6308e08f712a096168abac7256a5834044",
          "sha256": "c794569feb75900e1b92aa3ae73ab26df2deb905e7a24be8181187a034be0eb5",
          "sha1": "b6c2d76f5cd1dd80d32d63276a7c11ec2766af08",
          "md5": "508fcfcad162ff90db8274ffb5bd7299"
        }
      ]
    }
  ]
}
