{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender.lavsource",
    "module": "lavsource-bilibili-business",
    "version": "1.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "lavsource-bilibili-business-1.0.0-dev.jar",
          "url": "lavsource-bilibili-business-1.0.0-dev.jar",
          "size": 30438,
          "sha512": "83bfe40e8a5ddc6093a7957cb2c9d1a834454107c139f151c3100e567ad50f3073bc275ae5430f91840b1c0e4afaf070bd5bfab59c8936df07a080ca73b2075d",
          "sha256": "0c0f5120fc765dc7803b31a4c3dac2ce8ba0ba3d65ee6fe9be2f8ae95025e991",
          "sha1": "dc77508151370b64d13dc7e4731b9bced300ebe4",
          "md5": "184e7dbc8a6708b203c32d093e7e40db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.0-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lavsource-bilibili-business-1.0.0-dev.jar",
          "url": "lavsource-bilibili-business-1.0.0-dev.jar",
          "size": 30438,
          "sha512": "83bfe40e8a5ddc6093a7957cb2c9d1a834454107c139f151c3100e567ad50f3073bc275ae5430f91840b1c0e4afaf070bd5bfab59c8936df07a080ca73b2075d",
          "sha256": "0c0f5120fc765dc7803b31a4c3dac2ce8ba0ba3d65ee6fe9be2f8ae95025e991",
          "sha1": "dc77508151370b64d13dc7e4731b9bced300ebe4",
          "md5": "184e7dbc8a6708b203c32d093e7e40db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavsource-bilibili-business-1.0.0-dev-sources.jar",
          "url": "lavsource-bilibili-business-1.0.0-dev-sources.jar",
          "size": 9529,
          "sha512": "0b33491c4b604138727e8020d6481ef4c28e50157816f70e65ed02655dfce10777af7e3a2673e38d377f7ad94590d499949933ef51e9c9c0ed78047e90f76770",
          "sha256": "9d9fdc92e7fc241945f7460c132bf306659d12454cf4d380c100d06d0ba1e5c1",
          "sha1": "0d7a1c2001430cf53c84acf033861cd30c8202fa",
          "md5": "1ce90a8e47aa1d87f18e42dd5cef4873"
        }
      ]
    }
  ]
}
