{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender.lavsource",
    "module": "lavsource-bilibili-business",
    "version": "1.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "lavsource-bilibili-business-1.0.0-dev.jar",
          "url": "lavsource-bilibili-business-1.0.0-dev.jar",
          "size": 30086,
          "sha512": "37fe735e614966977c491b5e548839fc343d1ca5e221bced43820f861af94ad4df6975116cecac2c5910cc8305f13fd1b701be7db8c6506985c4547eba8d273c",
          "sha256": "c17a8c76c0aca9461d1e27128e152e54592551f4c8bdbae9ca606458a76f29a8",
          "sha1": "0ab4d71bc1a65bd3151ddf7d4d8685a1799ed8da",
          "md5": "2308ba37893ade82daa5f19e148e4e48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.0-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "lavsource-bilibili-business-1.0.0-dev.jar",
          "url": "lavsource-bilibili-business-1.0.0-dev.jar",
          "size": 30086,
          "sha512": "37fe735e614966977c491b5e548839fc343d1ca5e221bced43820f861af94ad4df6975116cecac2c5910cc8305f13fd1b701be7db8c6506985c4547eba8d273c",
          "sha256": "c17a8c76c0aca9461d1e27128e152e54592551f4c8bdbae9ca606458a76f29a8",
          "sha1": "0ab4d71bc1a65bd3151ddf7d4d8685a1799ed8da",
          "md5": "2308ba37893ade82daa5f19e148e4e48"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavsource-bilibili-business-1.0.0-dev-sources.jar",
          "url": "lavsource-bilibili-business-1.0.0-dev-sources.jar",
          "size": 9489,
          "sha512": "a0cb877f79ef8c2c3b1321c90b4aca70b209fe7bd64c718b1ce1191f6206e5f04aa2b27f5d30cb2f9da99ebb0e7b2b6308e08f712a096168abac7256a5834044",
          "sha256": "c794569feb75900e1b92aa3ae73ab26df2deb905e7a24be8181187a034be0eb5",
          "sha1": "b6c2d76f5cd1dd80d32d63276a7c11ec2766af08",
          "md5": "508fcfcad162ff90db8274ffb5bd7299"
        }
      ]
    }
  ]
}
