{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-basic-plugin",
    "version": "1.0.3-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.3-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.3-dev.jar",
          "url": "honoka-basic-plugin-1.0.3-dev.jar",
          "size": 24288,
          "sha512": "21b79eceb1e21913a8845f203cdb4df5fc257fbcae346242997d9d87dbd69b82ceb216dd38d6fd2c1eb3db3f7630993491baa8fa7d94eb4b8ec4a72a33458d4a",
          "sha256": "c35c85c3eb8a0473668a93d8115cd26e37cb96f019ea2e4cd77c1a7e5045c264",
          "sha1": "b0280ee033c11af45f96ce151bacc18a12b9292e",
          "md5": "04de3aedc65ec6c4eb6e1af7de69ef30"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.3-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.3-dev.jar",
          "url": "honoka-basic-plugin-1.0.3-dev.jar",
          "size": 24288,
          "sha512": "21b79eceb1e21913a8845f203cdb4df5fc257fbcae346242997d9d87dbd69b82ceb216dd38d6fd2c1eb3db3f7630993491baa8fa7d94eb4b8ec4a72a33458d4a",
          "sha256": "c35c85c3eb8a0473668a93d8115cd26e37cb96f019ea2e4cd77c1a7e5045c264",
          "sha1": "b0280ee033c11af45f96ce151bacc18a12b9292e",
          "md5": "04de3aedc65ec6c4eb6e1af7de69ef30"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.3-dev-sources.jar",
          "url": "honoka-basic-plugin-1.0.3-dev-sources.jar",
          "size": 3688,
          "sha512": "caef6a890cca50a97227c40a701eee31ba67e723dd9f7f1758709b8aa6566d93c4eec5d95a477c614a1dca5777b329fbd92bd8befcd510945cfea2935e0675dd",
          "sha256": "52e3c96fc6f3cda702509dbc499897faa1ddd71f09914726b7824187ca56c8a2",
          "sha1": "8559a35f8f6bfafdf26383d2ecd1dc143a900fa5",
          "md5": "fda82baf9117e30a53065bdfc0b6a573"
        }
      ]
    }
  ]
}
