{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-basic-plugin",
    "version": "1.0.3-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.3-dev.jar",
          "url": "honoka-basic-plugin-1.0.3-dev.jar",
          "size": 24379,
          "sha512": "b43555be46a083c8346072125ee8d131ffd21202a734a6f331937af56a3f3afffcfeaed011c06f185ed26cbd2d0925f51d5b756e3bb63cc397f4db79057d928a",
          "sha256": "c58110d2fa28680714ab7cebd4aa2d57314de4a16aab98b17f651265247a19bb",
          "sha1": "981cb416feff84e1a5ca832be206945da14d1a4c",
          "md5": "10f947ead8821ecc4ff913de59bac21d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.3-dev.jar",
          "url": "honoka-basic-plugin-1.0.3-dev.jar",
          "size": 24379,
          "sha512": "b43555be46a083c8346072125ee8d131ffd21202a734a6f331937af56a3f3afffcfeaed011c06f185ed26cbd2d0925f51d5b756e3bb63cc397f4db79057d928a",
          "sha256": "c58110d2fa28680714ab7cebd4aa2d57314de4a16aab98b17f651265247a19bb",
          "sha1": "981cb416feff84e1a5ca832be206945da14d1a4c",
          "md5": "10f947ead8821ecc4ff913de59bac21d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.3-dev-sources.jar",
          "url": "honoka-basic-plugin-1.0.3-dev-sources.jar",
          "size": 3707,
          "sha512": "3b4ce95152a6b00716a759169b4d5d44f5d32051d8870ab7a56234070b0769519b828feb32793a05d4aa5d31a21c3a9dd82933ab82e36eedc4bf32cd619aec8e",
          "sha256": "b2d3ca0e61e85f0384e0ffb1e0ca2cf3e35aeeb6fdab8b89f21c83401949d589",
          "sha1": "b13af8b778ba3f6bacb54ef9b6d487e057362c83",
          "md5": "529ca9b87e8a8aebee1aae64675f51a8"
        }
      ]
    }
  ]
}
