{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender",
    "module": "lavsource-spring-boot-starter",
    "version": "1.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.0.5-dev"
          }
        },
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "lavsource-spring-boot-starter-1.0.0-dev.jar",
          "url": "lavsource-spring-boot-starter-1.0.0-dev.jar",
          "size": 15928,
          "sha512": "4dc9d3fde90a822d2324bba777cd5ab196ca499b3da22b4333c1942a0db18b145c4f08c535d3561bd00527d1fc90afb1f3e2e075ccd8b4970de420fe3b030537",
          "sha256": "37f9128243f1d3000e6ac0fc5ee2637a49bde551e2864aa738426928adbb4aef",
          "sha1": "4f36d867b97925385d03d4138372454577db4d02",
          "md5": "a42da2a16c545d9e3dfbdc76502c8229"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.0.5-dev"
          }
        },
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.0-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lavsource-spring-boot-starter-1.0.0-dev.jar",
          "url": "lavsource-spring-boot-starter-1.0.0-dev.jar",
          "size": 15928,
          "sha512": "4dc9d3fde90a822d2324bba777cd5ab196ca499b3da22b4333c1942a0db18b145c4f08c535d3561bd00527d1fc90afb1f3e2e075ccd8b4970de420fe3b030537",
          "sha256": "37f9128243f1d3000e6ac0fc5ee2637a49bde551e2864aa738426928adbb4aef",
          "sha1": "4f36d867b97925385d03d4138372454577db4d02",
          "md5": "a42da2a16c545d9e3dfbdc76502c8229"
        }
      ]
    }
  ]
}
