{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender",
    "module": "lavsource-spring-boot-starter",
    "version": "1.0.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.0.5-dev"
          }
        },
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "lavsource-spring-boot-starter-1.0.0-dev.jar",
          "url": "lavsource-spring-boot-starter-1.0.0-dev.jar",
          "size": 17473,
          "sha512": "046f594457701ccd44f1c211c9162ba068a57875607272d339d10f3f241918661ef67299b8df2c399f2b8c6bc2e108747a682603566c8ccf446ccc4f7f0c95db",
          "sha256": "b8aae1da3d688fa2552ca847fb15c1c90024a289490f0a3199d9d287ea6b3198",
          "sha1": "8c3c1233b3262b46fe280644da466ce82a968416",
          "md5": "dff151866ffdffe42f685d3ad49e41c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-spring-boot-starter",
          "version": {
            "requires": "1.0.5-dev"
          }
        },
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.0-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lavsource-spring-boot-starter-1.0.0-dev.jar",
          "url": "lavsource-spring-boot-starter-1.0.0-dev.jar",
          "size": 17473,
          "sha512": "046f594457701ccd44f1c211c9162ba068a57875607272d339d10f3f241918661ef67299b8df2c399f2b8c6bc2e108747a682603566c8ccf446ccc4f7f0c95db",
          "sha256": "b8aae1da3d688fa2552ca847fb15c1c90024a289490f0a3199d9d287ea6b3198",
          "sha1": "8c3c1233b3262b46fe280644da466ce82a968416",
          "md5": "dff151866ffdffe42f685d3ad49e41c3"
        }
      ]
    }
  ]
}
