{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.1.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.2-dev.jar",
          "url": "honoka-utils-1.1.2-dev.jar",
          "size": 75968,
          "sha512": "b0199a55d64ae0c548cd83553cd071361a551d0d973acfe2e7bc989d4a3ec3a3e8c02f448462a9f6b676359101329b129971bbffb3e19959ead51ab7b62074f5",
          "sha256": "cdaa2b5162a87beb42deed3d2340ee26406c60d89874d1c9afe1fd11ee7a59d3",
          "sha1": "39a2a9fe92875018f3eb9607d8a9cadb9e4dc3b9",
          "md5": "f9dbdc54f3d55b8a57eb040b427b32c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.2-dev.jar",
          "url": "honoka-utils-1.1.2-dev.jar",
          "size": 75968,
          "sha512": "b0199a55d64ae0c548cd83553cd071361a551d0d973acfe2e7bc989d4a3ec3a3e8c02f448462a9f6b676359101329b129971bbffb3e19959ead51ab7b62074f5",
          "sha256": "cdaa2b5162a87beb42deed3d2340ee26406c60d89874d1c9afe1fd11ee7a59d3",
          "sha1": "39a2a9fe92875018f3eb9607d8a9cadb9e4dc3b9",
          "md5": "f9dbdc54f3d55b8a57eb040b427b32c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.1.2-dev-sources.jar",
          "url": "honoka-utils-1.1.2-dev-sources.jar",
          "size": 40246,
          "sha512": "c8951f6cff214783707e0bdde93e9b8714ccc1d8b8b3431c7d440d8bd7cc056319163bc6060857bfbf7d09c624cfbd0fe96da44b7e4b908cedcb041a672a8786",
          "sha256": "a3c61e39d36c77396750bc62f2bf0110c37cbd57b7c28c9c7fd41bf44628b491",
          "sha1": "b3f5a8a49a3731ac00e2a3f8e8c4268ad208cbf0",
          "md5": "d91cc615a6edbc66deca5e73b80c1584"
        }
      ]
    }
  ]
}
