{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.1.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.2-dev.jar",
          "url": "honoka-utils-1.1.2-dev.jar",
          "size": 78876,
          "sha512": "86bbcc64de1e9c66adc5675c9d03b31302d32834f029cc47034b7430ffb0374c690443e3926e9d54bb403d68f3d7cb87e66b940fd70d70721d201a454c2fe4b1",
          "sha256": "29d8a16e5d0a284f852d2ef27f8287f62dadbf4d167d7ce37ca515f8de52822d",
          "sha1": "25c46cc1154b020c264350d44fe1497c2bb3ca58",
          "md5": "1ab8cdb519681b4347c9f042c2074c48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.2-dev.jar",
          "url": "honoka-utils-1.1.2-dev.jar",
          "size": 78876,
          "sha512": "86bbcc64de1e9c66adc5675c9d03b31302d32834f029cc47034b7430ffb0374c690443e3926e9d54bb403d68f3d7cb87e66b940fd70d70721d201a454c2fe4b1",
          "sha256": "29d8a16e5d0a284f852d2ef27f8287f62dadbf4d167d7ce37ca515f8de52822d",
          "sha1": "25c46cc1154b020c264350d44fe1497c2bb3ca58",
          "md5": "1ab8cdb519681b4347c9f042c2074c48"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.1.2-dev-sources.jar",
          "url": "honoka-utils-1.1.2-dev-sources.jar",
          "size": 42439,
          "sha512": "d0ca3d7526233a33db4e48d45277673764d72041b9fc6d33bf49951f9aaa28b0fbc5d078176277930bdaa438120773a9c4a351f06ce8579d88067ce92919733f",
          "sha256": "ce3ce96f04a3dd53adbf8f2726b6f3cbbd63e196e1a6f47678529cc6de165e4c",
          "sha1": "b7b39208a749184af8d579273187ba67c8ef02d1",
          "md5": "e66fb0dfc977b3e7cea2d81bd0633cce"
        }
      ]
    }
  ]
}
