{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.1.2-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.2-dev.jar",
          "url": "honoka-utils-1.1.2-dev.jar",
          "size": 79590,
          "sha512": "1d47da79b8ad27c116d3070b5b6dd7fd38be1cb761a6946ac3f00f7980bcddaaaf8f9eacbe931a1a35c75dd5ab457ed17fb9bd499a85a75ec47b180190a7ca93",
          "sha256": "0abf41821749e3a46fcb2f4f43833a351bb0336573ca15ba627c6bfbbdeb4ea0",
          "sha1": "efbad4ad949b88f72ba323ef153b461e05bb4e20",
          "md5": "980361d714d2c90e25a0dbdf2edaa886"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.dom4j",
          "module": "dom4j",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.1"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.1.2-dev.jar",
          "url": "honoka-utils-1.1.2-dev.jar",
          "size": 79590,
          "sha512": "1d47da79b8ad27c116d3070b5b6dd7fd38be1cb761a6946ac3f00f7980bcddaaaf8f9eacbe931a1a35c75dd5ab457ed17fb9bd499a85a75ec47b180190a7ca93",
          "sha256": "0abf41821749e3a46fcb2f4f43833a351bb0336573ca15ba627c6bfbbdeb4ea0",
          "sha1": "efbad4ad949b88f72ba323ef153b461e05bb4e20",
          "md5": "980361d714d2c90e25a0dbdf2edaa886"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-utils-1.1.2-dev-sources.jar",
          "url": "honoka-utils-1.1.2-dev-sources.jar",
          "size": 42438,
          "sha512": "52991c15db3f56853ad590473513b983243f976f51d616dd7cfcd217cb742d4f8cff8eeffea7c336738ef235957cc3d2e135e98ac1e8d0e4dc6a1f509dc9b129",
          "sha256": "161e52f733d02013781a2d5a22cac1c354f95cd116c3754d0256dc8de7e04a5f",
          "sha1": "8adb4f519eb5d1750c035816553fd2f3d8f92c53",
          "md5": "390829838da0d569601b59d2c2c4b2d8"
        }
      ]
    }
  ]
}
