{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-basic-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.0.jar",
          "url": "honoka-basic-plugin-1.0.0.jar",
          "size": 26290,
          "sha512": "d80c121791bd4386b108139c8d5c5568c047b675efd3b6242fcc1fb7f2284c8012d1bfafdc3eebad83eeb9e0f8dacb5a6368043829869f9c58779e033e66071d",
          "sha256": "902544eb4be2aac00bce96a653691624562e8d17ee19ed996267dc3394cb2ca1",
          "sha1": "4f26cfac79783f47f8aa5ca0fabde91b8be71789",
          "md5": "182f359dcba95d745c2c2c4d1a9d86c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle",
          "module": "honoka-gradle-utils",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.0.jar",
          "url": "honoka-basic-plugin-1.0.0.jar",
          "size": 26290,
          "sha512": "d80c121791bd4386b108139c8d5c5568c047b675efd3b6242fcc1fb7f2284c8012d1bfafdc3eebad83eeb9e0f8dacb5a6368043829869f9c58779e033e66071d",
          "sha256": "902544eb4be2aac00bce96a653691624562e8d17ee19ed996267dc3394cb2ca1",
          "sha1": "4f26cfac79783f47f8aa5ca0fabde91b8be71789",
          "md5": "182f359dcba95d745c2c2c4d1a9d86c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-basic-plugin-1.0.0-sources.jar",
          "url": "honoka-basic-plugin-1.0.0-sources.jar",
          "size": 4005,
          "sha512": "d57d29587e85961d46bf6037135088d2514b0b0aa384ba82e63267eb5fb1ac95d37b1acff1fabf0c6f4ae74f17bcc9f011d194023e95a98c6184513091c6dcbf",
          "sha256": "aed4f7f0ed48ea6379df37e1f963e3acc8547a1271bfb06fe0cb185902b6a45a",
          "sha1": "74bab34a13a59a09a1ea24b69b2b81959b576f5b",
          "md5": "ed34eaeea882a4ebd2222c970abdc07e"
        }
      ]
    }
  ]
}
