{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.3.3.jar",
          "url": "qqrobot-spring-boot-starter-1.3.3.jar",
          "size": 1147194,
          "sha512": "17ba038e4b950998d78906a7e0b05cf51739502ff658e1a7cae8d8ec842a2e161ef5d13c0d65cf6ff713ba0bfc04e3e9d71c925e499855e4c461c5a60819a42f",
          "sha256": "13863f00280b9a21e0c6024848637b18c27b74a9312d2a48dbaca7228db1b33b",
          "sha1": "9b0176104a7404e3f5bee7ad6115a85b19922492",
          "md5": "86e00e61c81aaa4e20fc85ba1bd2773e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-framework-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "net.mamoe",
          "module": "mirai-core-jvm",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.3.3.jar",
          "url": "qqrobot-spring-boot-starter-1.3.3.jar",
          "size": 1147194,
          "sha512": "17ba038e4b950998d78906a7e0b05cf51739502ff658e1a7cae8d8ec842a2e161ef5d13c0d65cf6ff713ba0bfc04e3e9d71c925e499855e4c461c5a60819a42f",
          "sha256": "13863f00280b9a21e0c6024848637b18c27b74a9312d2a48dbaca7228db1b33b",
          "sha1": "9b0176104a7404e3f5bee7ad6115a85b19922492",
          "md5": "86e00e61c81aaa4e20fc85ba1bd2773e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.3.3-sources.jar",
          "url": "qqrobot-spring-boot-starter-1.3.3-sources.jar",
          "size": 1101252,
          "sha512": "0d024912c58557c68bba24fc244aca0c857cbe92403437761d6aa2da942c52270a7322cc46f88ac7eb32b4380fb3d0a688af43e081b2df1b40774b63e1187549",
          "sha256": "f6b7f257c9129f1b1218fb3927dd9b487de45a04401105e3348c8375fd45c189",
          "sha1": "93631b68f409ea12615a4f9e3f5a8f2a9b25a08a",
          "md5": "4a04b3c6b59e4a67a46b758e31fcacdb"
        }
      ]
    }
  ]
}
