{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "2.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.1-dev.jar",
          "url": "qqrobot-framework-api-2.0.1-dev.jar",
          "size": 11522,
          "sha512": "afdb1f1681ccb388dd0b9dbeb1170f1a132793b0fbfc9546e758ea6a0dac4109061842bcb4f37ddb7d07d2472e876a9fc82a611469a6686da9dc765d38e9e4de",
          "sha256": "252b78520fe8f43365576567b4746003c3fd1332791e81662df53e3a426ffdf6",
          "sha1": "e0f7ae34b2b64bf30bb8763d858ad15985b714c0",
          "md5": "d5dd7fb2fe7c4844258275e21e3af7b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.1-dev.jar",
          "url": "qqrobot-framework-api-2.0.1-dev.jar",
          "size": 11522,
          "sha512": "afdb1f1681ccb388dd0b9dbeb1170f1a132793b0fbfc9546e758ea6a0dac4109061842bcb4f37ddb7d07d2472e876a9fc82a611469a6686da9dc765d38e9e4de",
          "sha256": "252b78520fe8f43365576567b4746003c3fd1332791e81662df53e3a426ffdf6",
          "sha1": "e0f7ae34b2b64bf30bb8763d858ad15985b714c0",
          "md5": "d5dd7fb2fe7c4844258275e21e3af7b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.1-dev-sources.jar",
          "url": "qqrobot-framework-api-2.0.1-dev-sources.jar",
          "size": 4270,
          "sha512": "fe5943626aebfa7ae5cf9c0727f965cb54cc4289c5b224901753bec887e78915a5ca2e1d2b4fd3460c6953f94b87e7ab940bf892b45afa531e1167fbc080d20c",
          "sha256": "1b5b2b5165723783a9f4de52c0bbca36f321119460b40812c0c878bba1eb384d",
          "sha1": "7ee97ad35236b1d61664bd8d149f8bc491926077",
          "md5": "441fee870873ff5f4dae1d16b8411d68"
        }
      ]
    }
  ]
}
