{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "2.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.1-dev.jar",
          "url": "qqrobot-framework-api-2.0.1-dev.jar",
          "size": 11753,
          "sha512": "c37430476dec3dba538e1413da26b7b6cf5fd504531922c03f14fbb232535135bc57c3fd826a6c73bcabb4749e453ebdf9d084f6fbc7ff5bcc1f814d2696ee83",
          "sha256": "8953bf4d99ec089b571c7c5fedcbd0f25b618f55def79bd2af53c78fab269819",
          "sha1": "a75f40a239b781134f1f9f4258a540a47a26797a",
          "md5": "f8e3204d431d48e11b6def66c8e1b6da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.1-dev.jar",
          "url": "qqrobot-framework-api-2.0.1-dev.jar",
          "size": 11753,
          "sha512": "c37430476dec3dba538e1413da26b7b6cf5fd504531922c03f14fbb232535135bc57c3fd826a6c73bcabb4749e453ebdf9d084f6fbc7ff5bcc1f814d2696ee83",
          "sha256": "8953bf4d99ec089b571c7c5fedcbd0f25b618f55def79bd2af53c78fab269819",
          "sha1": "a75f40a239b781134f1f9f4258a540a47a26797a",
          "md5": "f8e3204d431d48e11b6def66c8e1b6da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.1-dev-sources.jar",
          "url": "qqrobot-framework-api-2.0.1-dev-sources.jar",
          "size": 4467,
          "sha512": "4275a566b63ab54be286d8614d62db233c0e117e2ae6a86446cbe42ef07e039bc795e705024b6ddc00ef86a12321c1bcb447585beb05432769009f3d73f7c457",
          "sha256": "0c6277ded2e2dcc0d67334ce9094198d75563e2a1fea6a6a92b67f28e6cbd9e3",
          "sha1": "d1e8a7f1f860d40aee1a55baac020d7d66b7fa0f",
          "md5": "de205468663df0105310d92cc14081fd"
        }
      ]
    }
  ]
}
