{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-framework-api",
    "version": "2.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.1-dev.jar",
          "url": "qqrobot-framework-api-2.0.1-dev.jar",
          "size": 8505,
          "sha512": "0dcb8df58b033415d55f166126cb145f1fe675be973825715688fa01577c8c6c11b24c184412dc302dd50923ec30fe61ae6f4392977a9d0d62fe58844e4db39a",
          "sha256": "60d8a77c9465fccb00ca44559f5428dd27e587a8682c094a4d9fa5b0ea16b1f7",
          "sha1": "5246f4e0e4c9c420cb02c9f2c23bd5aef3f622f2",
          "md5": "e06e91e57437bf84e14bef635a15ade1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.1-dev.jar",
          "url": "qqrobot-framework-api-2.0.1-dev.jar",
          "size": 8505,
          "sha512": "0dcb8df58b033415d55f166126cb145f1fe675be973825715688fa01577c8c6c11b24c184412dc302dd50923ec30fe61ae6f4392977a9d0d62fe58844e4db39a",
          "sha256": "60d8a77c9465fccb00ca44559f5428dd27e587a8682c094a4d9fa5b0ea16b1f7",
          "sha1": "5246f4e0e4c9c420cb02c9f2c23bd5aef3f622f2",
          "md5": "e06e91e57437bf84e14bef635a15ade1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-framework-api-2.0.1-dev-sources.jar",
          "url": "qqrobot-framework-api-2.0.1-dev-sources.jar",
          "size": 4448,
          "sha512": "2b896fea15821054ce77ca69064c8a8cff53ab698311d32790117a2278e5c4640532b52037afadaac60a7c086aceb535ae7682c4572ac134f0be59a297e616d1",
          "sha256": "bfd092a41345d3142381cd649d87d1241c051474a106d268e70dc503c54f524b",
          "sha1": "8b91c0eb3886c7fdb3f7c5f1417593d7c3fa45f3",
          "md5": "dcefbd50caf78e0fcc268149740617e4"
        }
      ]
    }
  ]
}
