{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "1.4.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "1.1.0-dev"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.4.0-dev.jar",
          "url": "qqrobot-spring-boot-starter-1.4.0-dev.jar",
          "size": 1181771,
          "sha512": "1d7a3940b28a517136996c15d4fb35bba3f38172049665a36fc3d7525e5eadf04b1ee234f38b6f780b2843abe7c4076c91c61bd3d095a80edff29ada1bc464e3",
          "sha256": "cf60bc26e5f55df8a8421879ea43702de41bbcf4c438d839015dbd9799e72dd1",
          "sha1": "4460c27a75e19699492776f39d41a6123d2f36e0",
          "md5": "bca31133cc44d9fdb54df3f985d0a6b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-framework-utils",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "1.1.0-dev"
          }
        },
        {
          "group": "net.mamoe",
          "module": "mirai-core-jvm",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.4.0-dev.jar",
          "url": "qqrobot-spring-boot-starter-1.4.0-dev.jar",
          "size": 1181771,
          "sha512": "1d7a3940b28a517136996c15d4fb35bba3f38172049665a36fc3d7525e5eadf04b1ee234f38b6f780b2843abe7c4076c91c61bd3d095a80edff29ada1bc464e3",
          "sha256": "cf60bc26e5f55df8a8421879ea43702de41bbcf4c438d839015dbd9799e72dd1",
          "sha1": "4460c27a75e19699492776f39d41a6123d2f36e0",
          "md5": "bca31133cc44d9fdb54df3f985d0a6b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.4.0-dev-sources.jar",
          "url": "qqrobot-spring-boot-starter-1.4.0-dev-sources.jar",
          "size": 1110560,
          "sha512": "d14384f4a706ed07a78d6ed3c429200761b913c18639d72c83e8390f90e1aeb5df8587ab9aad3694415c22adb824ef96c286e03cd7e38b43262fd58a9c140399",
          "sha256": "debbb8d2506bf20915f75715d57a29b537d4765a1bf6af4ef1529440a184829e",
          "sha1": "d566184afe881cb6bd12962355f391aa1beae22c",
          "md5": "d75c00de53a00fd42aae0ddd712a5b79"
        }
      ]
    }
  ]
}
