{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "1.4.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.4.0-dev.jar",
          "url": "qqrobot-spring-boot-starter-1.4.0-dev.jar",
          "size": 1178363,
          "sha512": "7be2dca034092b045d3fa60bef59eb8605cbd430349ab1fcd2add7b5b1b328c0ff5133afa2587e716a8e040c8eb60425fe7d2ebebaf20c8544f50318a0689225",
          "sha256": "46966f2ac87cd4721d0b2a4f4c3b44a210b4a2ece091cb95de8929e0feaa7d56",
          "sha1": "fe1dd2813d4f4650a8d06864bb12a89b1193e019",
          "md5": "c08a20db50d7ddc5e440a7a59419781d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-framework-utils",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "net.mamoe",
          "module": "mirai-core-jvm",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.4.0-dev.jar",
          "url": "qqrobot-spring-boot-starter-1.4.0-dev.jar",
          "size": 1178363,
          "sha512": "7be2dca034092b045d3fa60bef59eb8605cbd430349ab1fcd2add7b5b1b328c0ff5133afa2587e716a8e040c8eb60425fe7d2ebebaf20c8544f50318a0689225",
          "sha256": "46966f2ac87cd4721d0b2a4f4c3b44a210b4a2ece091cb95de8929e0feaa7d56",
          "sha1": "fe1dd2813d4f4650a8d06864bb12a89b1193e019",
          "md5": "c08a20db50d7ddc5e440a7a59419781d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.4.0-dev-sources.jar",
          "url": "qqrobot-spring-boot-starter-1.4.0-dev-sources.jar",
          "size": 1109064,
          "sha512": "9183382558ff33a3f663490ff67c7ccf67d93812c81e2bbdaa5712a183df4deee362729c80da8838f901bd211db4fd836636403c26a9e5c2eb72186e4d6c854f",
          "sha256": "538a4e7d214c09e9bcd529d7f583f23ebb92755853df0e97e1d56613f4bd4d5c",
          "sha1": "e967bef91d3d757f146eb3e1901ae6526a914052",
          "md5": "8781c7cd2fa0508b31904e82cc94c375"
        }
      ]
    }
  ]
}
