{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "1.4.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "1.1.0-dev"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.4.0-dev.jar",
          "url": "qqrobot-spring-boot-starter-1.4.0-dev.jar",
          "size": 1183749,
          "sha512": "cfe2968e81116f98f153159ef439d0f9b282f488022db436d4304e41a69098bce26229b106160b4687ac7f0e9477d17babb90667e5f7ba7d8465c63093073fdd",
          "sha256": "eb117ed260ccd3fe7cb78600440cc0e292f66c9b3a6927eb2a530a83a180c0bf",
          "sha1": "39c0624c934deb06f8822c6233dd43445f884fc1",
          "md5": "ee8da8a47b9aea2f865d202612f3ef32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.0.1-dev"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-framework-utils",
          "version": {
            "requires": "1.0.5-dev"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "1.1.0-dev"
          }
        },
        {
          "group": "net.mamoe",
          "module": "mirai-core-jvm",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.4.0-dev.jar",
          "url": "qqrobot-spring-boot-starter-1.4.0-dev.jar",
          "size": 1183749,
          "sha512": "cfe2968e81116f98f153159ef439d0f9b282f488022db436d4304e41a69098bce26229b106160b4687ac7f0e9477d17babb90667e5f7ba7d8465c63093073fdd",
          "sha256": "eb117ed260ccd3fe7cb78600440cc0e292f66c9b3a6927eb2a530a83a180c0bf",
          "sha1": "39c0624c934deb06f8822c6233dd43445f884fc1",
          "md5": "ee8da8a47b9aea2f865d202612f3ef32"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.4.0-dev-sources.jar",
          "url": "qqrobot-spring-boot-starter-1.4.0-dev-sources.jar",
          "size": 1110670,
          "sha512": "5a6bbc9fa38289d4f66bc8bd5c9d4da972d2102b416b18ccb4e57a4deca040f65dc58343e39efbedc5a7e3e5b1db17d0139a6d00aabcc21c1ab25fd02566dc94",
          "sha256": "d68133f0e3e840ee742df65ff0bcdfb6afa2f9050695419d9fb507488b302f96",
          "sha1": "5d12c85b26538bb3d86326577769d3ebd5b21c72",
          "md5": "dcf3e17d67e096988c033edcb333ea8c"
        }
      ]
    }
  ]
}
