{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle",
    "module": "honoka-gradle-utils",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.0.jar",
          "url": "honoka-gradle-utils-1.0.0.jar",
          "size": 21839,
          "sha512": "747d6de66a14d7c11ca000e7bfefc6489fa9d0b018793673f279baec2ffef03176714633282a3ff60f724205bca96e06f74536d40935a439b0f726b9cd7af49f",
          "sha256": "9444a8520056319039e4d18e4b0343613bdc459547b4f7aeb30697a8a36de8ff",
          "sha1": "09c7b3107abc9e57ff2edbbc31af6a26773d5827",
          "md5": "c71af51cf0e80797321fd00ec62428a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.0.jar",
          "url": "honoka-gradle-utils-1.0.0.jar",
          "size": 21839,
          "sha512": "747d6de66a14d7c11ca000e7bfefc6489fa9d0b018793673f279baec2ffef03176714633282a3ff60f724205bca96e06f74536d40935a439b0f726b9cd7af49f",
          "sha256": "9444a8520056319039e4d18e4b0343613bdc459547b4f7aeb30697a8a36de8ff",
          "sha1": "09c7b3107abc9e57ff2edbbc31af6a26773d5827",
          "md5": "c71af51cf0e80797321fd00ec62428a2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-gradle-utils-1.0.0-sources.jar",
          "url": "honoka-gradle-utils-1.0.0-sources.jar",
          "size": 4304,
          "sha512": "da0310f737447ee26e5f4d9f1b11693bbda7547fc4dcf0a60d6e97c09a39353d8adb6bd68a8e0c438cde75513772eb73d2eb6d3c638fa00432fa0de0c7a2fff8",
          "sha256": "21394a61fdc7993d07918adb05a53aadd2263e00d15fe998322ea651d5f70fd4",
          "sha1": "fe4634b0fb0214d435040b93e70ab7398069ed19",
          "md5": "7b6f0ee9b87ef75a06caf1b3858b67a7"
        }
      ]
    }
  ]
}
