{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.1.4-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.3-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.4-dev.jar",
          "url": "honoka-kotlin-utils-1.1.4-dev.jar",
          "size": 82533,
          "sha512": "c96643483c373c60bbf9694caf110fdef4f2327037c873d2cb3719163dec8613a5ec138a73ac4789ba44bf699abf325d97b43891374fd9d3d917c47325837f76",
          "sha256": "82c21d2f4bba2f0bebfd0d2922ea13466bca9504e07cd0c11f147c91a30d9e02",
          "sha1": "6dcbff654c142fe99721d3ab1829cf313b18edba",
          "md5": "37cfb5b72ee1b8e1d928aec38b2b191b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.3-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.4-dev.jar",
          "url": "honoka-kotlin-utils-1.1.4-dev.jar",
          "size": 82533,
          "sha512": "c96643483c373c60bbf9694caf110fdef4f2327037c873d2cb3719163dec8613a5ec138a73ac4789ba44bf699abf325d97b43891374fd9d3d917c47325837f76",
          "sha256": "82c21d2f4bba2f0bebfd0d2922ea13466bca9504e07cd0c11f147c91a30d9e02",
          "sha1": "6dcbff654c142fe99721d3ab1829cf313b18edba",
          "md5": "37cfb5b72ee1b8e1d928aec38b2b191b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.4-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.4-dev-sources.jar",
          "size": 21347,
          "sha512": "b2984f23f37be94e65529eeb76567b708b65bcd341c99176fdcdc760cb437f2bd4c45a8b801c1dd4a338697e2e48728441a3862bbe77f02a8bab2fcbbd852405",
          "sha256": "4b2f10063907a2ca9120a105bbc74070fb3a8f8e2afeb8fe163850291e41fcb6",
          "sha1": "da78a1b99ce64471a35a405479461766b5508692",
          "md5": "c4f7c61c2f680510ff9c27631b2b9c27"
        },
        {
          "name": "honoka-kotlin-utils-1.1.4-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.4-dev-sources.jar",
          "size": 21347,
          "sha512": "b2984f23f37be94e65529eeb76567b708b65bcd341c99176fdcdc760cb437f2bd4c45a8b801c1dd4a338697e2e48728441a3862bbe77f02a8bab2fcbbd852405",
          "sha256": "4b2f10063907a2ca9120a105bbc74070fb3a8f8e2afeb8fe163850291e41fcb6",
          "sha1": "da78a1b99ce64471a35a405479461766b5508692",
          "md5": "c4f7c61c2f680510ff9c27631b2b9c27"
        }
      ]
    }
  ]
}
