{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.1.4-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.3-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.4-dev.jar",
          "url": "honoka-kotlin-utils-1.1.4-dev.jar",
          "size": 78226,
          "sha512": "7e40e8b1b55ac5fcbe55958a0715d20ac85289754d433ff5e553d0748e158cdf5ab5b9d6a3adfd101012c2e4d6b9e5eb999906ebd4846ecd3ce2cdae1ce5385a",
          "sha256": "d61c2a6e7980d819e7cdb5f1de70551869815ebcadfea51b2fb52b87ffd4b007",
          "sha1": "2ee017fe59321100616eb513e6a5d69794a5f82c",
          "md5": "01ad66ccf32a4cdd1bda887e16a9aa56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.3-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.4-dev.jar",
          "url": "honoka-kotlin-utils-1.1.4-dev.jar",
          "size": 78226,
          "sha512": "7e40e8b1b55ac5fcbe55958a0715d20ac85289754d433ff5e553d0748e158cdf5ab5b9d6a3adfd101012c2e4d6b9e5eb999906ebd4846ecd3ce2cdae1ce5385a",
          "sha256": "d61c2a6e7980d819e7cdb5f1de70551869815ebcadfea51b2fb52b87ffd4b007",
          "sha1": "2ee017fe59321100616eb513e6a5d69794a5f82c",
          "md5": "01ad66ccf32a4cdd1bda887e16a9aa56"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.4-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.4-dev-sources.jar",
          "size": 20724,
          "sha512": "fddc8d50099a536e23b3d0ed008a15b2edd39853023b3545aec6785d4742ab4abc793b6961932ed17e80eda9e04316a1c447efe00ce841035c8921496b92affb",
          "sha256": "460b00df25df9c584e0c7b5f0b1e251d41fcebab3bae40d11162007c6a2ca3f6",
          "sha1": "599f2e3729c2b8dc8cfc5dc306dcef37fc51a9ef",
          "md5": "c1788129dbfb2e8bac9221f45a50adbe"
        },
        {
          "name": "honoka-kotlin-utils-1.1.4-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.4-dev-sources.jar",
          "size": 20724,
          "sha512": "fddc8d50099a536e23b3d0ed008a15b2edd39853023b3545aec6785d4742ab4abc793b6961932ed17e80eda9e04316a1c447efe00ce841035c8921496b92affb",
          "sha256": "460b00df25df9c584e0c7b5f0b1e251d41fcebab3bae40d11162007c6a2ca3f6",
          "sha1": "599f2e3729c2b8dc8cfc5dc306dcef37fc51a9ef",
          "md5": "c1788129dbfb2e8bac9221f45a50adbe"
        }
      ]
    }
  ]
}
