{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "1.1.4-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.3-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.4-dev.jar",
          "url": "honoka-kotlin-utils-1.1.4-dev.jar",
          "size": 67098,
          "sha512": "99dd0df9d56bd6440da750ec3a9e7377b7d4a5072d043c0434ee63cb4cf94b65a7eb61398a5a9329a1c0f51a319e17ae7ab8f9d7e6d50cf536babf577e8206c4",
          "sha256": "8496a24c5d0bfd94109e1a7eb330982c7060f7e90ec444388d400b0c1adecadf",
          "sha1": "81a9b39e772cea096456d93566f924f406eff646",
          "md5": "2e2a7988bfbd75f71553981f546b18ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.18"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.1.3-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.4-dev.jar",
          "url": "honoka-kotlin-utils-1.1.4-dev.jar",
          "size": 67098,
          "sha512": "99dd0df9d56bd6440da750ec3a9e7377b7d4a5072d043c0434ee63cb4cf94b65a7eb61398a5a9329a1c0f51a319e17ae7ab8f9d7e6d50cf536babf577e8206c4",
          "sha256": "8496a24c5d0bfd94109e1a7eb330982c7060f7e90ec444388d400b0c1adecadf",
          "sha1": "81a9b39e772cea096456d93566f924f406eff646",
          "md5": "2e2a7988bfbd75f71553981f546b18ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-1.1.4-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.4-dev-sources.jar",
          "size": 18650,
          "sha512": "fba9b9141eb8879a46bbad57a0b88bc58df57346135d9f3abc73b476878f3f7ebd9311f9d3b56585cd07c45704df72e1dc64a75e8fde5f47c9e96f1c53aba4a4",
          "sha256": "5df55b97f5f27e7c16cb7a37d614502bbac56b41664230057b22778dbd9059f6",
          "sha1": "e1e09b1bbbf8f4ab6f6423ac3ffa8b40e5444ff1",
          "md5": "f9eb5970a1d3e77012e5f5af2b399036"
        },
        {
          "name": "honoka-kotlin-utils-1.1.4-dev-sources.jar",
          "url": "honoka-kotlin-utils-1.1.4-dev-sources.jar",
          "size": 18650,
          "sha512": "fba9b9141eb8879a46bbad57a0b88bc58df57346135d9f3abc73b476878f3f7ebd9311f9d3b56585cd07c45704df72e1dc64a75e8fde5f47c9e96f1c53aba4a4",
          "sha256": "5df55b97f5f27e7c16cb7a37d614502bbac56b41664230057b22778dbd9059f6",
          "sha1": "e1e09b1bbbf8f4ab6f6423ac3ffa8b40e5444ff1",
          "md5": "f9eb5970a1d3e77012e5f5af2b399036"
        }
      ]
    }
  ]
}
