{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-json-gson",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-json-api",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-gson-1.1.3.jar",
          "url": "honoka-json-gson-1.1.3.jar",
          "size": 11975,
          "sha512": "2dfd08c3ff764848c9eefad5c86d82d3125c39d283797c43a3fef240435830851b975d77f6cf3b2f15c58aa73940c3cbb40a702c25e7c871d2422098b2884e10",
          "sha256": "061d4d87ab98e5bbaaf3de36c5cc218a4a36cedbafa40e9c3b2860e8aed469f6",
          "sha1": "c4c227b5b376ea1193d1ae2a0a55680abd6b732b",
          "md5": "c2c5b5a13b5bb867aebed6f0c6dfd6a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-json-api",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-gson-1.1.3.jar",
          "url": "honoka-json-gson-1.1.3.jar",
          "size": 11975,
          "sha512": "2dfd08c3ff764848c9eefad5c86d82d3125c39d283797c43a3fef240435830851b975d77f6cf3b2f15c58aa73940c3cbb40a702c25e7c871d2422098b2884e10",
          "sha256": "061d4d87ab98e5bbaaf3de36c5cc218a4a36cedbafa40e9c3b2860e8aed469f6",
          "sha1": "c4c227b5b376ea1193d1ae2a0a55680abd6b732b",
          "md5": "c2c5b5a13b5bb867aebed6f0c6dfd6a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-json-gson-1.1.3-sources.jar",
          "url": "honoka-json-gson-1.1.3-sources.jar",
          "size": 6310,
          "sha512": "f2ba142efca455559074dc52e81ab206b30009b93d31c3f8428023ebfc68000968727700cc9503849db716fe0855a07c515b3e28a55652e09c7f2316c5aec6eb",
          "sha256": "aeb3ee0794c235c75840108bbcbf1b88ba5999e597496d5ba2220a6bf639b2d5",
          "sha1": "dcb79a522c13e3fa1f41c7295c56799a4b95363d",
          "md5": "beb10082f1ca77a294892ae3abf7d244"
        }
      ]
    }
  ]
}
