{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.0.4-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.3-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.4-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.4-dev.jar",
          "size": 68571,
          "sha512": "cdeea8acc1c925f1a7102f9d0ebaa2cb0eed282764e697ecb88a7cfefdaa818780590a1f1aa026bf0266844d7822b48853fee15cd1beeb612b11695c6ed9fef7",
          "sha256": "41ca95233eee33605db6e7feea2b1ffa5ae5d716b63f0568ecc4d956365b90fe",
          "sha1": "610acf80a2cc2d31a1018ff0e4aa1af187c5d230",
          "md5": "2e1167cb564f33854b16f1e9cec3fa61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.3-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.4-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.4-dev.jar",
          "size": 68571,
          "sha512": "cdeea8acc1c925f1a7102f9d0ebaa2cb0eed282764e697ecb88a7cfefdaa818780590a1f1aa026bf0266844d7822b48853fee15cd1beeb612b11695c6ed9fef7",
          "sha256": "41ca95233eee33605db6e7feea2b1ffa5ae5d716b63f0568ecc4d956365b90fe",
          "sha1": "610acf80a2cc2d31a1018ff0e4aa1af187c5d230",
          "md5": "2e1167cb564f33854b16f1e9cec3fa61"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.4-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.4-dev-sources.jar",
          "size": 19779,
          "sha512": "b1879e26750c5d4c3369fd765f0e373c3ad38d38b5f8aaf4820b3025b8f43b3c197045f6c875d45c8ab775b0233b9051ad5acec8c82b9b2aeab7f253ddeeed56",
          "sha256": "3f66f76a54b667c81d5271eea72ce8dd5cb63d0771b1bcc7d63abf9dfef3f1ef",
          "sha1": "431064af28661698a6b749409f079c5888661605",
          "md5": "eb3dcc308b527bc2e1fef397509505e2"
        },
        {
          "name": "honoka-spring-boot-starter-1.0.4-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.4-dev-sources.jar",
          "size": 19779,
          "sha512": "b1879e26750c5d4c3369fd765f0e373c3ad38d38b5f8aaf4820b3025b8f43b3c197045f6c875d45c8ab775b0233b9051ad5acec8c82b9b2aeab7f253ddeeed56",
          "sha256": "3f66f76a54b667c81d5271eea72ce8dd5cb63d0771b1bcc7d63abf9dfef3f1ef",
          "sha1": "431064af28661698a6b749409f079c5888661605",
          "md5": "eb3dcc308b527bc2e1fef397509505e2"
        }
      ]
    }
  ]
}
