{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-spring-boot-starter",
    "version": "1.0.4-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.3-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.4-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.4-dev.jar",
          "size": 65164,
          "sha512": "1d29e525fafc41ca2ab7f73ace24fb92735178bbaacf39b4bca9f3f968785bf78c094bb1d2add839c5ea6def4a056fc120b36409b44fad9981a743af913d1cba",
          "sha256": "13431ad4ea771906a95c305d5c68264c2555e837cc8a5b4261793c6e032dde42",
          "sha1": "d1fb23d4e51697eea3f40dba4202697a0d1a04d3",
          "md5": "ade300a40859b1a0eda9c549db481631"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "3.5.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-kotlin-utils",
          "version": {
            "requires": "1.1.3-dev"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.4-dev.jar",
          "url": "honoka-spring-boot-starter-1.0.4-dev.jar",
          "size": 65164,
          "sha512": "1d29e525fafc41ca2ab7f73ace24fb92735178bbaacf39b4bca9f3f968785bf78c094bb1d2add839c5ea6def4a056fc120b36409b44fad9981a743af913d1cba",
          "sha256": "13431ad4ea771906a95c305d5c68264c2555e837cc8a5b4261793c6e032dde42",
          "sha1": "d1fb23d4e51697eea3f40dba4202697a0d1a04d3",
          "md5": "ade300a40859b1a0eda9c549db481631"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-spring-boot-starter-1.0.4-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.4-dev-sources.jar",
          "size": 19444,
          "sha512": "7d02489d34e041b8b5c8547aeba97444a01296a65d6053ac3872f24701fb194b1b8f01f1cded58e42b2cea679028b441ccd5ee14fe499acfab6d7bc35c8084fe",
          "sha256": "dfc242cc72550e8d213a34786b4b368cffdc4613acad9597a32d44781ed9be51",
          "sha1": "deb6df9192dbc30f858af422955f18ee5048273d",
          "md5": "7019fb1092b41eb41baa9f705fc9a276"
        },
        {
          "name": "honoka-spring-boot-starter-1.0.4-dev-sources.jar",
          "url": "honoka-spring-boot-starter-1.0.4-dev-sources.jar",
          "size": 19444,
          "sha512": "7d02489d34e041b8b5c8547aeba97444a01296a65d6053ac3872f24701fb194b1b8f01f1cded58e42b2cea679028b441ccd5ee14fe499acfab6d7bc35c8084fe",
          "sha256": "dfc242cc72550e8d213a34786b4b368cffdc4613acad9597a32d44781ed9be51",
          "sha1": "deb6df9192dbc30f858af422955f18ee5048273d",
          "md5": "7019fb1092b41eb41baa9f705fc9a276"
        }
      ]
    }
  ]
}
