{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.lavender",
    "module": "lavender-data-source-starter",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lavender-data-source-starter-1.0.0.jar",
          "url": "lavender-data-source-starter-1.0.0.jar",
          "size": 14554,
          "sha512": "5a19e19d0652bfe6b5e12f0387a2ce9177e952ff87e4f496b5727a0144e62d6c3a4cfdcffa9df24a9bf68633075da91f297e70ecac2cc96b163071b656aad170",
          "sha256": "2f16026d697959a5ce021bd49dc863ca7177373c98fbeaf7b728413191027e3a",
          "sha1": "42adce109b85d62a91b44a7d66ab2bd848b844a9",
          "md5": "24435e689e06e7662bed8ba5e1a23800"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "de.honoka.lavender",
          "module": "lavender-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-framework-utils",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.18"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        }
      ],
      "files": [
        {
          "name": "lavender-data-source-starter-1.0.0.jar",
          "url": "lavender-data-source-starter-1.0.0.jar",
          "size": 14554,
          "sha512": "5a19e19d0652bfe6b5e12f0387a2ce9177e952ff87e4f496b5727a0144e62d6c3a4cfdcffa9df24a9bf68633075da91f297e70ecac2cc96b163071b656aad170",
          "sha256": "2f16026d697959a5ce021bd49dc863ca7177373c98fbeaf7b728413191027e3a",
          "sha1": "42adce109b85d62a91b44a7d66ab2bd848b844a9",
          "md5": "24435e689e06e7662bed8ba5e1a23800"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavender-data-source-starter-1.0.0-sources.jar",
          "url": "lavender-data-source-starter-1.0.0-sources.jar",
          "size": 6020,
          "sha512": "86c55b3d5db34963d1514197f73d2f53b005db3458e4f57f6013463d0005157a4b350f26352bffac57beb3a388881315720f3ee17952c89a3165bd487aa06a3c",
          "sha256": "6e2f041e72a84467a4311b4d42fbc2bd8862af10d516339c23fb32478b5bcf2a",
          "sha1": "97a4dcc3eddc003a62eb4dcd4023b70380f9cef7",
          "md5": "6b2ccd6e937901a62d6acae33ba30839"
        }
      ]
    }
  ]
}
