{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-utils",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.6.jar",
          "url": "honoka-utils-1.0.6.jar",
          "size": 59368,
          "sha512": "be8620c7e3e767e887b7d8ce8834fed9ffd764ac6056a88e569712028140ea4c15418d41199fa69ae3cd9793144bc5462217814626e5e135e503a3979f9fa97f",
          "sha256": "42faadfa5c6a26020e4a233d757dc7720e50622a67d0d032a53a8d54ee3134f4",
          "sha1": "f9197e4e8205c3ffae4280f13dc6c5e3982d1982",
          "md5": "b081c7191a6050284ddbe0b29c428e16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "gui.ava",
          "module": "html2image",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-utils-1.0.6.jar",
          "url": "honoka-utils-1.0.6.jar",
          "size": 59368,
          "sha512": "be8620c7e3e767e887b7d8ce8834fed9ffd764ac6056a88e569712028140ea4c15418d41199fa69ae3cd9793144bc5462217814626e5e135e503a3979f9fa97f",
          "sha256": "42faadfa5c6a26020e4a233d757dc7720e50622a67d0d032a53a8d54ee3134f4",
          "sha1": "f9197e4e8205c3ffae4280f13dc6c5e3982d1982",
          "md5": "b081c7191a6050284ddbe0b29c428e16"
        }
      ]
    }
  ]
}
