{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.3.3.jar",
          "url": "qqrobot-spring-boot-starter-1.3.3.jar",
          "size": 1147194,
          "sha512": "dadffe0a6c790742f95341e119c375e4ee03e38508ecebc6715e114b8d5ab36ea0a82805efd435d5cc6d81119c8e2ff84bce81dfd0fe87ff92292597105bd9f0",
          "sha256": "a13d29822ddeb9399a3d78c391c2dbdcc864a55cf682dd4348096794cefeb5ec",
          "sha1": "58d56a09b8a0369042507462f1019c5ddc3be3ae",
          "md5": "47f9f86a7f29909efcd037ac9c7692f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-framework-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.mamoe",
          "module": "mirai-core-jvm",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.3.3.jar",
          "url": "qqrobot-spring-boot-starter-1.3.3.jar",
          "size": 1147194,
          "sha512": "dadffe0a6c790742f95341e119c375e4ee03e38508ecebc6715e114b8d5ab36ea0a82805efd435d5cc6d81119c8e2ff84bce81dfd0fe87ff92292597105bd9f0",
          "sha256": "a13d29822ddeb9399a3d78c391c2dbdcc864a55cf682dd4348096794cefeb5ec",
          "sha1": "58d56a09b8a0369042507462f1019c5ddc3be3ae",
          "md5": "47f9f86a7f29909efcd037ac9c7692f4"
        }
      ]
    }
  ]
}
