{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.qqrobot",
    "module": "qqrobot-spring-boot-starter",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.3.3.jar",
          "url": "qqrobot-spring-boot-starter-1.3.3.jar",
          "size": 1147194,
          "sha512": "1b8a27c76b4fd886b6fcc1e207c4e375e870d83f3053796dfe50b8ab013aa0d4acf2055b79a1afc4b242da99311e5333da05d2d046bf793e69a4653dc69d17bc",
          "sha256": "3326d366e802a1fc900b8c5d8e87fece2f455b11285ab90a3d627ed8cbfa4680",
          "sha1": "766332a7c53a7a1a58648f361c93152c518b304e",
          "md5": "4c3be5f68e9568ca6defda587146bdfe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-websocket"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-framework-utils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.mamoe",
          "module": "mirai-core-jvm",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson"
        },
        {
          "group": "com.github.houbb",
          "module": "opencc4j",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator"
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.1.214"
          }
        },
        {
          "group": "de.honoka.qqrobot",
          "module": "qqrobot-framework-api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "qqrobot-spring-boot-starter-1.3.3.jar",
          "url": "qqrobot-spring-boot-starter-1.3.3.jar",
          "size": 1147194,
          "sha512": "1b8a27c76b4fd886b6fcc1e207c4e375e870d83f3053796dfe50b8ab013aa0d4acf2055b79a1afc4b242da99311e5333da05d2d046bf793e69a4653dc69d17bc",
          "sha256": "3326d366e802a1fc900b8c5d8e87fece2f455b11285ab90a3d627ed8cbfa4680",
          "sha1": "766332a7c53a7a1a58648f361c93152c518b304e",
          "md5": "4c3be5f68e9568ca6defda587146bdfe"
        }
      ]
    }
  ]
}
