{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "2.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.1-dev.jar",
          "url": "honoka-kotlin-utils-2.0.1-dev.jar",
          "size": 11026,
          "sha512": "f811a2b99d08c68f980a0f5cb08b3a6305f68a4f9f5d24b700b26974cbd0424f0a5995401ecd195e243244567e28c0528d1ffb5c8c359b9e97e23207b57f23df",
          "sha256": "ac7bc78e9a1ed60deabbb09b3f66d4f8c1ccd0eaa9b20204c9db506b345d0c3f",
          "sha1": "c47b666e9de75ee9db97f6c3069b4ea4c80ab913",
          "md5": "1e032f7a94b4551b54b4a45115fe5dcb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.1-dev.jar",
          "url": "honoka-kotlin-utils-2.0.1-dev.jar",
          "size": 11026,
          "sha512": "f811a2b99d08c68f980a0f5cb08b3a6305f68a4f9f5d24b700b26974cbd0424f0a5995401ecd195e243244567e28c0528d1ffb5c8c359b9e97e23207b57f23df",
          "sha256": "ac7bc78e9a1ed60deabbb09b3f66d4f8c1ccd0eaa9b20204c9db506b345d0c3f",
          "sha1": "c47b666e9de75ee9db97f6c3069b4ea4c80ab913",
          "md5": "1e032f7a94b4551b54b4a45115fe5dcb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.1-dev-sources.jar",
          "url": "honoka-kotlin-utils-2.0.1-dev-sources.jar",
          "size": 4690,
          "sha512": "52ff16447460070d2ce4e829a02de93f1a80e24c5fab85cbc01cf73c7bd851d0c4418f9caeb7c821500089811de5660ef1f16d1fb8c39d6c44538a5ab1c71fd9",
          "sha256": "4708b85839de30def7ddc08ff262db450b832924e4f1dad5b6641ecaf4f0e2a0",
          "sha1": "e04744181f878508199ba865f4e64d90dd07975b",
          "md5": "2467443061f2176decd4570f0fd42d55"
        }
      ]
    }
  ]
}
