{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "2.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.1-dev.jar",
          "url": "honoka-kotlin-utils-2.0.1-dev.jar",
          "size": 11026,
          "sha512": "7ab5b0b32058a5770bebce929c5c878c24929370bb5de2d48244d297a77c3ff31e044e1b91833d1eee1ef416555bffb2c42d08484a792ddd4091cec506595b05",
          "sha256": "c5c289997a220ebfcea086ce344bf405fbe534520bb833b13e4607fac643bd39",
          "sha1": "2064e6a148a919de1acefa1516a3c46f3991ddbe",
          "md5": "925d97b21a3e3fd578fdb25ac66f51b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.1-dev.jar",
          "url": "honoka-kotlin-utils-2.0.1-dev.jar",
          "size": 11026,
          "sha512": "7ab5b0b32058a5770bebce929c5c878c24929370bb5de2d48244d297a77c3ff31e044e1b91833d1eee1ef416555bffb2c42d08484a792ddd4091cec506595b05",
          "sha256": "c5c289997a220ebfcea086ce344bf405fbe534520bb833b13e4607fac643bd39",
          "sha1": "2064e6a148a919de1acefa1516a3c46f3991ddbe",
          "md5": "925d97b21a3e3fd578fdb25ac66f51b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.1-dev-sources.jar",
          "url": "honoka-kotlin-utils-2.0.1-dev-sources.jar",
          "size": 4690,
          "sha512": "6fd35dc383631508c7a80c6aa6a16de627592635547e421cd61dff091dd0310d5130bfb0bcdf8a080a192cad1e865b6cdc0cbdede3fcac24fbcb7f001576d15a",
          "sha256": "2717d9ef4e1fabf4ba05363e77ce33fb259673a6bff99b634d503a9d2b86843b",
          "sha1": "5b1c195e2f6b68530346813db8285ff614ee70ce",
          "md5": "fe33d6cb7add4d76842930b15e01c42f"
        }
      ]
    }
  ]
}
