{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-kotlin-utils",
    "version": "2.0.1-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.1-dev.jar",
          "url": "honoka-kotlin-utils-2.0.1-dev.jar",
          "size": 11026,
          "sha512": "eb331f4dfd1a9d542d591a19b6cd1ab3ae4f457655620de526ce628bed3b2b1e30cdc1d6277c11dce17b7411754bf6818fde3c80c66ed734389f37e7c4c6232f",
          "sha256": "19b2cab4d31ba10972dd3a1df7f9aba665e802118eaa1dff90e4196993f367a8",
          "sha1": "ccb71fb53121bf5c3762d6bdbf2807cb44377434",
          "md5": "57a2c345d50cd2b39b4f02142c9911d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "2.0.1-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.1-dev.jar",
          "url": "honoka-kotlin-utils-2.0.1-dev.jar",
          "size": 11026,
          "sha512": "eb331f4dfd1a9d542d591a19b6cd1ab3ae4f457655620de526ce628bed3b2b1e30cdc1d6277c11dce17b7411754bf6818fde3c80c66ed734389f37e7c4c6232f",
          "sha256": "19b2cab4d31ba10972dd3a1df7f9aba665e802118eaa1dff90e4196993f367a8",
          "sha1": "ccb71fb53121bf5c3762d6bdbf2807cb44377434",
          "md5": "57a2c345d50cd2b39b4f02142c9911d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-kotlin-utils-2.0.1-dev-sources.jar",
          "url": "honoka-kotlin-utils-2.0.1-dev-sources.jar",
          "size": 4690,
          "sha512": "1d861869523aab4f1b2e2844ec9e8c940dc5e16f60fb5b32db73bf3d907ab13842ad8c60aa957b80ae470b9aef8976f9d4303f9fd703cba9125acec2cc0d043f",
          "sha256": "24fa6394cfa824e9d0200ddc5d31207a2201dfc370a3ab1f334a2d8a02a39bd8",
          "sha1": "7dcf42a6f138a9c7c724c283d553ab953b34a43e",
          "md5": "6e9269a39c8f86990c8f118ea4f2031d"
        }
      ]
    }
  ]
}
