{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-json-gson",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-json-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-gson-1.1.2.jar",
          "url": "honoka-json-gson-1.1.2.jar",
          "size": 11607,
          "sha512": "b61cdfc9437182e9b3069ab1b2a3aa6c5fc8ac26598f84ee9c7574ae846bab3a2b43c95470354c98b104af823beea04d0f8bf69a4e6cda32631ffc469cf0ef8c",
          "sha256": "665c3d8425fd856b5cb3733b3c9d99f556b9fcece122ae4ff501d5b5954ed7c3",
          "sha1": "e8b6aa686b4710dd80326757bd3ac558db1deacd",
          "md5": "825dece3f1c79986774fe6e8ac433a3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "de.honoka.sdk",
          "module": "honoka-json-api",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-json-gson-1.1.2.jar",
          "url": "honoka-json-gson-1.1.2.jar",
          "size": 11607,
          "sha512": "b61cdfc9437182e9b3069ab1b2a3aa6c5fc8ac26598f84ee9c7574ae846bab3a2b43c95470354c98b104af823beea04d0f8bf69a4e6cda32631ffc469cf0ef8c",
          "sha256": "665c3d8425fd856b5cb3733b3c9d99f556b9fcece122ae4ff501d5b5954ed7c3",
          "sha1": "e8b6aa686b4710dd80326757bd3ac558db1deacd",
          "md5": "825dece3f1c79986774fe6e8ac433a3d"
        }
      ]
    }
  ]
}
