{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-android-plugin",
    "version": "1.1.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-android-plugin-1.1.0-dev.jar",
          "url": "honoka-android-plugin-1.1.0-dev.jar",
          "size": 23798,
          "sha512": "5de16f5f0cb83fc70d06b3044587085bb1ca2586304706fcc80c99db1e6fe1db0865813e8cc255b94d66af2d9ee37510c41cdd7aa6c367af44d6aa0b4bb0249b",
          "sha256": "a68c7f71c9b0d5ffc09c00848886e4371ba4cc19951e8d6a836fbb386c18a371",
          "sha1": "512e2fa0366abb2aec7ff9c1af1a2c0f49d09946",
          "md5": "97fa82768075c265149a871eed00fe18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle.plugin",
          "module": "honoka-basic-plugin",
          "version": {
            "requires": "1.1.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-android-plugin-1.1.0-dev.jar",
          "url": "honoka-android-plugin-1.1.0-dev.jar",
          "size": 23798,
          "sha512": "5de16f5f0cb83fc70d06b3044587085bb1ca2586304706fcc80c99db1e6fe1db0865813e8cc255b94d66af2d9ee37510c41cdd7aa6c367af44d6aa0b4bb0249b",
          "sha256": "a68c7f71c9b0d5ffc09c00848886e4371ba4cc19951e8d6a836fbb386c18a371",
          "sha1": "512e2fa0366abb2aec7ff9c1af1a2c0f49d09946",
          "md5": "97fa82768075c265149a871eed00fe18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-android-plugin-1.1.0-dev-sources.jar",
          "url": "honoka-android-plugin-1.1.0-dev-sources.jar",
          "size": 4621,
          "sha512": "5c78d5925b60a441f1531706c489f99810d593287d3ba73547e6e9205f440d9e5b6716785039190db633ef2f1990ba9347ff69d9cd7060017356366b1dc9f9b6",
          "sha256": "615302dfbb7cab3eba097213af535b34e88767304f09aa8bc6f11d0b0fc04845",
          "sha1": "a9d1c0debfa4f7ba1474fb4927d56a5d093f34f8",
          "md5": "6dff63324fd7466b21f4c2f8ce9e23e9"
        }
      ]
    }
  ]
}
