{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-android-plugin",
    "version": "1.1.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-android-plugin-1.1.0-dev.jar",
          "url": "honoka-android-plugin-1.1.0-dev.jar",
          "size": 22301,
          "sha512": "69dcc66f0b445ffc87405636863eabef6fe566a8d16ecf3931ea1c37e43668affaeb1c6a231e76d856311f2b292b1ff877a86a31a249a64638fa67f0489c7a31",
          "sha256": "38707e8cfb82bde03ffbca119a0ea4d3ae76565be6b7c827ebee8b009a32a81b",
          "sha1": "2216d200a71180fab269957b61750bd8ef518f03",
          "md5": "d0d29841e0024aaa50d80e98fa41d355"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle.plugin",
          "module": "honoka-basic-plugin",
          "version": {
            "requires": "1.1.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-android-plugin-1.1.0-dev.jar",
          "url": "honoka-android-plugin-1.1.0-dev.jar",
          "size": 22301,
          "sha512": "69dcc66f0b445ffc87405636863eabef6fe566a8d16ecf3931ea1c37e43668affaeb1c6a231e76d856311f2b292b1ff877a86a31a249a64638fa67f0489c7a31",
          "sha256": "38707e8cfb82bde03ffbca119a0ea4d3ae76565be6b7c827ebee8b009a32a81b",
          "sha1": "2216d200a71180fab269957b61750bd8ef518f03",
          "md5": "d0d29841e0024aaa50d80e98fa41d355"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-android-plugin-1.1.0-dev-sources.jar",
          "url": "honoka-android-plugin-1.1.0-dev-sources.jar",
          "size": 4215,
          "sha512": "3a03f7a3dc4e95ac0317ada138303b1d952c5af188b8c91703b5ba84fbb32e008632ac445910e4ff5c29fa78f86c3d0be17e6d0a0f5916ce95cf17faf6c4ae04",
          "sha256": "7d724ae82e36128ae2d53fa1ec805160f4bf7e3598e7d2bbf81c2f0093529651",
          "sha1": "554ce5029d3ec7516d3eb8b56a0a97cff0e43913",
          "md5": "0e9fdc7b66c063924d89632d13fc7fc4"
        }
      ]
    }
  ]
}
