{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.gradle.plugin",
    "module": "honoka-android-plugin",
    "version": "1.1.0-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "honoka-android-plugin-1.1.0-dev.jar",
          "url": "honoka-android-plugin-1.1.0-dev.jar",
          "size": 23887,
          "sha512": "7095b6b80c1feb4c55cffdf9420c0a9754386b5c3d9b5f8ba8fc411fe65086fb7be336a5be5f668fda03ed77892c38bc031bbd3244bea93df9918d9a01859c97",
          "sha256": "a6ccd31c89f4652da20420fd764ac10bdac6d953cf47508e63313625a9365dd5",
          "sha1": "d0d5d277bce63e29324430a3fb68fcb70761fae0",
          "md5": "7de3fc6674a8f7596f8712035b2dabbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.honoka.gradle.plugin",
          "module": "honoka-basic-plugin",
          "version": {
            "requires": "1.1.0-dev"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-android-plugin-1.1.0-dev.jar",
          "url": "honoka-android-plugin-1.1.0-dev.jar",
          "size": 23887,
          "sha512": "7095b6b80c1feb4c55cffdf9420c0a9754386b5c3d9b5f8ba8fc411fe65086fb7be336a5be5f668fda03ed77892c38bc031bbd3244bea93df9918d9a01859c97",
          "sha256": "a6ccd31c89f4652da20420fd764ac10bdac6d953cf47508e63313625a9365dd5",
          "sha1": "d0d5d277bce63e29324430a3fb68fcb70761fae0",
          "md5": "7de3fc6674a8f7596f8712035b2dabbe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-android-plugin-1.1.0-dev-sources.jar",
          "url": "honoka-android-plugin-1.1.0-dev-sources.jar",
          "size": 4672,
          "sha512": "f694f8f3623ca4bba23f19e2eb967b5f90a99154687d884ef484aa7ba92afba511e0a60b5c1db210f833d4723483a1a1943d33c57992117cc5d1fd528410803b",
          "sha256": "5eed22670d36aea9899c8a4f783e9de10f779de74005830f8433bd380b4f428d",
          "sha1": "b996681dc6b10639c10222176111968fa7c31414",
          "md5": "9b6ba0e6031db88c7b25c0cdd386f748"
        }
      ]
    }
  ]
}
