{
  "formatVersion": "1.1",
  "component": {
    "group": "de.honoka.sdk",
    "module": "honoka-framework-utils",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.3.jar",
          "url": "honoka-framework-utils-1.0.3.jar",
          "size": 16482,
          "sha512": "aeb150a11c96cae29e452328254df02c0da3a4b29f7db3cdef04b6671c9af419f736737d6d407cace461e0596cb007f5c96aae557116d06aab8036fc322cd22a",
          "sha256": "f3dd98c453a24525bf4448d09f93a96c47c711d19050bc16fdfce4be99c28795",
          "sha1": "c77d503408edc62a5d4f163e539dc81605110ccb",
          "md5": "7983a385ce39a4721795e758268f5302"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.honoka.sdk",
          "module": "honoka-utils",
          "version": {
            "requires": "1.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "honoka-framework-utils-1.0.3.jar",
          "url": "honoka-framework-utils-1.0.3.jar",
          "size": 16482,
          "sha512": "aeb150a11c96cae29e452328254df02c0da3a4b29f7db3cdef04b6671c9af419f736737d6d407cace461e0596cb007f5c96aae557116d06aab8036fc322cd22a",
          "sha256": "f3dd98c453a24525bf4448d09f93a96c47c711d19050bc16fdfce4be99c28795",
          "sha1": "c77d503408edc62a5d4f163e539dc81605110ccb",
          "md5": "7983a385ce39a4721795e758268f5302"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "honoka-framework-utils-1.0.3-sources.jar",
          "url": "honoka-framework-utils-1.0.3-sources.jar",
          "size": 11714,
          "sha512": "eefba0f2ac7979af21b846dfdae46e9b4194656fd02eb3e5186046bc9b4acf0efe623159a6d8fdef7b0554cd8e90dc5489f4865200b1a8219a126495c9d00ab4",
          "sha256": "997d44418fe498a36ba0da88649e091044798a9c6533afc8007339fbdab7bef2",
          "sha1": "14f07fad4f91e53bff1832ca95c850d70bfd33f1",
          "md5": "6b1b4de0f75642eda2ccd6e8bf2a3f9a"
        }
      ]
    }
  ]
}
